// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from './types';
import { ch01 } from './chapters/ch-01';
import { ch02 } from './chapters/ch-02';
import { ch03 } from './chapters/ch-03';
import { ch04 } from './chapters/ch-04';
import { ch05 } from './chapters/ch-05';
import { ch06 } from './chapters/ch-06';
import { ch07 } from './chapters/ch-07';
import { ch08 } from './chapters/ch-08';
import { ch09 } from './chapters/ch-09';
import { ch10 } from './chapters/ch-10';
import { ch11 } from './chapters/ch-11';
import { ch12 } from './chapters/ch-12';
import { ch13 } from './chapters/ch-13';
import { ch14 } from './chapters/ch-14';
import { ch15 } from './chapters/ch-15';
import { ch16 } from './chapters/ch-16';
import { ch17 } from './chapters/ch-17';
import { ch18 } from './chapters/ch-18';
import { ch19 } from './chapters/ch-19';
import { ch20 } from './chapters/ch-20';
import { ch21 } from './chapters/ch-21';
import { ch22 } from './chapters/ch-22';
import { ch23 } from './chapters/ch-23';
import { ch24 } from './chapters/ch-24';
import { ch25 } from './chapters/ch-25';
import { ch26 } from './chapters/ch-26';
import { ch27 } from './chapters/ch-27';
import { ch28 } from './chapters/ch-28';
import { ch29 } from './chapters/ch-29';
import { ch30 } from './chapters/ch-30';
import { ch31 } from './chapters/ch-31';
import { ch32 } from './chapters/ch-32';
import { ch33 } from './chapters/ch-33';
import { ch34 } from './chapters/ch-34';
import { ch35 } from './chapters/ch-35';
import { ch36 } from './chapters/ch-36';
import { ch37 } from './chapters/ch-37';
import { ch38 } from './chapters/ch-38';
import { ch39 } from './chapters/ch-39';
import { ch40 } from './chapters/ch-40';
import { ch41 } from './chapters/ch-41';
import { ch42 } from './chapters/ch-42';
import { ch43 } from './chapters/ch-43';
import { ch44 } from './chapters/ch-44';
import { ch45 } from './chapters/ch-45';
import { ch46 } from './chapters/ch-46';

export const CHAPTERS: Chapter[] = [ch01, ch02, ch03, ch04, ch05, ch06, ch07, ch08, ch09, ch10, ch11, ch12, ch13, ch14, ch15, ch16, ch17, ch18, ch19, ch20, ch21, ch22, ch23, ch24, ch25, ch26, ch27, ch28, ch29, ch30, ch31, ch32, ch33, ch34, ch35, ch36, ch37, ch38, ch39, ch40, ch41, ch42, ch43, ch44, ch45, ch46];

const byId = new Map(CHAPTERS.map(c => [c.id, c]));

export function getChapter(id: string): Chapter | undefined {
  return byId.get(id);
}

export function getAllCards() {
  return CHAPTERS.flatMap(ch => ch.cards.map(card => ({ chapterId: ch.id, card })));
}
