// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Part } from './types';

export const PARTS: Part[] = [
  {
    "id": "part-01",
    "number": 1,
    "label": "Part 1 — Preparatory",
    "chapterIds": [
      "ch-01",
      "ch-02",
      "ch-03",
      "ch-04",
      "ch-05",
      "ch-06"
    ]
  },
  {
    "id": "part-02",
    "number": 2,
    "label": "Part 2 — Anatomy & Physiology",
    "chapterIds": [
      "ch-07"
    ]
  },
  {
    "id": "part-03",
    "number": 3,
    "label": "Part 3 — Pathophysiology",
    "chapterIds": [
      "ch-08"
    ]
  },
  {
    "id": "part-04",
    "number": 4,
    "label": "Part 4 — Life Span Development",
    "chapterIds": [
      "ch-09"
    ]
  },
  {
    "id": "part-05",
    "number": 5,
    "label": "Part 5 — Airway Management",
    "chapterIds": [
      "ch-10"
    ]
  },
  {
    "id": "part-06",
    "number": 6,
    "label": "Part 6 — Assessment",
    "chapterIds": [
      "ch-11",
      "ch-12",
      "ch-13"
    ]
  },
  {
    "id": "part-07",
    "number": 7,
    "label": "Part 7 — Pharmacology",
    "chapterIds": [
      "ch-14"
    ]
  },
  {
    "id": "part-08",
    "number": 8,
    "label": "Part 8 — Shock & Resuscitation",
    "chapterIds": [
      "ch-15"
    ]
  },
  {
    "id": "part-09",
    "number": 9,
    "label": "Part 9 — Medicine",
    "chapterIds": [
      "ch-16",
      "ch-17",
      "ch-18",
      "ch-19",
      "ch-20",
      "ch-21",
      "ch-22",
      "ch-23",
      "ch-24",
      "ch-25",
      "ch-26"
    ]
  },
  {
    "id": "part-10",
    "number": 10,
    "label": "Part 10 — Trauma",
    "chapterIds": [
      "ch-27",
      "ch-28",
      "ch-29",
      "ch-30",
      "ch-31",
      "ch-32",
      "ch-33",
      "ch-34",
      "ch-35",
      "ch-36"
    ]
  },
  {
    "id": "part-11",
    "number": 11,
    "label": "Part 11 — Special Populations",
    "chapterIds": [
      "ch-37",
      "ch-38",
      "ch-39",
      "ch-40",
      "ch-41"
    ]
  },
  {
    "id": "part-12",
    "number": 12,
    "label": "Part 12 — EMS Operations",
    "chapterIds": [
      "ch-42",
      "ch-43",
      "ch-44",
      "ch-45",
      "ch-46"
    ]
  }
];
