// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch03: Chapter = {
  "id": "ch-03",
  "number": 3,
  "partId": "part-01",
  "title": "Medical, Legal & Ethical Issues",
  "cards": [
    {
      "id": "ch-03.fc.01",
      "q": "What is informed consent?",
      "a": "A competent patient's agreement to treatment after being informed of risks, benefits, and alternatives."
    },
    {
      "id": "ch-03.fc.02",
      "q": "What is implied consent?",
      "a": "Legal assumption that an unconscious or incompetent patient would consent to life-saving treatment."
    },
    {
      "id": "ch-03.fc.03",
      "q": "What is a DNR?",
      "a": "Do Not Resuscitate — a legal order directing EMS not to attempt resuscitation if the patient has no pulse or is not breathing."
    },
    {
      "id": "ch-03.fc.04",
      "q": "What is abandonment in EMS?",
      "a": "Terminating care of a patient without transferring to an equally or more qualified provider."
    },
    {
      "id": "ch-03.fc.05",
      "q": "What is negligence?",
      "a": "Failure to provide the standard of care a reasonable EMT would provide, resulting in patient harm."
    },
    {
      "id": "ch-03.fc.06",
      "q": "What are the four elements of negligence?",
      "a": "Duty to act, Breach of duty, Causation, Damages."
    },
    {
      "id": "ch-03.fc.07",
      "q": "What is an advance directive?",
      "a": "A legal document stating a patient's wishes for medical care if they become unable to communicate."
    },
    {
      "id": "ch-03.fc.08",
      "q": "What is HIPAA and why does it matter to EMTs?",
      "a": "Health Insurance Portability and Accountability Act — protects patient health information from unauthorized disclosure."
    }
  ],
  "notes": [
    {
      "id": "ch-03.n.01",
      "title": "Consent in EMS",
      "body": "Competent adults must give informed consent before treatment. Children require parent/guardian consent unless life-threatening. Implied consent covers unconscious or incompetent patients in emergencies. Minors in life-threatening situations: treat first.",
      "terms": [
        "Informed consent",
        "Implied consent",
        "Competence",
        "Minor",
        "Expressed consent"
      ]
    },
    {
      "id": "ch-03.n.02",
      "title": "Negligence & Liability",
      "body": "Negligence requires: duty existed, the EMT breached that duty, the breach caused harm, and actual damages resulted. Good Samaritan laws may protect off-duty providers acting in good faith without expectation of payment.",
      "terms": [
        "Duty to act",
        "Breach",
        "Causation",
        "Damages",
        "Good Samaritan"
      ]
    },
    {
      "id": "ch-03.n.03",
      "title": "Advance Directives & Patient Refusal",
      "body": "EMTs must honor valid DNR orders and advance directives. Patients have the right to refuse treatment. Requirements: competent, fully informed, signs refusal form with witness. Document thoroughly. Encourage 911 callback if symptoms worsen.",
      "terms": [
        "DNR",
        "Advance directive",
        "Living will",
        "Right to refuse",
        "Documentation"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-03.q.01",
      "q": "An unconscious patient needs emergent airway management. Which consent applies?",
      "opts": [
        "A. Informed consent",
        "B. Expressed consent",
        "C. Implied consent",
        "D. Parental consent"
      ],
      "ans": 2,
      "exp": "Implied consent assumes an unconscious patient would want life-saving treatment if they were able to consent.",
      "easy": {
        "q": "What is implied consent?",
        "opts": [
          "A. Implied consent",
          "B. Informed consent"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Competent adults must give informed consent before treatment. Based on this presentation, an unconscious patient needs emergent airway management. Which consent applies??",
        "opts": [
          "A. Expressed consent",
          "B. Informed consent",
          "C. Implied consent",
          "D. Parental consent"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-03.q.02",
      "q": "The four elements of negligence are:",
      "opts": [
        "A. Scene, patient, treatment, outcome",
        "B. Duty, breach, causation, damages",
        "C. Consent, refusal, abandonment, liability",
        "D. Scope, standard, skill, safety"
      ],
      "ans": 1,
      "exp": "To prove negligence: duty to act existed, the duty was breached, the breach caused harm, and actual damage resulted.",
      "easy": {
        "q": "What are the four elements of negligence?",
        "opts": [
          "A. Duty, breach, causation, damages",
          "B. Scope, standard, skill, safety"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. The four elements of negligence are?",
        "opts": [
          "A. Consent, refusal, abandonment, liability",
          "B. Scene, patient, treatment, outcome",
          "C. Duty, breach, causation, damages",
          "D. Scope, standard, skill, safety"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-03.q.03",
      "q": "Abandonment occurs when:",
      "opts": [
        "A. A patient refuses transport",
        "B. An EMT leaves without transferring care to an equal or higher provider",
        "C. A DNR is honored",
        "D. Bystanders take over care"
      ],
      "ans": 1,
      "exp": "Abandonment = terminating care without ensuring transfer to an equally or more qualified provider.",
      "easy": {
        "q": "What is abandonment in EMS?",
        "opts": [
          "A. An EMT leaves without transferring care to an equal or higher provider",
          "B. A DNR is honored"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Abandonment occurs when?",
        "opts": [
          "A. A patient refuses transport",
          "B. Bystanders take over care",
          "C. An EMT leaves without transferring care to an equal or higher provider",
          "D. A DNR is honored"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-03.q.04",
      "q": "A valid DNR means the EMT should:",
      "opts": [
        "A. Begin CPR anyway until confirmed",
        "B. Transport and reassess at hospital",
        "C. Honor it and withhold resuscitation",
        "D. Contact the patient's family first"
      ],
      "ans": 2,
      "exp": "A valid, properly signed DNR is a legal document and must be honored by EMS.",
      "easy": {
        "q": "What is valid DNR means the EMT should?",
        "opts": [
          "A. Honor it and withhold resuscitation",
          "B. Begin CPR anyway until confirmed"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. A valid DNR means the EMT should?",
        "opts": [
          "A. Transport and reassess at hospital",
          "B. Contact the patient's family first",
          "C. Honor it and withhold resuscitation",
          "D. Begin CPR anyway until confirmed"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-03.q.05",
      "q": "A competent adult refuses transport. You should:",
      "opts": [
        "A. Transport anyway for safety",
        "B. Leave without documentation",
        "C. Inform of risks, have sign refusal, document thoroughly",
        "D. Call police"
      ],
      "ans": 2,
      "exp": "Competent adults have the legal right to refuse. Inform of risks, obtain signed refusal with witness, document everything.",
      "easy": {
        "q": "What is competent adult refuses transport. You should?",
        "opts": [
          "A. Inform of risks, have sign refusal, document thoroughly",
          "B. Call police"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. A competent adult refuses transport. You should?",
        "opts": [
          "A. Transport anyway for safety",
          "B. Leave without documentation",
          "C. Inform of risks, have sign refusal, document thoroughly",
          "D. Call police"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-03.q.06",
      "q": "HIPAA requires EMTs to:",
      "opts": [
        "A. Share information with all hospital staff",
        "B. Protect patient health info from unauthorized disclosure",
        "C. Document all calls publicly",
        "D. Report all histories to law enforcement"
      ],
      "ans": 1,
      "exp": "HIPAA mandates protection of patient health information. Share only with those directly involved in care or as legally required.",
      "easy": {
        "q": "What is HIPAA and why does it matter to EMTs?",
        "opts": [
          "A. Protect patient health info from unauthorized disclosure",
          "B. Document all calls publicly"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. HIPAA requires EMTs to?",
        "opts": [
          "A. Share information with all hospital staff",
          "B. Report all histories to law enforcement",
          "C. Protect patient health info from unauthorized disclosure",
          "D. Document all calls publicly"
        ],
        "ans": 2
      }
    }
  ]
};
