// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch08: Chapter = {
  "id": "ch-08",
  "number": 8,
  "partId": "part-03",
  "title": "Pathophysiology",
  "cards": [
    {
      "id": "ch-08.fc.01",
      "q": "What is homeostasis?",
      "a": "The body's ability to maintain a stable internal environment — temperature, pH, fluid balance, and electrolytes within normal ranges."
    },
    {
      "id": "ch-08.fc.02",
      "q": "What is hypoxia?",
      "a": "Insufficient oxygen delivery to body tissues — causes cellular dysfunction and death if prolonged."
    },
    {
      "id": "ch-08.fc.03",
      "q": "What is anaerobic metabolism?",
      "a": "Cellular energy production without oxygen — produces lactic acid as a byproduct, causing metabolic acidosis."
    },
    {
      "id": "ch-08.fc.04",
      "q": "What is ischemia?",
      "a": "Insufficient blood flow to tissue causing oxygen deprivation — often due to blockage of blood vessels."
    },
    {
      "id": "ch-08.fc.05",
      "q": "What is inflammation?",
      "a": "The body's protective response to injury or infection — causes redness, heat, swelling, pain, and loss of function (RHSPL)."
    },
    {
      "id": "ch-08.fc.06",
      "q": "What is the difference between hypoxia and hypercarbia?",
      "a": "Hypoxia = low O2 in tissues. Hypercarbia = excess CO2 in blood — a sign of inadequate ventilation."
    },
    {
      "id": "ch-08.fc.07",
      "q": "What is sepsis?",
      "a": "A life-threatening systemic inflammatory response to infection causing organ dysfunction and circulatory failure."
    },
    {
      "id": "ch-08.fc.08",
      "q": "What are the signs of sepsis EMTs should recognize?",
      "a": "Fever or hypothermia, tachycardia, tachypnea, altered mental status, and possible hypotension — plus a suspected infection source."
    }
  ],
  "notes": [
    {
      "id": "ch-08.n.01",
      "title": "Cellular Physiology",
      "body": "Cells require oxygen and glucose for aerobic metabolism. When O2 is inadequate, cells switch to anaerobic metabolism, producing lactic acid. Acidosis impairs enzyme function and eventually causes cell death. Brain and heart cells are most sensitive to hypoxia — begin dying within 4-6 minutes.",
      "terms": [
        "Aerobic metabolism",
        "Anaerobic metabolism",
        "Lactic acid",
        "Metabolic acidosis",
        "Hypoxia"
      ]
    },
    {
      "id": "ch-08.n.02",
      "title": "Perfusion & Shock",
      "body": "Perfusion requires adequate pump (heart), pipes (vessels), and fluid (blood). Failure of any component causes shock (hypoperfusion). The body compensates initially — tachycardia and vasoconstriction — before decompensating and entering irreversible shock.",
      "terms": [
        "Perfusion triangle",
        "Compensation",
        "Decompensation",
        "Organ failure",
        "Hypoperfusion"
      ]
    },
    {
      "id": "ch-08.n.03",
      "title": "Inflammation & Infection",
      "body": "Inflammation is a protective response: vasodilation, increased capillary permeability, white cell migration to the site. Sepsis occurs when infection triggers an out-of-control systemic inflammatory response. Signs: fever/hypothermia, tachycardia, AMS — treat as emergent.",
      "terms": [
        "Inflammation",
        "Sepsis",
        "SIRS",
        "Vasodilation",
        "WBC"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-08.q.01",
      "q": "Anaerobic metabolism produces:",
      "opts": [
        "A. Glucose",
        "B. Lactic acid",
        "C. Oxygen",
        "D. ATP only"
      ],
      "ans": 1,
      "exp": "Without oxygen, cells use anaerobic metabolism producing lactic acid, leading to metabolic acidosis and cellular dysfunction.",
      "level1": {
        "q": "What is anaerobic metabolism?",
        "opts": [
          "A. Lactic acid",
          "B. Oxygen"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-08.q.02",
      "q": "Hypoxia refers to:",
      "opts": [
        "A. Low blood pressure",
        "B. Low CO2 in blood",
        "C. Insufficient oxygen to body tissues",
        "D. Elevated blood glucose"
      ],
      "ans": 2,
      "exp": "Hypoxia = inadequate oxygen delivery to cells. It causes cellular dysfunction and death if not corrected promptly.",
      "level1": {
        "q": "What is hypoxia?",
        "opts": [
          "A. Insufficient oxygen to body tissues",
          "B. Low CO2 in blood"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-08.q.03",
      "q": "The perfusion triangle includes:",
      "opts": [
        "A. Airway, breathing, circulation",
        "B. Heart (pump), vessels (pipes), blood (fluid)",
        "C. O2, CO2, glucose",
        "D. Brain, heart, lungs"
      ],
      "ans": 1,
      "exp": "Adequate perfusion requires a working pump (heart), intact pipes (vessels), and adequate fluid (blood volume).",
      "level1": {
        "q": "What is ischemia?",
        "opts": [
          "A. Heart (pump), vessels (pipes), blood (fluid)",
          "B. O2, CO2, glucose"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-08.q.04",
      "q": "Early shock is characterized by:",
      "opts": [
        "A. Hypotension and bradycardia",
        "B. Compensatory tachycardia and vasoconstriction",
        "C. Warm, flushed skin",
        "D. Decreased respiratory rate"
      ],
      "ans": 1,
      "exp": "Early shock triggers compensatory mechanisms: tachycardia increases cardiac output, vasoconstriction maintains BP temporarily.",
      "level1": {
        "q": "What is Early shock is characterized by?",
        "opts": [
          "A. Compensatory tachycardia and vasoconstriction",
          "B. Warm, flushed skin"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-08.q.05",
      "q": "Sepsis is best described as:",
      "opts": [
        "A. A localized skin infection",
        "B. A systemic inflammatory response to infection",
        "C. Viral pneumonia",
        "D. A blood clotting disorder"
      ],
      "ans": 1,
      "exp": "Sepsis is a life-threatening systemic response to infection causing widespread inflammation and organ dysfunction.",
      "level1": {
        "q": "What is sepsis?",
        "opts": [
          "A. A systemic inflammatory response to infection",
          "B. Viral pneumonia"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-08.q.06",
      "q": "Which cells are most sensitive to hypoxia?",
      "opts": [
        "A. Muscle cells",
        "B. Skin cells",
        "C. Brain and heart cells",
        "D. Liver cells"
      ],
      "ans": 2,
      "exp": "Brain cells begin to die within 4-6 minutes without oxygen — cardiac cells are similarly sensitive. Prioritize airway and oxygenation.",
      "level1": {
        "q": "Name the option that correctly answers: Which cells are most sensitive to hypoxia?",
        "opts": [
          "A. Brain and heart cells",
          "B. Skin cells"
        ],
        "ans": 0
      }
    }
  ]
};
