// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch09: Chapter = {
  "id": "ch-09",
  "number": 9,
  "partId": "part-04",
  "title": "Life Span Development",
  "cards": [
    {
      "id": "ch-09.fc.01",
      "q": "What are the vital sign norms for a newborn?",
      "a": "Respiratory rate: 30-60/min. Heart rate: 100-160/min. Blood pressure not routinely assessed in the field."
    },
    {
      "id": "ch-09.fc.02",
      "q": "What characterizes the toddler stage (1-3 years)?",
      "a": "Rapid motor and language development, fear of strangers, separation anxiety, and magical thinking."
    },
    {
      "id": "ch-09.fc.03",
      "q": "What is the leading cause of death in school-age children?",
      "a": "Trauma — particularly motor vehicle crashes."
    },
    {
      "id": "ch-09.fc.04",
      "q": "What physiological changes occur with aging?",
      "a": "Decreased cardiac reserve, reduced lung capacity, slower reflexes, thinner skin, decreased renal function, polypharmacy risk."
    },
    {
      "id": "ch-09.fc.05",
      "q": "What is polypharmacy and why is it important in EMS?",
      "a": "Use of multiple medications by older patients — increases risk of drug interactions, adverse effects, and toxicity."
    },
    {
      "id": "ch-09.fc.06",
      "q": "How does pain assessment differ in older adults?",
      "a": "Older patients may under-report pain and may present atypically. Use standardized pain scales and observe non-verbal cues."
    },
    {
      "id": "ch-09.fc.07",
      "q": "What vital signs are normal for a school-age child (6-12 years)?",
      "a": "Respiratory rate: 15-30/min. Heart rate: 70-120/min. Blood pressure approaching adult norms."
    },
    {
      "id": "ch-09.fc.08",
      "q": "What is the 'magical thinking' of toddlers and why does it matter in EMS?",
      "a": "Young children may believe injury is punishment. Be reassuring, avoid blame language, and always involve caregivers in communication."
    }
  ],
  "notes": [
    {
      "id": "ch-09.n.01",
      "title": "Pediatric Development",
      "body": "Infants rely on caregivers for all needs. Toddlers develop autonomy with separation anxiety. School-age children understand cause and effect. Adolescents develop abstract thinking and identity. Understanding developmental stage guides communication and assessment approach — speak at the child's level.",
      "terms": [
        "Infant",
        "Toddler",
        "School-age",
        "Adolescent",
        "Separation anxiety"
      ]
    },
    {
      "id": "ch-09.n.02",
      "title": "Adult & Geriatric Physiology",
      "body": "Young adults are at peak physical capacity. Middle adults face cardiovascular and cancer risks. Older adults experience multiple system changes: reduced cardiac output, decreased lung compliance, slower metabolism, reduced renal clearance, and osteoporosis.",
      "terms": [
        "Cardiac reserve",
        "Lung compliance",
        "Polypharmacy",
        "Osteoporosis",
        "Atypical presentation"
      ]
    },
    {
      "id": "ch-09.n.03",
      "title": "Geriatric Considerations in EMS",
      "body": "Older patients may present atypically — MI without chest pain, infection without fever. Assess carefully and assume the worst. Account for medications, sensory deficits (hearing/vision), and fragile skin. Treat all older patients with dignity and speak directly to them rather than to family.",
      "terms": [
        "Atypical presentation",
        "Sensory deficit",
        "Polypharmacy",
        "Advance directive",
        "Dignity"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-09.q.01",
      "q": "Normal heart rate for a newborn is:",
      "opts": [
        "A. 60-100 bpm",
        "B. 80-120 bpm",
        "C. 100-160 bpm",
        "D. 120-200 bpm"
      ],
      "ans": 2,
      "exp": "Newborns have a resting heart rate of 100-160 bpm. Rates below 100 in a newborn are concerning and require intervention.",
      "level1": {
        "q": "What is Normal heart rate for a newborn is?",
        "opts": [
          "A. 100-160 bpm",
          "B. 60-100 bpm"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-09.q.02",
      "q": "Toddlers in EMS encounters may exhibit:",
      "opts": [
        "A. Full cooperation with strangers",
        "B. Separation anxiety and fear of strangers",
        "C. Ability to give full medical history",
        "D. Adult-level vital sign norms"
      ],
      "ans": 1,
      "exp": "Toddlers (1-3 years) develop strong attachments and commonly show separation anxiety and stranger fear — involve caregivers.",
      "level1": {
        "q": "What characterizes the toddler stage (1-3 years)?",
        "opts": [
          "A. Separation anxiety and fear of strangers",
          "B. Adult-level vital sign norms"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-09.q.03",
      "q": "The leading cause of death in school-age children is:",
      "opts": [
        "A. Cancer",
        "B. Respiratory disease",
        "C. Trauma",
        "D. Cardiac arrest"
      ],
      "ans": 2,
      "exp": "Trauma, particularly motor vehicle crashes, is the #1 killer of school-age children.",
      "level1": {
        "q": "What is the leading cause of death in school-age children?",
        "opts": [
          "A. Trauma",
          "B. Cancer"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-09.q.04",
      "q": "Polypharmacy in geriatric patients is important because:",
      "opts": [
        "A. Elderly patients rarely take medications",
        "B. Multiple medications increase drug interaction and adverse effect risks",
        "C. It simplifies medical history",
        "D. It reduces EMS drug administration risk"
      ],
      "ans": 1,
      "exp": "Older patients often take 5+ medications. Drug interactions, side effects, and overdose are common EMS complications.",
      "level1": {
        "q": "What is polypharmacy and why is it important in EMS?",
        "opts": [
          "A. Multiple medications increase drug interaction and adverse effect risks",
          "B. It simplifies medical history"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-09.q.05",
      "q": "Older adults may present atypically, meaning:",
      "opts": [
        "A. They always have exaggerated symptoms",
        "B. They may have serious illness without classic signs (e.g., MI without chest pain)",
        "C. Their vitals are always abnormal",
        "D. They always require ALS"
      ],
      "ans": 1,
      "exp": "Geriatric patients often lack classic symptoms — MI may present as fatigue, infection without fever. Always maintain high index of suspicion.",
      "level1": {
        "q": "How does pain assessment differ in older adults?",
        "opts": [
          "A. They may have serious illness without classic signs (e.g., MI without chest pain)",
          "B. They always require ALS"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-09.q.06",
      "q": "Vital signs approach adult norms during:",
      "opts": [
        "A. School age (6-12)",
        "B. Toddler stage",
        "C. Adolescence (12-18)",
        "D. Young adulthood only"
      ],
      "ans": 2,
      "exp": "Pediatric vital signs gradually normalize toward adult values through adolescence as the cardiovascular system matures.",
      "level1": {
        "q": "What is Vital signs approach adult norms during?",
        "opts": [
          "A. Adolescence (12-18)",
          "B. Toddler stage"
        ],
        "ans": 0
      }
    }
  ]
};
