// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch04: Chapter = {
  "id": "ch-04",
  "number": 4,
  "partId": "part-01",
  "title": "Documentation",
  "cards": [
    {
      "id": "ch-04.fc.01",
      "q": "What is a PCR?",
      "a": "Patient Care Report — the official medical and legal record of an EMS call documenting assessment, care given, and patient response."
    },
    {
      "id": "ch-04.fc.02",
      "q": "What are the characteristics of good documentation?",
      "a": "Accurate, legible, complete, objective, timely, and unaltered."
    },
    {
      "id": "ch-04.fc.03",
      "q": "What should you never do to a PCR?",
      "a": "Never alter, falsify, or destroy a PCR — it is a legal document. Correct errors with a single line, initials, and date."
    },
    {
      "id": "ch-04.fc.04",
      "q": "How should errors on a paper PCR be corrected?",
      "a": "Draw a single line through the error, write the correct information, initial and date — never use whiteout or scribble."
    },
    {
      "id": "ch-04.fc.05",
      "q": "What does 'objective' mean in documentation?",
      "a": "Recording what you observed and measured — not opinions or assumptions. 'Patient has a 4 cm laceration' not 'bad cut.'"
    },
    {
      "id": "ch-04.fc.06",
      "q": "What are pertinent negatives?",
      "a": "Relevant symptoms the patient denies — important to document because they help rule out conditions."
    },
    {
      "id": "ch-04.fc.07",
      "q": "Why is documentation important in EMS?",
      "a": "Medical continuity of care, legal protection, billing, quality improvement review, and research."
    },
    {
      "id": "ch-04.fc.08",
      "q": "When should the PCR be completed?",
      "a": "As soon as possible after the call while details are fresh and accurate."
    }
  ],
  "notes": [
    {
      "id": "ch-04.n.01",
      "title": "The Patient Care Report (PCR)",
      "body": "The PCR is both a medical record and a legal document. It follows the patient to the hospital and becomes part of the permanent medical record. Incomplete or inaccurate documentation can harm patient care and expose the EMT to liability.",
      "terms": [
        "PCR",
        "Legal document",
        "Continuity of care",
        "Billing",
        "Liability"
      ]
    },
    {
      "id": "ch-04.n.02",
      "title": "Documentation Standards",
      "body": "Use objective, factual language. Record times accurately. Document pertinent positives AND negatives. Never leave blanks — use N/A if not applicable. Write legibly. Complete the PCR as soon as possible after the call while details are fresh.",
      "terms": [
        "Objective",
        "Pertinent negatives",
        "Subjective",
        "Timely documentation",
        "Legible"
      ]
    },
    {
      "id": "ch-04.n.03",
      "title": "Error Correction & Falsification",
      "body": "Errors are corrected with a single line, initials, and date — never whiteout or scribble. Electronic PCRs have audit trails. Falsifying a PCR is fraud and can result in criminal charges, loss of certification, and civil liability.",
      "terms": [
        "Error correction",
        "Falsification",
        "Fraud",
        "Audit trail",
        "Single line"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-04.q.01",
      "q": "A PCR is best described as:",
      "opts": [
        "A. An internal EMS quality review",
        "B. A medical and legal record of patient care",
        "C. A billing form only",
        "D. A hospital intake form"
      ],
      "ans": 1,
      "exp": "The PCR is both a medical record and a legal document used for continuity of care, billing, QI, and legal protection."
    },
    {
      "id": "ch-04.q.02",
      "q": "How should an error on a paper PCR be corrected?",
      "opts": [
        "A. Use whiteout to cover it",
        "B. Scribble over the mistake",
        "C. Draw a single line, write correction, initial and date",
        "D. Complete a new PCR"
      ],
      "ans": 2,
      "exp": "A single line preserves the original entry. Whiteout suggests falsification and is never acceptable on legal documents."
    },
    {
      "id": "ch-04.q.03",
      "q": "Pertinent negatives in documentation means:",
      "opts": [
        "A. Things that went wrong on the call",
        "B. Symptoms the patient denies that are relevant to the chief complaint",
        "C. Negative patient attitude",
        "D. Abnormal findings only"
      ],
      "ans": 1,
      "exp": "Pertinent negatives document relevant symptoms the patient does NOT have — helpful in ruling out diagnoses."
    },
    {
      "id": "ch-04.q.04",
      "q": "Falsifying a PCR can result in:",
      "opts": [
        "A. Only a written warning",
        "B. Criminal charges and loss of certification",
        "C. Mandatory retraining only",
        "D. No consequences if patient survived"
      ],
      "ans": 1,
      "exp": "PCR falsification is fraud — a crime that can result in criminal prosecution, civil liability, and permanent loss of EMS certification."
    },
    {
      "id": "ch-04.q.05",
      "q": "Objective documentation means:",
      "opts": [
        "A. Recording your impressions of the patient",
        "B. Recording what you observe and measure factually",
        "C. Describing how the patient feels",
        "D. Including your diagnosis"
      ],
      "ans": 1,
      "exp": "Objective documentation records facts: measurements, observations, and patient statements — not EMT opinions or diagnoses."
    },
    {
      "id": "ch-04.q.06",
      "q": "The PCR should be completed:",
      "opts": [
        "A. Within 24 hours",
        "B. At the beginning of your next shift",
        "C. As soon as possible after the call",
        "D. Only if the patient goes to the hospital"
      ],
      "ans": 2,
      "exp": "Complete the PCR as soon as possible after the call while details are accurate and fresh in memory."
    }
  ]
};
