// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch07: Chapter = {
  "id": "ch-07",
  "number": 7,
  "partId": "part-02",
  "title": "Anatomy, Physiology & Medical Terminology",
  "cards": [
    {
      "id": "ch-07.fc.01",
      "q": "What are the four main body cavities?",
      "a": "Cranial (brain), thoracic (heart/lungs), abdominal (digestive organs), pelvic (reproductive/urinary organs)."
    },
    {
      "id": "ch-07.fc.02",
      "q": "What does the term 'proximal' mean?",
      "a": "Closer to the point of attachment or origin — opposite of distal (farther away from the point of origin)."
    },
    {
      "id": "ch-07.fc.03",
      "q": "What are the anatomical planes of the body?",
      "a": "Sagittal (left/right), Coronal/Frontal (front/back), Transverse/Horizontal (upper/lower)."
    },
    {
      "id": "ch-07.fc.04",
      "q": "What is anatomical position?",
      "a": "Standing upright, facing forward, arms at sides, palms facing forward — the reference position for all anatomical terminology."
    },
    {
      "id": "ch-07.fc.05",
      "q": "What does 'medial' mean?",
      "a": "Toward the midline of the body — opposite of lateral (away from the midline)."
    },
    {
      "id": "ch-07.fc.06",
      "q": "What is the difference between anterior and posterior?",
      "a": "Anterior = front of the body. Posterior = back of the body."
    },
    {
      "id": "ch-07.fc.07",
      "q": "What does 'superior' and 'inferior' mean?",
      "a": "Superior = above or toward the head. Inferior = below or toward the feet."
    },
    {
      "id": "ch-07.fc.08",
      "q": "What are the abdominal quadrants?",
      "a": "Right Upper Quadrant (RUQ), Left Upper Quadrant (LUQ), Right Lower Quadrant (RLQ), Left Lower Quadrant (LLQ)."
    }
  ],
  "notes": [
    {
      "id": "ch-07.n.01",
      "title": "Directional Terms",
      "body": "All anatomical terms are based on the body in anatomical position. Superior/inferior describe up/down. Anterior/posterior describe front/back. Medial/lateral describe midline distance. Proximal/distal describe distance from origin. Prone = face down, supine = face up.",
      "terms": [
        "Superior",
        "Inferior",
        "Anterior",
        "Posterior",
        "Medial",
        "Lateral",
        "Proximal",
        "Distal"
      ]
    },
    {
      "id": "ch-07.n.02",
      "title": "Body Cavities & Regions",
      "body": "The cranial cavity contains the brain. The thoracic cavity contains heart, lungs, and great vessels. The abdominal cavity contains digestive organs, liver, and spleen. The pelvic cavity contains the bladder and reproductive organs. The abdominal quadrant system helps localize pain and injury.",
      "terms": [
        "Cranial",
        "Thoracic",
        "Abdominal",
        "Pelvic",
        "Quadrant"
      ]
    },
    {
      "id": "ch-07.n.03",
      "title": "Medical Terminology Basics",
      "body": "Medical terms use prefixes, roots, and suffixes. Root words describe the body part (cardio = heart, pulmo = lung). Prefixes modify meaning (tachy = fast, brady = slow). Suffixes describe conditions (-itis = inflammation, -emia = blood condition). Learning roots helps decode unfamiliar terms.",
      "terms": [
        "Prefix",
        "Root",
        "Suffix",
        "Tachy",
        "Brady",
        "Itis",
        "Emia"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-07.q.01",
      "q": "The term 'distal' means:",
      "opts": [
        "A. Closer to the midline",
        "B. Farther from the point of attachment",
        "C. Below another structure",
        "D. Behind another structure"
      ],
      "ans": 1,
      "exp": "Distal = farther from the point of origin or attachment. Proximal = closer to the point of origin.",
      "easy": {
        "q": "What does the term 'proximal' mean?",
        "opts": [
          "A. Farther from the point of attachment",
          "B. Closer to the midline"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. The term 'distal' means?",
        "opts": [
          "A. Behind another structure",
          "B. Below another structure",
          "C. Farther from the point of attachment",
          "D. Closer to the midline"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-07.q.02",
      "q": "Which body cavity contains the heart and lungs?",
      "opts": [
        "A. Cranial",
        "B. Abdominal",
        "C. Pelvic",
        "D. Thoracic"
      ],
      "ans": 3,
      "exp": "The thoracic cavity (chest) contains the heart, lungs, great vessels, esophagus, and trachea.",
      "easy": {
        "q": "What are the four main body cavities?",
        "opts": [
          "A. Thoracic",
          "B. Pelvic"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: The cranial cavity contains the brain. Based on this presentation, which body cavity contains the heart and lungs??",
        "opts": [
          "A. Abdominal",
          "B. Cranial",
          "C. Thoracic",
          "D. Pelvic"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-07.q.03",
      "q": "A patient lying face up is in what position?",
      "opts": [
        "A. Prone",
        "B. Lateral recumbent",
        "C. Supine",
        "D. Fowler's"
      ],
      "ans": 2,
      "exp": "Supine = lying face up (on the back). Prone = lying face down.",
      "easy": {
        "q": "What is patient lying face up is in what position??",
        "opts": [
          "A. Supine",
          "B. Prone"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Apply your field knowledge: A patient lying face up is in what position??",
        "opts": [
          "A. Lateral recumbent",
          "B. Fowler's",
          "C. Supine",
          "D. Prone"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-07.q.04",
      "q": "The RLQ of the abdomen contains:",
      "opts": [
        "A. Liver and gallbladder",
        "B. Stomach and spleen",
        "C. Appendix and part of the colon",
        "D. Kidneys and spleen"
      ],
      "ans": 2,
      "exp": "The Right Lower Quadrant contains the appendix, cecum, and part of the ascending colon — appendicitis presents here.",
      "easy": {
        "q": "What is RLQ of the abdomen contains?",
        "opts": [
          "A. Appendix and part of the colon",
          "B. Stomach and spleen"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. The RLQ of the abdomen contains?",
        "opts": [
          "A. Liver and gallbladder",
          "B. Stomach and spleen",
          "C. Appendix and part of the colon",
          "D. Kidneys and spleen"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-07.q.05",
      "q": "'Lateral' means:",
      "opts": [
        "A. Toward the midline",
        "B. Away from the midline",
        "C. Below another structure",
        "D. In front of another structure"
      ],
      "ans": 1,
      "exp": "Lateral = away from the midline. Medial = toward the midline.",
      "easy": {
        "q": "What does 'medial' mean?",
        "opts": [
          "A. Away from the midline",
          "B. Toward the midline"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. 'Lateral' means?",
        "opts": [
          "A. In front of another structure",
          "B. Below another structure",
          "C. Away from the midline",
          "D. Toward the midline"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-07.q.06",
      "q": "Anatomical position is:",
      "opts": [
        "A. Patient lying supine",
        "B. Standing, facing forward, palms facing forward",
        "C. Standing, arms crossed",
        "D. Patient sitting upright"
      ],
      "ans": 1,
      "exp": "Anatomical position: standing upright, facing forward, arms at sides with palms facing forward — the universal reference for anatomical descriptions.",
      "easy": {
        "q": "What is anatomical position?",
        "opts": [
          "A. Standing, facing forward, palms facing forward",
          "B. Patient lying supine"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: All anatomical terms are based on the body in anatomical position. Based on this presentation, anatomical position is?",
        "opts": [
          "A. Patient sitting upright",
          "B. Standing, arms crossed",
          "C. Standing, facing forward, palms facing forward",
          "D. Patient lying supine"
        ],
        "ans": 2
      }
    }
  ]
};
