// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch05: Chapter = {
  "id": "ch-05",
  "number": 5,
  "partId": "part-01",
  "title": "Communication",
  "cards": [
    {
      "id": "ch-05.fc.01",
      "q": "What are the components of an EMS radio report to the hospital?",
      "a": "Unit ID, patient age/sex, chief complaint, mental status, vitals, assessment findings, treatment given, and ETA."
    },
    {
      "id": "ch-05.fc.02",
      "q": "What is the difference between simplex and duplex radio systems?",
      "a": "Simplex: one person talks at a time (push-to-talk). Duplex: both parties can transmit simultaneously (like a phone)."
    },
    {
      "id": "ch-05.fc.03",
      "q": "What is a repeater in radio communication?",
      "a": "A device that receives a radio signal and re-transmits it at higher power to extend communication range."
    },
    {
      "id": "ch-05.fc.04",
      "q": "What is therapeutic communication?",
      "a": "Communication techniques that build trust and rapport — includes active listening, open-ended questions, and empathy."
    },
    {
      "id": "ch-05.fc.05",
      "q": "What are open-ended questions?",
      "a": "Questions that require more than yes/no answers — allows patients to describe symptoms in their own words."
    },
    {
      "id": "ch-05.fc.06",
      "q": "What are barriers to effective communication?",
      "a": "Language differences, hearing impairment, altered mental status, age, cultural differences, and environmental noise."
    },
    {
      "id": "ch-05.fc.07",
      "q": "What is FCC and why is it relevant to EMS?",
      "a": "Federal Communications Commission — regulates radio frequencies used by EMS agencies."
    },
    {
      "id": "ch-05.fc.08",
      "q": "Why are radio transmissions in EMS legally significant?",
      "a": "All EMS radio transmissions are recorded and may be used as legal evidence — speak professionally and avoid PHI on open channels."
    }
  ],
  "notes": [
    {
      "id": "ch-05.n.01",
      "title": "Radio Communication",
      "body": "EMS uses radio systems to communicate with dispatch and hospitals. Simplex requires one party to release before the other speaks. Repeaters extend radio range. All transmissions are recorded legal records — speak professionally and avoid patient identifiers on open channels.",
      "terms": [
        "Simplex",
        "Duplex",
        "Repeater",
        "FCC",
        "Base station"
      ]
    },
    {
      "id": "ch-05.n.02",
      "title": "Verbal Patient Report",
      "body": "When transferring care, give a concise verbal report: unit ID, patient info, chief complaint, vitals, assessment, treatment, and ETA. Use objective medical terminology. The hospital radio report alerts the ED to prepare resources before patient arrival.",
      "terms": [
        "Radio report",
        "ETA",
        "Handoff",
        "SBAR",
        "Transfer of care"
      ]
    },
    {
      "id": "ch-05.n.03",
      "title": "Therapeutic Communication",
      "body": "Build trust with calm, empathetic communication. Use open-ended questions to gather history. Maintain appropriate eye contact and body language. Be culturally sensitive. With pediatric patients, speak to both child and caregiver. With elderly patients, speak directly to the patient.",
      "terms": [
        "Therapeutic communication",
        "Open-ended questions",
        "Active listening",
        "Empathy",
        "Cultural competence"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-05.q.01",
      "q": "On a simplex radio system, you must:",
      "opts": [
        "A. Speak continuously",
        "B. Wait for the other party to finish before transmitting",
        "C. Use a repeater each time",
        "D. Always use a base station"
      ],
      "ans": 1,
      "exp": "Simplex systems are one-direction-at-a-time. You must release the transmit button and wait for the other party to finish."
    },
    {
      "id": "ch-05.q.02",
      "q": "Open-ended questions in patient communication are used to:",
      "opts": [
        "A. Get yes/no answers quickly",
        "B. Allow patients to describe symptoms in their own words",
        "C. Confirm existing information",
        "D. Speed up the assessment"
      ],
      "ans": 1,
      "exp": "Open-ended questions (How does your chest feel? What happened?) encourage patients to provide detailed information."
    },
    {
      "id": "ch-05.q.03",
      "q": "The hospital radio report should include all EXCEPT:",
      "opts": [
        "A. Patient age and chief complaint",
        "B. Vital signs and treatment given",
        "C. Patient's full Social Security number",
        "D. Estimated time of arrival"
      ],
      "ans": 2,
      "exp": "Patient identifiers like SSN are protected health information and must not be transmitted over radio. Use unit/age/chief complaint."
    },
    {
      "id": "ch-05.q.04",
      "q": "A repeater in radio communication:",
      "opts": [
        "A. Records all radio transmissions",
        "B. Extends radio range by re-transmitting signals",
        "C. Blocks unauthorized transmissions",
        "D. Converts analog to digital"
      ],
      "ans": 1,
      "exp": "Repeaters receive weak signals and re-broadcast them at higher power, extending effective communication range."
    },
    {
      "id": "ch-05.q.05",
      "q": "Therapeutic communication in EMS means:",
      "opts": [
        "A. Using medical jargon to sound professional",
        "B. Building trust through empathy, listening, and appropriate questioning",
        "C. Rapid closed questioning only",
        "D. Avoiding eye contact"
      ],
      "ans": 1,
      "exp": "Therapeutic communication builds patient trust and rapport, improving history gathering and cooperation with care."
    },
    {
      "id": "ch-05.q.06",
      "q": "Radio transmissions in EMS are:",
      "opts": [
        "A. Completely private and confidential",
        "B. Legal records that may be reviewed in court",
        "C. Not admissible as evidence",
        "D. Deleted after 24 hours"
      ],
      "ans": 1,
      "exp": "All EMS radio transmissions are recorded and may be used as legal evidence. Always speak professionally and avoid PHI."
    }
  ]
};
