// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch06: Chapter = {
  "id": "ch-06",
  "number": 6,
  "partId": "part-01",
  "title": "Lifting & Moving Patients",
  "cards": [
    {
      "id": "ch-06.fc.01",
      "q": "What is the power lift technique?",
      "a": "Feet shoulder-width apart, back straight, weight on balls of feet, lift with legs — never bend at the waist."
    },
    {
      "id": "ch-06.fc.02",
      "q": "When is an emergency move used?",
      "a": "When there is immediate danger to patient or rescuer: fire, explosion risk, hazardous materials, or when life-saving care cannot be given in current position."
    },
    {
      "id": "ch-06.fc.03",
      "q": "What is the difference between urgent and non-urgent moves?",
      "a": "Urgent: patient needs rapid care (altered LOC, shock) — move quickly with minimal spinal precautions. Non-urgent: patient is stable — move carefully with full precautions."
    },
    {
      "id": "ch-06.fc.04",
      "q": "What is a log roll used for?",
      "a": "To turn a patient suspected of spinal injury while maintaining spinal alignment — requires minimum 3 rescuers."
    },
    {
      "id": "ch-06.fc.05",
      "q": "What is the recovery position?",
      "a": "Unconscious breathing patient placed on their side to maintain airway and allow drainage — reduces aspiration risk."
    },
    {
      "id": "ch-06.fc.06",
      "q": "What is a scoop (orthopedic) stretcher used for?",
      "a": "To move patients with suspected spinal injuries by splitting and fitting around the patient without excessive movement."
    },
    {
      "id": "ch-06.fc.07",
      "q": "What is the power grip?",
      "a": "All fingers and palm in full contact with the object being carried — maximizes lifting strength and control."
    },
    {
      "id": "ch-06.fc.08",
      "q": "How many rescuers are recommended for a log roll?",
      "a": "Minimum 3 — one at the head maintaining spinal alignment, one at the torso, one at the legs."
    }
  ],
  "notes": [
    {
      "id": "ch-06.n.01",
      "title": "Principles of Safe Lifting",
      "body": "Back injuries are the #1 EMS occupational injury. Power lift: feet flat, back straight, palms up. Power grip: all fingers and palms in contact with surface. Never twist. Keep load below waist and close to body. Always ask for help with heavy patients — no lift is worth a career-ending back injury.",
      "terms": [
        "Power lift",
        "Power grip",
        "Body mechanics",
        "Ergonomics",
        "Communicate"
      ]
    },
    {
      "id": "ch-06.n.02",
      "title": "Emergency vs. Non-Emergency Moves",
      "body": "Emergency moves are used only when danger is immediate or care cannot be given in place. They may compromise spinal precautions. Urgent moves balance speed with spinal care. Non-urgent moves use proper technique with full spinal precautions maintained throughout.",
      "terms": [
        "Emergency move",
        "Urgent move",
        "Non-urgent move",
        "Spinal precautions",
        "Immediate danger"
      ]
    },
    {
      "id": "ch-06.n.03",
      "title": "Patient Transfer Equipment",
      "body": "Wheeled stretcher is standard for ambulance transport. Stair chair for stairs and confined spaces. Scoop stretcher for suspected spinal patients. Long backboard for spinal immobilization. Always lock wheels, use all safety straps, and confirm patient is secure before moving.",
      "terms": [
        "Wheeled stretcher",
        "Stair chair",
        "Scoop stretcher",
        "Long backboard",
        "Safety straps"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-06.q.01",
      "q": "An emergency move is indicated when:",
      "opts": [
        "A. The patient requests it",
        "B. There is immediate life threat to patient or rescuer",
        "C. The patient is heavy",
        "D. The ambulance is parked far away"
      ],
      "ans": 1,
      "exp": "Emergency moves sacrifice spinal precautions only when there is immediate danger (fire, hazmat) or when lifesaving care cannot be given in place."
    },
    {
      "id": "ch-06.q.02",
      "q": "The power lift technique requires the EMT to:",
      "opts": [
        "A. Bend at the waist with straight legs",
        "B. Keep back straight, bend at knees, lift with legs",
        "C. Twist to the side when lifting",
        "D. Hold breath during the lift"
      ],
      "ans": 1,
      "exp": "Power lift: back straight, feet shoulder-width, palms up, lift with legs — never bend at the waist or twist."
    },
    {
      "id": "ch-06.q.03",
      "q": "A log roll requires a minimum of how many rescuers?",
      "opts": [
        "A. 1",
        "B. 2",
        "C. 3",
        "D. 4"
      ],
      "ans": 2,
      "exp": "A safe log roll requires at least 3 rescuers — one at the head maintaining spinal alignment, one at the torso, one at the legs."
    },
    {
      "id": "ch-06.q.04",
      "q": "The recovery position is used for patients who are:",
      "opts": [
        "A. In cardiac arrest",
        "B. Unconscious but breathing with no suspected spinal injury",
        "C. In respiratory distress",
        "D. Conscious and alert"
      ],
      "ans": 1,
      "exp": "Recovery position (lateral recumbent) maintains airway patency and allows drainage in unconscious breathing patients."
    },
    {
      "id": "ch-06.q.05",
      "q": "A scoop stretcher is most appropriate for:",
      "opts": [
        "A. Cardiac arrest patients during CPR",
        "B. Patients with suspected spinal injuries requiring minimal movement",
        "C. Bariatric patients only",
        "D. Patients on upper floors"
      ],
      "ans": 1,
      "exp": "The scoop stretcher splits apart to fit around the patient, minimizing movement for suspected spinal injury patients."
    },
    {
      "id": "ch-06.q.06",
      "q": "The primary reason EMTs get back injuries is:",
      "opts": [
        "A. Motor vehicle accidents",
        "B. Patient assaults",
        "C. Improper lifting technique",
        "D. Slip and fall on scene"
      ],
      "ans": 2,
      "exp": "Improper lifting — bending at the waist, twisting, or lifting beyond capacity — causes the majority of EMS back injuries."
    }
  ]
};
