// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch02: Chapter = {
  "id": "ch-02",
  "number": 2,
  "partId": "part-01",
  "title": "Workforce Safety & Wellness",
  "cards": [
    {
      "id": "ch-02.fc.01",
      "q": "What is BSI (Body Substance Isolation)?",
      "a": "An infection control approach treating all body fluids as potentially infectious — requires gloves, eye protection, and appropriate PPE."
    },
    {
      "id": "ch-02.fc.02",
      "q": "What PPE is required for potential airborne exposure?",
      "a": "N95 respirator (or higher), eye protection, and gown in addition to standard gloves."
    },
    {
      "id": "ch-02.fc.03",
      "q": "What is the correct order for donning PPE?",
      "a": "Gown → Mask/Respirator → Goggles/Face Shield → Gloves."
    },
    {
      "id": "ch-02.fc.04",
      "q": "What is CISM?",
      "a": "Critical Incident Stress Management — a structured support system to help EMS personnel process traumatic events."
    },
    {
      "id": "ch-02.fc.05",
      "q": "What are warning signs of cumulative stress in EMS?",
      "a": "Irritability, insomnia, substance use, social withdrawal, decreased job performance, and compassion fatigue."
    },
    {
      "id": "ch-02.fc.06",
      "q": "What is the safe lifting technique for EMTs?",
      "a": "Keep back straight, bend at knees and hips, keep load close to body, lift with legs, avoid twisting."
    },
    {
      "id": "ch-02.fc.07",
      "q": "What are common routes of disease transmission in EMS?",
      "a": "Direct contact, indirect contact, airborne (droplet/aerosol), and bloodborne (needle stick, mucous membrane splash)."
    },
    {
      "id": "ch-02.fc.08",
      "q": "What is an exposure control plan?",
      "a": "A written employer plan outlining procedures to minimize employee exposure to bloodborne pathogens."
    }
  ],
  "notes": [
    {
      "id": "ch-02.n.01",
      "title": "Infection Control",
      "body": "BSI precautions treat all blood and body fluids as infectious. Gloves are minimum standard for every patient. Add mask, goggles, and gown based on anticipated exposure. Perform hand hygiene before and after every patient contact.",
      "terms": [
        "BSI",
        "PPE",
        "N95",
        "Hand hygiene",
        "Airborne precautions"
      ]
    },
    {
      "id": "ch-02.n.02",
      "title": "EMT Wellness & Stress Management",
      "body": "EMS providers face unique physical and psychological stressors. CISM helps process acute critical incidents. Cumulative stress builds over time and can cause burnout, compassion fatigue, and substance abuse. Peer support and professional help are essential.",
      "terms": [
        "CISM",
        "Compassion fatigue",
        "Burnout",
        "Critical incident",
        "Peer support"
      ]
    },
    {
      "id": "ch-02.n.03",
      "title": "Safe Lifting & Body Mechanics",
      "body": "Back injuries are the most common EMS occupational injury. Use power lift: back straight, knees bent, feet shoulder-width apart. Keep weight close to body. Always communicate with your partner and request help for heavy patients.",
      "terms": [
        "Power lift",
        "Power grip",
        "Body mechanics",
        "Ergonomics"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-02.q.01",
      "q": "Minimum PPE for all patient contacts is:",
      "opts": [
        "A. N95 mask",
        "B. Gloves",
        "C. Gown and goggles",
        "D. Full face shield"
      ],
      "ans": 1,
      "exp": "Gloves are minimum PPE for every patient contact. Additional PPE is added based on exposure risk.",
      "level1": {
        "q": "What is Minimum PPE for all patient contacts is?",
        "opts": [
          "A. Gloves",
          "B. N95 mask"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-02.q.02",
      "q": "When doffing PPE, what is removed first?",
      "opts": [
        "A. Mask",
        "B. Gown",
        "C. Gloves",
        "D. Goggles"
      ],
      "ans": 2,
      "exp": "Gloves are removed first because they are the most contaminated. Remove from outside-in to avoid self-contamination.",
      "level1": {
        "q": "What is BSI (Body Substance Isolation)?",
        "opts": [
          "A. Gloves",
          "B. Mask"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-02.q.03",
      "q": "CISM is designed to:",
      "opts": [
        "A. Investigate EMS errors",
        "B. Help EMS personnel process critical incident stress",
        "C. Train EMTs in decontamination",
        "D. Review PCR documentation"
      ],
      "ans": 1,
      "exp": "Critical Incident Stress Management provides structured peer and professional support after traumatic calls.",
      "level1": {
        "q": "What is CISM?",
        "opts": [
          "A. Help EMS personnel process critical incident stress",
          "B. Investigate EMS errors"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-02.q.04",
      "q": "Most common occupational injury in EMS:",
      "opts": [
        "A. Needle sticks",
        "B. Vehicle crashes",
        "C. Back injuries",
        "D. Airborne disease exposure"
      ],
      "ans": 2,
      "exp": "Back injuries from improper lifting are the most frequent EMS occupational injuries — proper body mechanics are essential.",
      "level1": {
        "q": "What is Most common occupational injury in EMS?",
        "opts": [
          "A. Back injuries",
          "B. Needle sticks"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-02.q.05",
      "q": "N95 respirators are required for:",
      "opts": [
        "A. Bloodborne pathogen exposure",
        "B. Airborne diseases like TB and measles",
        "C. Contact precaution patients",
        "D. All patient contacts"
      ],
      "ans": 1,
      "exp": "N95 respirators filter airborne particles and are required for suspected airborne diseases like tuberculosis and measles.",
      "level1": {
        "q": "What is N95 respirators are required for?",
        "opts": [
          "A. Airborne diseases like TB and measles",
          "B. All patient contacts"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-02.q.06",
      "q": "Signs of compassion fatigue include:",
      "opts": [
        "A. Increased empathy and motivation",
        "B. Emotional numbness, withdrawal, decreased performance",
        "C. Improved patient care quality",
        "D. Increased team cohesion"
      ],
      "ans": 1,
      "exp": "Compassion fatigue manifests as emotional detachment, reduced empathy, social withdrawal, and declining job performance.",
      "level1": {
        "q": "What are warning signs of cumulative stress in EMS?",
        "opts": [
          "A. Emotional numbness, withdrawal, decreased performance",
          "B. Increased team cohesion"
        ],
        "ans": 0
      }
    }
  ]
};
