// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch01: Chapter = {
  "id": "ch-01",
  "number": 1,
  "partId": "part-01",
  "title": "EMS Systems, Research & Public Health",
  "cards": [
    {
      "id": "ch-01.fc.01",
      "q": "What are the four nationally recognized EMT certification levels?",
      "a": "Emergency Medical Responder (EMR), EMT, Advanced EMT (AEMT), and Paramedic."
    },
    {
      "id": "ch-01.fc.02",
      "q": "What is the EMS medical director's role?",
      "a": "A physician providing medical oversight who approves protocols and under whose license EMTs legally practice."
    },
    {
      "id": "ch-01.fc.03",
      "q": "What is the difference between online and offline medical direction?",
      "a": "Online: real-time physician contact by radio or phone. Offline: pre-written protocols and standing orders."
    },
    {
      "id": "ch-01.fc.04",
      "q": "What is the 'Golden Hour' concept?",
      "a": "Critically injured trauma patients have the best survival chance if they reach definitive care within one hour of injury."
    },
    {
      "id": "ch-01.fc.05",
      "q": "What does 'standard of care' mean in EMS?",
      "a": "The care a reasonable, prudent EMT with similar training would provide in the same situation."
    },
    {
      "id": "ch-01.fc.06",
      "q": "What is a standing order?",
      "a": "A written protocol authorizing specific EMT interventions without real-time physician contact."
    },
    {
      "id": "ch-01.fc.07",
      "q": "What is quality improvement (QI) in EMS?",
      "a": "A continuous review system evaluating patient care, documentation, and system performance to improve outcomes."
    },
    {
      "id": "ch-01.fc.08",
      "q": "What is the purpose of EMS research?",
      "a": "To evaluate treatment effectiveness and improve evidence-based prehospital care practices."
    }
  ],
  "notes": [
    {
      "id": "ch-01.n.01",
      "title": "EMS System Structure",
      "body": "EMS is a coordinated system including public access (9-1-1), dispatch, first responders, EMTs, AEMTs, paramedics, and hospital care. Each level links to form the chain of survival.",
      "terms": [
        "Chain of survival",
        "Medical director",
        "Standing orders",
        "Quality improvement"
      ]
    },
    {
      "id": "ch-01.n.02",
      "title": "Levels of EMS Training",
      "body": "EMR: immediate life-saving care. EMT: basic life support. AEMT: limited advanced skills. Paramedic: full ALS including drugs and advanced airways. Each level has a defined scope of practice regulated by the state.",
      "terms": [
        "EMR",
        "EMT",
        "AEMT",
        "Paramedic",
        "Scope of practice"
      ]
    },
    {
      "id": "ch-01.n.03",
      "title": "Medical Direction & Accountability",
      "body": "All EMS systems require a physician medical director. Online direction = real-time communication. Offline = pre-approved protocols. QI programs review care retrospectively to improve future performance.",
      "terms": [
        "Online direction",
        "Offline direction",
        "Protocol",
        "QI"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-01.q.01",
      "q": "EMTs practice under the license of:",
      "opts": [
        "A. Their certification agency",
        "B. The physician medical director",
        "C. The state EMS office",
        "D. Their employer"
      ],
      "ans": 1,
      "exp": "EMTs legally practice under the medical director's license, which authorizes their scope of practice in the field.",
      "easy": {
        "q": "What is the EMS medical director's role?",
        "opts": [
          "A. The physician medical director",
          "B. Their employer"
        ],
        "ans": 0
      },
      "hard": {
        "q": "During QA review of an EMS run, your supervisor asks: EMTs practice under the license of?",
        "opts": [
          "A. Their certification agency",
          "B. The state EMS office",
          "C. The physician medical director",
          "D. Their employer"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-01.q.02",
      "q": "A standing order is best described as:",
      "opts": [
        "A. Real-time physician communication",
        "B. A hospital treatment plan",
        "C. Pre-approved written protocols for specific interventions",
        "D. A court order"
      ],
      "ans": 2,
      "exp": "Standing orders are pre-approved protocols allowing EMTs to act without calling a physician each time.",
      "easy": {
        "q": "What is a standing order?",
        "opts": [
          "A. Pre-approved written protocols for specific interventions",
          "B. A court order"
        ],
        "ans": 0
      },
      "hard": {
        "q": "During QA review of an EMS run, your supervisor asks: a standing order is is MOST accurately defined as?",
        "opts": [
          "A. Real-time physician communication",
          "B. A hospital treatment plan",
          "C. Pre-approved written protocols for specific interventions",
          "D. A court order"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-01.q.03",
      "q": "Quality improvement in EMS is designed to:",
      "opts": [
        "A. Punish poor-performing EMTs",
        "B. Continuously review and improve patient care",
        "C. Reduce ambulance costs",
        "D. Train new dispatchers"
      ],
      "ans": 1,
      "exp": "QI programs evaluate care through case review and feedback to continuously improve patient outcomes.",
      "easy": {
        "q": "What is quality improvement (QI) in EMS?",
        "opts": [
          "A. Continuously review and improve patient care",
          "B. Train new dispatchers"
        ],
        "ans": 0
      },
      "hard": {
        "q": "During QA review of an EMS run, your supervisor asks: quality improvement in EMS is designed to?",
        "opts": [
          "A. Punish poor-performing EMTs",
          "B. Reduce ambulance costs",
          "C. Continuously review and improve patient care",
          "D. Train new dispatchers"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-01.q.04",
      "q": "The 'Golden Hour' concept applies most to:",
      "opts": [
        "A. Medical cardiac patients",
        "B. Critically injured trauma patients",
        "C. Diabetic emergencies",
        "D. Pediatric patients only"
      ],
      "ans": 1,
      "exp": "The Golden Hour states trauma patients have the best survival if definitive care is reached within 1 hour of injury.",
      "easy": {
        "q": "What is the 'Golden Hour' concept?",
        "opts": [
          "A. Critically injured trauma patients",
          "B. Diabetic emergencies"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. The 'Golden Hour' concept applies most to?",
        "opts": [
          "A. Medical cardiac patients",
          "B. Pediatric patients only",
          "C. Critically injured trauma patients",
          "D. Diabetic emergencies"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-01.q.05",
      "q": "Which EMS level performs full advanced life support?",
      "opts": [
        "A. EMR",
        "B. EMT",
        "C. AEMT",
        "D. Paramedic"
      ],
      "ans": 3,
      "exp": "Paramedics have the highest EMT certification and can perform full ALS: IV therapy, intubation, and drug administration.",
      "easy": {
        "q": "Name the option that correctly answers: Which EMS level performs full advanced life support?",
        "opts": [
          "A. Paramedic",
          "B. EMR"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: EMR: immediate life-saving care. Based on this presentation, which EMS level performs full advanced life support??",
        "opts": [
          "A. AEMT",
          "B. EMR",
          "C. Paramedic",
          "D. EMT"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-01.q.06",
      "q": "Online medical direction means:",
      "opts": [
        "A. Following pre-written protocols",
        "B. Real-time communication with a physician",
        "C. Internet-based training",
        "D. Hospital documentation"
      ],
      "ans": 1,
      "exp": "Online (direct) medical direction involves real-time radio or phone contact with a physician for orders.",
      "easy": {
        "q": "What is the difference between online and offline medical direction?",
        "opts": [
          "A. Real-time communication with a physician",
          "B. Hospital documentation"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: All EMS systems require a physician medical director. Based on this presentation, online medical direction means?",
        "opts": [
          "A. Following pre-written protocols",
          "B. Internet-based training",
          "C. Real-time communication with a physician",
          "D. Hospital documentation"
        ],
        "ans": 2
      }
    }
  ]
};
