// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch15: Chapter = {
  "id": "ch-15",
  "number": 15,
  "partId": "part-08",
  "title": "Shock and Resuscitation",
  "cards": [
    {
      "id": "ch-15.fc.01",
      "q": "What is shock (hypoperfusion)?",
      "a": "Inadequate perfusion of cells and tissues with oxygenated blood, leading to cellular death if untreated."
    },
    {
      "id": "ch-15.fc.02",
      "q": "What are the three components of the perfusion triangle?",
      "a": "Heart (pump), blood vessels (pipes), and blood volume (fluid) — failure of any one causes shock."
    },
    {
      "id": "ch-15.fc.03",
      "q": "What are early signs of shock?",
      "a": "Anxiety/restlessness, tachycardia, pale/cool/clammy skin, increased respiratory rate, normal or slightly low BP."
    },
    {
      "id": "ch-15.fc.04",
      "q": "What is the best method to control external bleeding?",
      "a": "Direct pressure — apply firm, continuous pressure with a gloved hand and dressing."
    },
    {
      "id": "ch-15.fc.05",
      "q": "When should a tourniquet be applied?",
      "a": "Life-threatening extremity bleeding that cannot be controlled with direct pressure."
    },
    {
      "id": "ch-15.fc.06",
      "q": "Where should a tourniquet be placed?",
      "a": "2-3 inches proximal to (above) the wound. Document the exact time of application."
    },
    {
      "id": "ch-15.fc.07",
      "q": "What is anaphylactic shock?",
      "a": "A severe, life-threatening allergic reaction causing massive vasodilation, airway edema, and distributive shock."
    },
    {
      "id": "ch-15.fc.08",
      "q": "How do you treat hypovolemic shock in the field?",
      "a": "Control bleeding, position supine, keep warm, high-flow O2, rapid transport — do not delay for IV access."
    }
  ],
  "notes": [
    {
      "id": "ch-15.n.01",
      "title": "Types of Shock",
      "body": "Hypovolemic: blood/fluid loss. Cardiogenic: pump failure. Distributive: vasodilation (septic, anaphylactic, neurogenic). Obstructive: tension pneumothorax or tamponade blocking flow. All result in inadequate tissue perfusion — recognize early and treat aggressively.",
      "terms": [
        "Hypovolemic",
        "Cardiogenic",
        "Distributive",
        "Obstructive",
        "Septic"
      ]
    },
    {
      "id": "ch-15.n.02",
      "title": "Hemorrhage Control",
      "body": "Direct pressure is first-line for all external bleeding. Wound packing for junctional wounds. Tourniquets for uncontrolled extremity bleeding — 2-3 inches above wound, document time. Pressure dressings maintain pressure during transport.",
      "terms": [
        "Direct pressure",
        "Tourniquet",
        "Wound packing",
        "Hemostatic dressing",
        "Junctional"
      ]
    },
    {
      "id": "ch-15.n.03",
      "title": "Shock Management",
      "body": "Maintain airway. High-flow O2. Supine position (legs elevated if no spinal concern). Prevent heat loss. Rapid transport. Do not delay transport for IV — EMTs cannot replace blood volume in the field. Every minute counts in decompensated shock.",
      "terms": [
        "Supine position",
        "Oxygen",
        "Rapid transport",
        "Warm patient",
        "Hypothermia prevention"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-15.q.01",
      "q": "Early signs of shock include:",
      "opts": [
        "A. Bradycardia and hypertension",
        "B. Tachycardia and pale, cool, clammy skin",
        "C. Flushed, hot, dry skin",
        "D. Decreased respiratory rate"
      ],
      "ans": 1,
      "exp": "Early shock triggers compensatory tachycardia and vasoconstriction causing pale, cool, clammy skin. BP may remain normal initially."
    },
    {
      "id": "ch-15.q.02",
      "q": "First-line treatment for external bleeding:",
      "opts": [
        "A. Tourniquet",
        "B. Elevation only",
        "C. Direct pressure",
        "D. Pressure point"
      ],
      "ans": 2,
      "exp": "Direct pressure is always first-line for external hemorrhage control. Tourniquets are reserved for life-threatening limb bleeding."
    },
    {
      "id": "ch-15.q.03",
      "q": "Tourniquet placement:",
      "opts": [
        "A. Directly over the wound",
        "B. 2-3 inches proximal to the wound",
        "C. Distal to the wound",
        "D. At the nearest joint"
      ],
      "ans": 1,
      "exp": "Tourniquet placement 2-3 inches proximal (above) the wound avoids joint placement and ensures effective arterial compression."
    },
    {
      "id": "ch-15.q.04",
      "q": "Anaphylactic shock is classified as:",
      "opts": [
        "A. Hypovolemic",
        "B. Cardiogenic",
        "C. Obstructive",
        "D. Distributive"
      ],
      "ans": 3,
      "exp": "Anaphylaxis causes massive vasodilation from histamine release — this is distributive shock, not hypovolemic."
    },
    {
      "id": "ch-15.q.05",
      "q": "Signs of internal abdominal bleeding:",
      "opts": [
        "A. Hypertension, bradycardia",
        "B. Rigid/distended abdomen, signs of shock",
        "C. Clear lung sounds, normal BP",
        "D. Bradypnea, fever"
      ],
      "ans": 1,
      "exp": "Internal bleeding causes abdominal rigidity/distension, referred pain, bruising patterns, and signs of hypovolemic shock."
    },
    {
      "id": "ch-15.q.06",
      "q": "Field treatment of hypovolemic shock focuses on:",
      "opts": [
        "A. Starting IV before transport",
        "B. Controlling bleeding and rapid transport",
        "C. Position of comfort",
        "D. Oral rehydration"
      ],
      "ans": 1,
      "exp": "Control the bleeding source, maintain airway/O2, keep patient warm, and transport rapidly. Do not delay for IV access."
    }
  ]
};
