// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch12: Chapter = {
  "id": "ch-12",
  "number": 12,
  "partId": "part-06",
  "title": "Scene Size-Up",
  "cards": [
    {
      "id": "ch-12.fc.01",
      "q": "What are the four components of scene size-up?",
      "a": "Scene safety, Mechanism of injury (MOI) or Nature of illness (NOI), Number of patients, Need for additional resources."
    },
    {
      "id": "ch-12.fc.02",
      "q": "What is BSI and when is it applied?",
      "a": "Body Substance Isolation — PPE must be donned before entering the scene, before any patient contact."
    },
    {
      "id": "ch-12.fc.03",
      "q": "What is mechanism of injury (MOI)?",
      "a": "The force(s) that caused a trauma injury — helps predict injury patterns (e.g., high-speed MVC suggests spinal/internal injuries)."
    },
    {
      "id": "ch-12.fc.04",
      "q": "What is nature of illness (NOI)?",
      "a": "The medical condition causing the patient's problem — determined during scene size-up by bystander information and scene clues."
    },
    {
      "id": "ch-12.fc.05",
      "q": "When should you call for additional resources?",
      "a": "As soon as the need is identified during size-up — do not wait until you are overwhelmed. It is safer to cancel resources than to need them and not have them."
    },
    {
      "id": "ch-12.fc.06",
      "q": "What environmental clues help determine NOI at a medical scene?",
      "a": "Medication bottles, medical equipment (oxygen, nebulizer), medical alert jewelry, positioning, patient's surroundings."
    },
    {
      "id": "ch-12.fc.07",
      "q": "What is index of suspicion?",
      "a": "The EMT's anticipation of injury patterns based on MOI — guides assessment and treatment even before findings are confirmed."
    },
    {
      "id": "ch-12.fc.08",
      "q": "What are scene safety hazards to identify?",
      "a": "Traffic, fire, hazardous materials, structural instability, violence/weapons, downed power lines, and environmental conditions."
    }
  ],
  "notes": [
    {
      "id": "ch-12.n.01",
      "title": "Scene Safety — Always First",
      "body": "No patient care can occur safely if the scene is unsafe. Identify hazards from a distance before approaching. Traffic, fire, hazmat, violence, unstable structures, and downed lines are common threats. Never become a victim — call for appropriate resources first.",
      "terms": [
        "Scene safety",
        "BSI/PPE",
        "Hazards",
        "Staging",
        "Additional resources"
      ]
    },
    {
      "id": "ch-12.n.02",
      "title": "MOI vs NOI",
      "body": "Trauma scenes: determine MOI to predict injuries (kinetic energy, deformity, damage patterns). Medical scenes: determine NOI from bystanders, medication bottles, medical devices, and scene findings. Both inform your index of suspicion and initial approach.",
      "terms": [
        "MOI",
        "NOI",
        "Index of suspicion",
        "Kinetic energy",
        "Scene clues"
      ]
    },
    {
      "id": "ch-12.n.03",
      "title": "Resource Identification",
      "body": "Count patients early — if more than your crew can handle, call for mutual aid immediately. Consider hazmat resources for chemical exposure, ALS for critical patients, law enforcement for violence, and fire for entrapment or fire hazard. Never delay this call.",
      "terms": [
        "Mutual aid",
        "ALS intercept",
        "Hazmat",
        "MCI",
        "Patient count"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-12.q.01",
      "q": "The first component of scene size-up is:",
      "opts": [
        "A. Counting patients",
        "B. Determining MOI",
        "C. Scene safety and BSI",
        "D. Calling for ALS"
      ],
      "ans": 2,
      "exp": "Scene safety and donning appropriate BSI/PPE are always the first steps — before approaching or touching any patient."
    },
    {
      "id": "ch-12.q.02",
      "q": "Mechanism of injury (MOI) helps the EMT:",
      "opts": [
        "A. Determine the patient's age",
        "B. Anticipate injury patterns and guide assessment",
        "C. Confirm the diagnosis",
        "D. Choose hospital destination"
      ],
      "ans": 1,
      "exp": "MOI allows the EMT to develop an index of suspicion — predicting likely injuries based on the forces involved."
    },
    {
      "id": "ch-12.q.03",
      "q": "When should additional resources be requested?",
      "opts": [
        "A. Only after assessment confirms need",
        "B. As soon as the need is identified during size-up",
        "C. Only if ALS is unavailable",
        "D. After the patient is stabilized"
      ],
      "ans": 1,
      "exp": "Request additional resources as soon as you identify the need — it is always better to cancel resources than to need them and not have them."
    },
    {
      "id": "ch-12.q.04",
      "q": "Environmental clues for medical NOI include:",
      "opts": [
        "A. Skid marks on the road",
        "B. Medication bottles, medical equipment, alert jewelry",
        "C. Vehicle deformity",
        "D. Bystander statements only"
      ],
      "ans": 1,
      "exp": "Medication bottles, nebulizers, oxygen concentrators, and medical alert bracelets provide critical clues about a patient's medical history."
    },
    {
      "id": "ch-12.q.05",
      "q": "Index of suspicion refers to:",
      "opts": [
        "A. Assuming all patients are faking",
        "B. Anticipating injuries based on MOI before confirming them",
        "C. Suspecting foul play",
        "D. Estimating scene danger"
      ],
      "ans": 1,
      "exp": "Index of suspicion is the EMT's anticipation of likely injuries or conditions based on the mechanism or scene — guiding a more thorough assessment."
    },
    {
      "id": "ch-12.q.06",
      "q": "A downed power line at a scene means:",
      "opts": [
        "A. Approach carefully with rubber gloves",
        "B. Stage at a safe distance and call the utility company",
        "C. Drive over it with the ambulance",
        "D. Touch it only with wooden equipment"
      ],
      "ans": 1,
      "exp": "Downed power lines are immediately life-threatening. Stage at a safe distance, call utilities, and do not approach until power is confirmed off."
    }
  ]
};
