// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch11: Chapter = {
  "id": "ch-11",
  "number": 11,
  "partId": "part-06",
  "title": "Vital Signs, Monitoring & History Taking",
  "cards": [
    {
      "id": "ch-11.fc.01",
      "q": "What are the normal adult vital sign ranges?",
      "a": "Respiratory rate: 12-20/min. Pulse: 60-100 bpm. BP: 90-140 systolic. Temperature: 98.6°F (37°C). SpO2: 94-100%."
    },
    {
      "id": "ch-11.fc.02",
      "q": "What does SAMPLE stand for?",
      "a": "Signs/Symptoms, Allergies, Medications, Pertinent past history, Last oral intake, Events leading to illness/injury."
    },
    {
      "id": "ch-11.fc.03",
      "q": "What does OPQRST stand for?",
      "a": "Onset, Provocation/Palliation, Quality, Radiation, Severity (1-10 scale), Time."
    },
    {
      "id": "ch-11.fc.04",
      "q": "How do you assess pulse quality?",
      "a": "Rate (beats/min), rhythm (regular or irregular), and strength (strong, weak, bounding, thready)."
    },
    {
      "id": "ch-11.fc.05",
      "q": "What are the four skin signs assessed by EMTs?",
      "a": "Color, temperature, condition (moisture), and capillary refill time (CRT)."
    },
    {
      "id": "ch-11.fc.06",
      "q": "What is a normal capillary refill time?",
      "a": "Less than 2 seconds in adults and children. Greater than 2 seconds suggests poor perfusion."
    },
    {
      "id": "ch-11.fc.07",
      "q": "What is a pulse oximeter and what does it measure?",
      "a": "A non-invasive device measuring peripheral oxygen saturation (SpO2) — the percentage of hemoglobin saturated with oxygen."
    },
    {
      "id": "ch-11.fc.08",
      "q": "What monitoring device measures end-tidal CO2?",
      "a": "Capnography (EtCO2 monitor) — measures CO2 in exhaled air, confirming tube placement and ventilation adequacy."
    }
  ],
  "notes": [
    {
      "id": "ch-11.n.01",
      "title": "Vital Sign Assessment",
      "body": "Vital signs are objective measurements of body function. Always assess: respiratory rate/quality, pulse rate/rhythm/strength, skin signs, pupils, blood pressure, and SpO2. Trends over time (trending up or down) are more meaningful than single measurements. Reassess frequently.",
      "terms": [
        "Respiratory rate",
        "Pulse",
        "Blood pressure",
        "SpO2",
        "Capillary refill"
      ]
    },
    {
      "id": "ch-11.n.02",
      "title": "History Taking — SAMPLE & OPQRST",
      "body": "SAMPLE provides comprehensive medical background. OPQRST focuses specifically on the chief complaint — especially pain and respiratory complaints. Never skip history — it often provides more diagnostic value than physical exam alone.",
      "terms": [
        "SAMPLE",
        "OPQRST",
        "Chief complaint",
        "Medical history",
        "Pertinent negatives"
      ]
    },
    {
      "id": "ch-11.n.03",
      "title": "Monitoring Devices",
      "body": "Pulse oximeter: SpO2 — may be falsely normal in CO poisoning or poor perfusion states. Blood glucose meter: essential for any AMS patient. Capnography: confirms airway placement and monitors ventilation. Cardiac monitor (ALS): identifies rhythms. Know the limitations of each device.",
      "terms": [
        "Pulse oximeter",
        "Capnography",
        "EtCO2",
        "Blood glucose meter",
        "Limitations"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-11.q.01",
      "q": "Normal adult respiratory rate is:",
      "opts": [
        "A. 6-10/min",
        "B. 12-20/min",
        "C. 20-30/min",
        "D. 30-40/min"
      ],
      "ans": 1,
      "exp": "Normal adult respiratory rate is 12-20 breaths per minute. Below 12 or above 20 warrants further assessment."
    },
    {
      "id": "ch-11.q.02",
      "q": "The 'E' in SAMPLE stands for:",
      "opts": [
        "A. Examination",
        "B. Events leading to illness",
        "C. Eating habits",
        "D. Estimated age"
      ],
      "ans": 1,
      "exp": "E = Events leading to the illness or injury. Understanding what happened just before onset helps determine the cause."
    },
    {
      "id": "ch-11.q.03",
      "q": "Normal capillary refill time is:",
      "opts": [
        "A. Less than 1 second",
        "B. Less than 2 seconds",
        "C. Less than 4 seconds",
        "D. Up to 6 seconds"
      ],
      "ans": 1,
      "exp": "CRT < 2 seconds is normal. Greater than 2 seconds suggests poor peripheral perfusion (shock, hypothermia, etc.)."
    },
    {
      "id": "ch-11.q.04",
      "q": "OPQRST is most useful for evaluating:",
      "opts": [
        "A. Medical history",
        "B. Allergies",
        "C. The chief complaint, especially pain",
        "D. Medication list"
      ],
      "ans": 2,
      "exp": "OPQRST (Onset, Provocation, Quality, Radiation, Severity, Time) specifically evaluates the chief complaint — especially pain."
    },
    {
      "id": "ch-11.q.05",
      "q": "Pulse oximetry may be falsely normal in:",
      "opts": [
        "A. Respiratory distress",
        "B. Carbon monoxide poisoning",
        "C. Hypovolemic shock",
        "D. Anemia only"
      ],
      "ans": 1,
      "exp": "Standard pulse oximetry cannot distinguish oxyhemoglobin from carboxyhemoglobin — CO poisoning can show a normal SpO2."
    },
    {
      "id": "ch-11.q.06",
      "q": "Skin signs that suggest shock include:",
      "opts": [
        "A. Pink, warm, dry skin",
        "B. Flushed, hot, moist skin",
        "C. Pale, cool, clammy skin",
        "D. Normal color with diaphoresis only"
      ],
      "ans": 2,
      "exp": "Pale, cool, clammy skin results from compensatory vasoconstriction in early shock — blood is shunted to vital organs."
    }
  ]
};
