// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch16: Chapter = {
  "id": "ch-16",
  "number": 16,
  "partId": "part-09",
  "title": "Respiratory Emergencies",
  "cards": [
    {
      "id": "ch-16.fc.01",
      "q": "What are signs of respiratory distress?",
      "a": "Increased respiratory rate, accessory muscle use, nasal flaring, tripod position, cyanosis, inability to speak in full sentences."
    },
    {
      "id": "ch-16.fc.02",
      "q": "What is the difference between COPD emphysema and chronic bronchitis?",
      "a": "Emphysema: destruction of alveolar walls, air trapping, barrel chest. Chronic bronchitis: excessive mucus production, productive cough >3 months/year for 2+ years."
    },
    {
      "id": "ch-16.fc.03",
      "q": "What is asthma?",
      "a": "A reversible obstructive disease causing bronchoconstriction, mucus production, and airway edema triggered by allergens or irritants."
    },
    {
      "id": "ch-16.fc.04",
      "q": "How do you assist with a metered-dose inhaler (MDI)?",
      "a": "Confirm patient's prescription, shake the inhaler, patient exhales fully, actuate at start of slow inhalation, hold breath 10 seconds."
    },
    {
      "id": "ch-16.fc.05",
      "q": "What is the difference between wheezing and stridor?",
      "a": "Wheezing (lower airway): musical expiratory sound from bronchoconstriction. Stridor (upper airway): high-pitched inspiratory sound indicating upper airway obstruction."
    },
    {
      "id": "ch-16.fc.06",
      "q": "What is pulmonary edema?",
      "a": "Fluid accumulation in the alveoli — usually from CHF. Causes pink/frothy sputum, severe dyspnea, patient sitting upright (orthopnea)."
    },
    {
      "id": "ch-16.fc.07",
      "q": "What SpO2 level generally warrants supplemental oxygen?",
      "a": "SpO2 below 94% in most patients. For COPD patients, use caution and target 88-92% to avoid eliminating hypoxic drive."
    },
    {
      "id": "ch-16.fc.08",
      "q": "What position helps a CHF patient breathe easier?",
      "a": "Fowler's or semi-Fowler's (sitting upright) — reduces venous return and decreases pulmonary congestion."
    }
  ],
  "notes": [
    {
      "id": "ch-16.n.01",
      "title": "Assessment of Respiratory Emergencies",
      "body": "Assess rate, rhythm, depth, and quality of breathing. Auscultate lung sounds bilaterally. Identify if obstruction is upper (stridor) or lower (wheezing). Determine if distress is obstructive (asthma/COPD) or fluid-based (CHF/pulmonary edema). Treat life threats immediately.",
      "terms": [
        "Stridor",
        "Wheezing",
        "Crackles",
        "Auscultation",
        "Accessory muscles"
      ]
    },
    {
      "id": "ch-16.n.02",
      "title": "Obstructive Lung Diseases",
      "body": "Asthma causes reversible bronchospasm — treat with bronchodilator (albuterol) inhaler. COPD (emphysema/chronic bronchitis) is irreversible airflow limitation. COPD patients may retain CO2 and rely on hypoxic drive — administer O2 cautiously (target SpO2 88-92%).",
      "terms": [
        "Bronchospasm",
        "Albuterol",
        "Hypoxic drive",
        "COPD",
        "Barrel chest"
      ]
    },
    {
      "id": "ch-16.n.03",
      "title": "CHF & Pulmonary Edema",
      "body": "Left heart failure causes fluid backup into pulmonary circulation — pulmonary edema. Patient presents sitting upright (orthopnea), with crackles (rales), pink frothy sputum, and severe anxiety. High-flow O2 and upright positioning are key EMT interventions. Rapid transport.",
      "terms": [
        "CHF",
        "Pulmonary edema",
        "Orthopnea",
        "Crackles",
        "Pink frothy sputum"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-16.q.01",
      "q": "Stridor indicates obstruction of the:",
      "opts": [
        "A. Lower airway (bronchi)",
        "B. Upper airway (larynx/trachea)",
        "C. Alveoli",
        "D. Pleural space"
      ],
      "ans": 1,
      "exp": "Stridor is a high-pitched inspiratory sound caused by upper airway narrowing at the larynx or trachea.",
      "level1": {
        "q": "What is the difference between wheezing and stridor?",
        "opts": [
          "A. Upper airway (larynx/trachea)",
          "B. Alveoli"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-16.q.02",
      "q": "Target SpO2 for a COPD patient on oxygen:",
      "opts": [
        "A. 95-100%",
        "B. 94-98%",
        "C. 88-92%",
        "D. Below 85%"
      ],
      "ans": 2,
      "exp": "COPD patients may rely on hypoxic drive. Over-oxygenating may suppress their respiratory drive — target 88-92% SpO2.",
      "level1": {
        "q": "What is Target SpO2 for a COPD patient on oxygen?",
        "opts": [
          "A. 88-92%",
          "B. 94-98%"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-16.q.03",
      "q": "A CHF patient in respiratory distress should be positioned:",
      "opts": [
        "A. Supine (flat)",
        "B. Trendelenburg",
        "C. Sitting upright (Fowler's)",
        "D. Recovery position"
      ],
      "ans": 2,
      "exp": "Upright position reduces venous return to the heart, decreasing pulmonary congestion and improving breathing in CHF.",
      "level1": {
        "q": "What position helps a CHF patient breathe easier?",
        "opts": [
          "A. Sitting upright (Fowler's)",
          "B. Supine (flat)"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-16.q.04",
      "q": "Before assisting with a patient's inhaler, you must:",
      "opts": [
        "A. Confirm the prescription belongs to the patient",
        "B. Check blood pressure first",
        "C. Administer oxygen first always",
        "D. Always get online medical direction"
      ],
      "ans": 0,
      "exp": "Confirm the prescription is prescribed to this patient, check for contraindications, and follow local protocol for medical direction.",
      "level1": {
        "q": "How do you assist with a metered-dose inhaler (MDI)?",
        "opts": [
          "A. Confirm the prescription belongs to the patient",
          "B. Check blood pressure first"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-16.q.05",
      "q": "Pink frothy sputum with crackles and severe dyspnea suggests:",
      "opts": [
        "A. Asthma",
        "B. Pulmonary embolism",
        "C. Pulmonary edema (CHF)",
        "D. Pneumothorax"
      ],
      "ans": 2,
      "exp": "Pink/frothy sputum with wet crackles (rales) is classic for pulmonary edema from CHF — fluid has entered the alveoli.",
      "level1": {
        "q": "What is Pink frothy sputum with crackles and severe dyspnea suggests?",
        "opts": [
          "A. Pulmonary edema (CHF)",
          "B. Asthma"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-16.q.06",
      "q": "Wheezing is caused by:",
      "opts": [
        "A. Upper airway obstruction",
        "B. Lower airway bronchoconstriction",
        "C. Fluid in alveoli",
        "D. Pleural effusion"
      ],
      "ans": 1,
      "exp": "Wheezing is a musical expiratory sound caused by narrowed lower airways — classic in asthma and COPD exacerbations.",
      "level1": {
        "q": "What is the difference between wheezing and stridor?",
        "opts": [
          "A. Lower airway bronchoconstriction",
          "B. Fluid in alveoli"
        ],
        "ans": 0
      }
    }
  ]
};
