// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch18: Chapter = {
  "id": "ch-18",
  "number": 18,
  "partId": "part-09",
  "title": "Altered Mental Status, Stroke & Headache",
  "cards": [
    {
      "id": "ch-18.fc.01",
      "q": "What is altered mental status (AMS)?",
      "a": "Any deviation from normal mental function — includes confusion, disorientation, combativeness, lethargy, or unconsciousness."
    },
    {
      "id": "ch-18.fc.02",
      "q": "What does AEIOU-TIPS stand for?",
      "a": "Alcohol, Epilepsy, Insulin/diabetic, Overdose, Uremia, Trauma, Infection, Psychiatric, Stroke/Syncope — causes of AMS."
    },
    {
      "id": "ch-18.fc.03",
      "q": "What is the Cincinnati Stroke Scale?",
      "a": "Facial droop, arm drift, abnormal speech — any one positive = high stroke suspicion (72% probability)."
    },
    {
      "id": "ch-18.fc.04",
      "q": "Why is stroke time critical?",
      "a": "tPA (clot-busting drug) must be given within 3-4.5 hours of symptom onset in ischemic stroke — document exact onset time."
    },
    {
      "id": "ch-18.fc.05",
      "q": "What is the difference between ischemic and hemorrhagic stroke?",
      "a": "Ischemic: clot blocking cerebral blood flow (80% of strokes). Hemorrhagic: blood vessel ruptures into brain tissue."
    },
    {
      "id": "ch-18.fc.06",
      "q": "What is a TIA?",
      "a": "Transient Ischemic Attack — stroke-like symptoms that resolve within 24 hours. A major warning sign of impending stroke."
    },
    {
      "id": "ch-18.fc.07",
      "q": "What is a thunderclap headache?",
      "a": "A sudden, severe headache described as the 'worst of my life' — classic presentation of subarachnoid hemorrhage."
    },
    {
      "id": "ch-18.fc.08",
      "q": "What position is recommended for a conscious stroke patient?",
      "a": "Head elevated 15-30 degrees if no spinal concern — reduces intracranial pressure. Keep NPO (nothing by mouth)."
    }
  ],
  "notes": [
    {
      "id": "ch-18.n.01",
      "title": "Evaluating AMS",
      "body": "AMS has many causes — use AEIOU-TIPS as a memory aid. Always check blood glucose in any AMS patient. Assume hypoglycemia until proven otherwise. Perform rapid neurological exam: AVPU, pupils, grip strength, and facial symmetry.",
      "terms": [
        "AEIOU-TIPS",
        "AVPU",
        "Neurological exam",
        "Hypoglycemia",
        "Pupils"
      ]
    },
    {
      "id": "ch-18.n.02",
      "title": "Stroke Recognition & Management",
      "body": "Recognize stroke with Cincinnati Stroke Scale or FAST. Document exact time of symptom onset — critical for tPA eligibility. Keep patient calm, NPO, position with head elevated 15-30 degrees if no spinal concern. Transport to stroke center immediately.",
      "terms": [
        "Cincinnati Stroke Scale",
        "tPA",
        "Ischemic stroke",
        "Hemorrhagic stroke",
        "Stroke center"
      ]
    },
    {
      "id": "ch-18.n.03",
      "title": "Headache in EMS",
      "body": "Most headaches are benign (tension, migraine). Concerning signs: 'worst headache of life,' sudden onset (thunderclap), with fever/neck stiffness (meningitis), or following trauma. These warrant urgent transport. Subarachnoid hemorrhage classically presents as the worst headache ever experienced.",
      "terms": [
        "Thunderclap headache",
        "Subarachnoid hemorrhage",
        "Meningitis",
        "Migraine",
        "TIA"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-18.q.01",
      "q": "The Cincinnati Stroke Scale evaluates:",
      "opts": [
        "A. Pupils, pulse, pressure",
        "B. Facial droop, arm drift, speech",
        "C. GCS, LOC, pupils",
        "D. Blood glucose, BP, SpO2"
      ],
      "ans": 1,
      "exp": "Cincinnati Stroke Scale: Facial droop, Arm drift, Speech — any one abnormal = 72% probability of stroke.",
      "level1": {
        "q": "What is the Cincinnati Stroke Scale?",
        "opts": [
          "A. Facial droop, arm drift, speech",
          "B. GCS, LOC, pupils"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-18.q.02",
      "q": "Time is critical in stroke management because:",
      "opts": [
        "A. Aspirin must be given within 1 hour",
        "B. tPA must be given within 3-4.5 hours of symptom onset",
        "C. CPR must start within 4 minutes",
        "D. Oxygen depletes quickly"
      ],
      "ans": 1,
      "exp": "Ischemic stroke treatment with tPA has a 3-4.5 hour window from symptom onset — exact onset time must be documented.",
      "level1": {
        "q": "Why is stroke time critical?",
        "opts": [
          "A. tPA must be given within 3-4.5 hours of symptom onset",
          "B. Oxygen depletes quickly"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-18.q.03",
      "q": "AEIOU-TIPS is used to remember causes of:",
      "opts": [
        "A. Cardiac arrest",
        "B. Altered mental status",
        "C. Respiratory failure",
        "D. Trauma priorities"
      ],
      "ans": 1,
      "exp": "AEIOU-TIPS lists common causes of AMS: Alcohol, Epilepsy, Insulin, Overdose, Uremia, Trauma, Infection, Psychiatric, Stroke.",
      "level1": {
        "q": "What is AEIOU-TIPS is used to remember causes of?",
        "opts": [
          "A. Altered mental status",
          "B. Cardiac arrest"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-18.q.04",
      "q": "A TIA differs from a stroke because:",
      "opts": [
        "A. TIA causes permanent deficits",
        "B. TIA symptoms resolve, usually within 24 hours",
        "C. TIA only affects vision",
        "D. TIA requires tPA"
      ],
      "ans": 1,
      "exp": "A TIA produces stroke-like symptoms that resolve completely, but it is a major warning sign of impending stroke.",
      "level1": {
        "q": "What is a TIA?",
        "opts": [
          "A. TIA symptoms resolve, usually within 24 hours",
          "B. TIA requires tPA"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-18.q.05",
      "q": "A thunderclap headache should raise suspicion for:",
      "opts": [
        "A. Migraine",
        "B. Tension headache",
        "C. Subarachnoid hemorrhage",
        "D. Ear infection"
      ],
      "ans": 2,
      "exp": "Subarachnoid hemorrhage classically presents as a sudden, severe 'thunderclap' — the worst headache of the patient's life. Transport urgently.",
      "level1": {
        "q": "What is a thunderclap headache?",
        "opts": [
          "A. Subarachnoid hemorrhage",
          "B. Migraine"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-18.q.06",
      "q": "First action for any AMS patient:",
      "opts": [
        "A. Administer oral glucose",
        "B. Check blood glucose",
        "C. Perform detailed neurological exam",
        "D. Obtain full SAMPLE history"
      ],
      "ans": 1,
      "exp": "Check blood glucose first in any AMS patient — hypoglycemia is immediately treatable and can mimic many serious conditions.",
      "level1": {
        "q": "What is First action for any AMS patient?",
        "opts": [
          "A. Check blood glucose",
          "B. Administer oral glucose"
        ],
        "ans": 0
      }
    }
  ]
};
