// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch13: Chapter = {
  "id": "ch-13",
  "number": 13,
  "partId": "part-06",
  "title": "Patient Assessment",
  "cards": [
    {
      "id": "ch-13.fc.01",
      "q": "What are the components of the primary assessment?",
      "a": "General impression, level of consciousness (AVPU), airway, breathing, circulation, and priority/transport decision."
    },
    {
      "id": "ch-13.fc.02",
      "q": "What does AVPU stand for?",
      "a": "Alert, Verbal (responds to voice), Pain (responds to pain stimuli), Unresponsive."
    },
    {
      "id": "ch-13.fc.03",
      "q": "What is the purpose of the secondary assessment?",
      "a": "A systematic head-to-toe or focused physical exam to find additional injuries or conditions after life threats are controlled."
    },
    {
      "id": "ch-13.fc.04",
      "q": "How often should you reassess a stable patient?",
      "a": "Every 15 minutes. Unstable or critical patients: every 5 minutes."
    },
    {
      "id": "ch-13.fc.05",
      "q": "What is a rapid trauma assessment?",
      "a": "A quick head-to-toe assessment for significant MOI to identify life threats — performed before detailed exam."
    },
    {
      "id": "ch-13.fc.06",
      "q": "What is DCAP-BTLS?",
      "a": "Deformities, Contusions, Abrasions, Punctures/Penetrations, Burns, Tenderness, Lacerations, Swelling — assessment findings during physical exam."
    },
    {
      "id": "ch-13.fc.07",
      "q": "When should you perform a focused vs. full-body assessment?",
      "a": "Focused: isolated complaint with no significant MOI. Full-body (rapid): significant MOI, altered LOC, or multiple complaints."
    },
    {
      "id": "ch-13.fc.08",
      "q": "What is trending in patient assessment?",
      "a": "Tracking changes in vital signs and condition over time — improving or deteriorating trends guide transport and care decisions."
    }
  ],
  "notes": [
    {
      "id": "ch-13.n.01",
      "title": "Primary Assessment",
      "body": "Rapidly identify and treat life threats. General impression from across the room. AVPU for mental status. Open airway with appropriate maneuver. Assess breathing adequacy and circulation (pulse, major bleeding). Assign priority: emergent (load and go) vs. non-emergent (stay and play).",
      "terms": [
        "General impression",
        "AVPU",
        "Life threat",
        "Priority",
        "Transport decision"
      ]
    },
    {
      "id": "ch-13.n.02",
      "title": "Secondary Assessment & Physical Exam",
      "body": "Head-to-toe assessment using DCAP-BTLS at each region. Use look, listen, and feel. Assess pupils, chest, abdomen, pelvis, extremities, and posterior. Compare bilateral findings. Document all findings — both positive and pertinent negative findings.",
      "terms": [
        "DCAP-BTLS",
        "Head-to-toe",
        "Bilateral",
        "Pupils",
        "Pertinent negatives"
      ]
    },
    {
      "id": "ch-13.n.03",
      "title": "Reassessment",
      "body": "Reassessment confirms your initial findings, checks effectiveness of interventions, and detects changes in patient condition. Stable: every 15 minutes. Unstable: every 5 minutes. Always reassess after any intervention. Trending vital signs are as important as single readings.",
      "terms": [
        "Reassessment",
        "Trending",
        "Intervention effectiveness",
        "Stable",
        "Unstable"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-13.q.01",
      "q": "During primary assessment, level of consciousness is assessed using:",
      "opts": [
        "A. GCS",
        "B. AVPU",
        "C. SAMPLE",
        "D. OPQRST"
      ],
      "ans": 1,
      "exp": "AVPU (Alert, Verbal, Pain, Unresponsive) is the rapid LOC scale used during primary assessment."
    },
    {
      "id": "ch-13.q.02",
      "q": "DCAP-BTLS is used during:",
      "opts": [
        "A. Scene size-up",
        "B. Primary assessment",
        "C. Physical exam / secondary assessment",
        "D. Patient handoff"
      ],
      "ans": 2,
      "exp": "DCAP-BTLS is the mnemonic for physical exam findings assessed at each body region during the secondary assessment."
    },
    {
      "id": "ch-13.q.03",
      "q": "How often should an unstable patient be reassessed?",
      "opts": [
        "A. Every 15 minutes",
        "B. Every 10 minutes",
        "C. Every 5 minutes",
        "D. Only at the hospital"
      ],
      "ans": 2,
      "exp": "Unstable or critical patients require reassessment every 5 minutes to detect changes in their condition."
    },
    {
      "id": "ch-13.q.04",
      "q": "A rapid trauma assessment is indicated for:",
      "opts": [
        "A. All patients",
        "B. Patients with significant MOI or altered LOC",
        "C. Medical patients only",
        "D. Patients who request it"
      ],
      "ans": 1,
      "exp": "Rapid trauma assessment is performed when significant MOI exists, when the patient has altered LOC, or when multiple complaints are present."
    },
    {
      "id": "ch-13.q.05",
      "q": "Trending in patient assessment means:",
      "opts": [
        "A. Following current treatment trends",
        "B. Tracking changes in condition and vitals over time",
        "C. Using social media for protocols",
        "D. Comparing to other patients"
      ],
      "ans": 1,
      "exp": "Trending tracks whether the patient is improving or deteriorating over time — a series of falling blood pressures is more alarming than one low reading."
    },
    {
      "id": "ch-13.q.06",
      "q": "Pertinent negatives should be:",
      "opts": [
        "A. Ignored unless significant",
        "B. Documented because they help rule out conditions",
        "C. Only noted for trauma patients",
        "D. Listed only in the verbal report"
      ],
      "ans": 1,
      "exp": "Pertinent negatives (symptoms the patient denies) are important documentation — they show a thorough assessment was performed."
    }
  ]
};
