// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch17: Chapter = {
  "id": "ch-17",
  "number": 17,
  "partId": "part-09",
  "title": "Cardiac Emergencies & Resuscitation",
  "cards": [
    {
      "id": "ch-17.fc.01",
      "q": "What is the chain of survival?",
      "a": "Early recognition, early CPR, early defibrillation, early advanced care — the sequence that improves cardiac arrest survival."
    },
    {
      "id": "ch-17.fc.02",
      "q": "What does AED stand for and what does it do?",
      "a": "Automated External Defibrillator — analyzes heart rhythm and delivers a shock to correct ventricular fibrillation or pulseless VT."
    },
    {
      "id": "ch-17.fc.03",
      "q": "Adult CPR compression rate:",
      "a": "100-120 compressions per minute."
    },
    {
      "id": "ch-17.fc.04",
      "q": "Adult CPR compression depth:",
      "a": "At least 2 inches (5 cm), no more than 2.4 inches. Allow full chest recoil between compressions."
    },
    {
      "id": "ch-17.fc.05",
      "q": "What is ventricular fibrillation (VF)?",
      "a": "A chaotic, disorganized electrical rhythm causing the heart to quiver rather than pump — a shockable rhythm."
    },
    {
      "id": "ch-17.fc.06",
      "q": "What is AMI?",
      "a": "Acute Myocardial Infarction — heart attack. Blockage of a coronary artery causing myocardial cell death."
    },
    {
      "id": "ch-17.fc.07",
      "q": "What is aspirin's role in chest pain management?",
      "a": "Aspirin (324 mg chewed) inhibits platelet aggregation, reducing clot size in AMI — given if not allergic and no contraindications."
    },
    {
      "id": "ch-17.fc.08",
      "q": "After an AED shock, what do you do?",
      "a": "Resume CPR immediately — do not pause to check pulse. Continue 2 minutes then re-analyze."
    }
  ],
  "notes": [
    {
      "id": "ch-17.n.01",
      "title": "CPR Technique",
      "body": "High-quality CPR: rate 100-120/min, depth ≥2 inches, full chest recoil between compressions, minimize interruptions (<10 sec), avoid hyperventilation. Switch compressors every 2 minutes to prevent fatigue and maintain quality compressions.",
      "terms": [
        "Compression rate",
        "Compression depth",
        "Full recoil",
        "Minimize interruptions",
        "Ratio 30:2"
      ]
    },
    {
      "id": "ch-17.n.02",
      "title": "AED Use",
      "body": "Power on, apply pads (right clavicle / left axilla), clear the patient, analyze, shock if advised. Resume CPR immediately after shock — every minute without defibrillation reduces survival by 7-10%. Use pediatric pads for ages 1-8.",
      "terms": [
        "AED",
        "Defibrillation",
        "Pad placement",
        "Shockable rhythm",
        "Pediatric pads"
      ]
    },
    {
      "id": "ch-17.n.03",
      "title": "AMI Recognition & Management",
      "body": "Classic chest pain: crushing, radiating to left arm/jaw, with diaphoresis and nausea. Position comfortably. O2 if SpO2 <94%. Administer aspirin 324 mg (chewed). Assist with nitroglycerin per protocol. Rapid transport — door-to-balloon time is critical.",
      "terms": [
        "AMI",
        "Aspirin",
        "Nitroglycerin",
        "Diaphoresis",
        "Rapid transport"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-17.q.01",
      "q": "Adult CPR compression rate:",
      "opts": [
        "A. 60-80/min",
        "B. 80-100/min",
        "C. 100-120/min",
        "D. 120-140/min"
      ],
      "ans": 2,
      "exp": "AHA guidelines require 100-120 compressions per minute for effective CPR in adults.",
      "easy": {
        "q": "Adult CPR compression rate:?",
        "opts": [
          "A. 100-120/min",
          "B. 60-80/min"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Adult CPR compression rate?",
        "opts": [
          "A. 120-140/min",
          "B. 80-100/min",
          "C. 100-120/min",
          "D. 60-80/min"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-17.q.02",
      "q": "After an AED shock, you should:",
      "opts": [
        "A. Check pulse for 1 minute",
        "B. Resume CPR immediately",
        "C. Wait for AED re-analysis",
        "D. Transport immediately"
      ],
      "ans": 1,
      "exp": "Resume CPR immediately after a shock — do not pause to check a pulse. Continue 2 minutes then re-analyze.",
      "easy": {
        "q": "After an AED shock, what do you do?",
        "opts": [
          "A. Resume CPR immediately",
          "B. Transport immediately"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Power on, apply pads (right clavicle / left axilla), clear the patient, analyze, shock if advised. Based on this presentation, after an AED shock, you should?",
        "opts": [
          "A. Check pulse for 1 minute",
          "B. Wait for AED re-analysis",
          "C. Resume CPR immediately",
          "D. Transport immediately"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-17.q.03",
      "q": "Ventricular fibrillation is treated with:",
      "opts": [
        "A. CPR only",
        "B. Epinephrine",
        "C. Defibrillation",
        "D. Airway management only"
      ],
      "ans": 2,
      "exp": "VF is a shockable rhythm. Early defibrillation is the definitive treatment. CPR continues until the AED is ready.",
      "easy": {
        "q": "What is Ventricular fibrillation is treated with?",
        "opts": [
          "A. Defibrillation",
          "B. CPR only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Ventricular fibrillation is treated with?",
        "opts": [
          "A. Airway management only",
          "B. Epinephrine",
          "C. Defibrillation",
          "D. CPR only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-17.q.04",
      "q": "Adult compression depth:",
      "opts": [
        "A. 1 inch",
        "B. At least 2 inches",
        "C. 3 inches",
        "D. Depth does not matter"
      ],
      "ans": 1,
      "exp": "Adult compressions must be at least 2 inches deep (5 cm) but no more than 2.4 inches for effective blood flow.",
      "easy": {
        "q": "Adult CPR compression depth:?",
        "opts": [
          "A. At least 2 inches",
          "B. 1 inch"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Adult compression depth?",
        "opts": [
          "A. Depth does not matter",
          "B. 3 inches",
          "C. At least 2 inches",
          "D. 1 inch"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-17.q.05",
      "q": "Aspirin in cardiac chest pain works by:",
      "opts": [
        "A. Relieving pain",
        "B. Lowering blood pressure",
        "C. Inhibiting platelet aggregation",
        "D. Opening coronary arteries"
      ],
      "ans": 2,
      "exp": "Aspirin inhibits platelet aggregation, helping prevent clot growth in an occluded coronary artery during AMI.",
      "easy": {
        "q": "What is aspirin's role in chest pain management?",
        "opts": [
          "A. Inhibiting platelet aggregation",
          "B. Relieving pain"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Classic chest pain: crushing, radiating to left arm/jaw, with diaphoresis and nausea. Based on this presentation, aspirin in cardiac chest pain works by?",
        "opts": [
          "A. Opening coronary arteries",
          "B. Lowering blood pressure",
          "C. Inhibiting platelet aggregation",
          "D. Relieving pain"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-17.q.06",
      "q": "Pediatric AED pads are used for:",
      "opts": [
        "A. Infants only",
        "B. Ages 1-8 or under 55 lbs",
        "C. Ages 1-12",
        "D. All children under 18"
      ],
      "ans": 1,
      "exp": "Pediatric pads (attenuated dose) for ages 1-8 or under 55 lbs. For infants under 1, a manual defibrillator is preferred.",
      "easy": {
        "q": "What is Pediatric AED pads are used for?",
        "opts": [
          "A. Ages 1-8 or under 55 lbs",
          "B. Ages 1-12"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Power on, apply pads (right clavicle / left axilla), clear the patient, analyze, shock if advised. Based on this presentation, pediatric AED pads are used for?",
        "opts": [
          "A. All children under 18",
          "B. Infants only",
          "C. Ages 1-8 or under 55 lbs",
          "D. Ages 1-12"
        ],
        "ans": 2
      }
    }
  ]
};
