// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch10: Chapter = {
  "id": "ch-10",
  "number": 10,
  "partId": "part-05",
  "title": "Airway Management, Ventilation & Oxygenation",
  "cards": [
    {
      "id": "ch-10.fc.01",
      "q": "What is the preferred airway maneuver for a trauma patient?",
      "a": "Jaw-thrust maneuver — opens the airway without moving the cervical spine."
    },
    {
      "id": "ch-10.fc.02",
      "q": "What is head-tilt chin-lift used for?",
      "a": "Opening the airway in unresponsive medical patients with no suspected spinal injury."
    },
    {
      "id": "ch-10.fc.03",
      "q": "What are the two types of airway adjuncts?",
      "a": "Oropharyngeal airway (OPA) and Nasopharyngeal airway (NPA)."
    },
    {
      "id": "ch-10.fc.04",
      "q": "When is an OPA contraindicated?",
      "a": "In conscious or semi-conscious patients with a gag reflex — it will cause vomiting and aspiration risk."
    },
    {
      "id": "ch-10.fc.05",
      "q": "How do you size an OPA?",
      "a": "Measure from the corner of the mouth to the earlobe, or from the center of the mouth to the angle of the jaw."
    },
    {
      "id": "ch-10.fc.06",
      "q": "What flow rate does a non-rebreather mask deliver?",
      "a": "10-15 L/min, delivering approximately 90% oxygen."
    },
    {
      "id": "ch-10.fc.07",
      "q": "What is a nasal cannula used for?",
      "a": "Delivering low-flow oxygen (1-6 L/min) to patients needing mild supplemental O2 who are breathing adequately."
    },
    {
      "id": "ch-10.fc.08",
      "q": "What is the BVM ventilation rate for an adult?",
      "a": "One breath every 5-6 seconds (10-12 breaths per minute)."
    }
  ],
  "notes": [
    {
      "id": "ch-10.n.01",
      "title": "Opening the Airway",
      "body": "Head-tilt chin-lift for medical patients without spinal concern. Jaw-thrust for trauma (no head movement). Suction any secretions immediately. Recovery position helps maintain airway in breathing, unconscious patients without spinal injury.",
      "terms": [
        "Head-tilt chin-lift",
        "Jaw-thrust",
        "Suction",
        "Recovery position",
        "Sniffing position"
      ]
    },
    {
      "id": "ch-10.n.02",
      "title": "Airway Adjuncts",
      "body": "OPA holds the tongue away from the posterior pharynx — only for unconscious patients without a gag reflex. NPA is tolerated by semi-conscious patients. Always size correctly — OPA measured from corner of mouth to earlobe.",
      "terms": [
        "OPA",
        "NPA",
        "Gag reflex",
        "Sizing",
        "Airway adjunct"
      ]
    },
    {
      "id": "ch-10.n.03",
      "title": "Oxygen Delivery Devices",
      "body": "Nasal cannula: 24-44% O2 at 1-6 LPM. Simple face mask: 35-60% at 6-10 LPM. Non-rebreather: up to 90% at 10-15 LPM. BVM with supplemental O2: ~100%. Target SpO2 94-99% in most patients; 88-92% in COPD.",
      "terms": [
        "Non-rebreather",
        "Nasal cannula",
        "BVM",
        "SpO2",
        "Supplemental oxygen"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-10.q.01",
      "q": "A trauma patient is unresponsive. Correct airway maneuver:",
      "opts": [
        "A. Head-tilt chin-lift",
        "B. Jaw-thrust",
        "C. Finger sweep",
        "D. Hyperextension"
      ],
      "ans": 1,
      "exp": "Jaw-thrust is used for suspected spinal trauma — it opens the airway without extending the neck.",
      "level1": {
        "q": "What is the preferred airway maneuver for a trauma patient?",
        "opts": [
          "A. Jaw-thrust",
          "B. Finger sweep"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-10.q.02",
      "q": "OPA is CONTRAINDICATED in patients who:",
      "opts": [
        "A. Are unresponsive",
        "B. Have no gag reflex",
        "C. Are semi-conscious with a gag reflex",
        "D. Are apneic"
      ],
      "ans": 2,
      "exp": "OPA in a patient with a gag reflex triggers vomiting and aspiration risk. Use NPA instead.",
      "level1": {
        "q": "When is an OPA contraindicated?",
        "opts": [
          "A. Are semi-conscious with a gag reflex",
          "B. Are apneic"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-10.q.03",
      "q": "Non-rebreather mask flow rate:",
      "opts": [
        "A. 2-4 L/min",
        "B. 6-8 L/min",
        "C. 10-15 L/min",
        "D. 20 L/min"
      ],
      "ans": 2,
      "exp": "NRB requires 10-15 L/min to keep the reservoir bag inflated, delivering approximately 90% oxygen.",
      "level1": {
        "q": "What flow rate does a non-rebreather mask deliver?",
        "opts": [
          "A. 10-15 L/min",
          "B. 20 L/min"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-10.q.04",
      "q": "Adult BVM ventilation rate:",
      "opts": [
        "A. 1 breath every 2-3 seconds",
        "B. 1 breath every 5-6 seconds",
        "C. 1 breath every 10 seconds",
        "D. 20 breaths per minute"
      ],
      "ans": 1,
      "exp": "Adult BVM: 1 breath every 5-6 seconds (10-12/min). Over-ventilation causes gastric distension and reduces cardiac output.",
      "level1": {
        "q": "What is the BVM ventilation rate for an adult?",
        "opts": [
          "A. 1 breath every 5-6 seconds",
          "B. 20 breaths per minute"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-10.q.05",
      "q": "Which device delivers highest O2 concentration?",
      "opts": [
        "A. Nasal cannula",
        "B. Simple face mask",
        "C. Partial rebreather",
        "D. BVM with 100% O2"
      ],
      "ans": 3,
      "exp": "BVM connected to 100% O2 delivers the highest concentration. NRB ~90%, simple mask ~35-60%, nasal cannula ~24-44%.",
      "level1": {
        "q": "Name the option that correctly answers: Which device delivers highest O2 concentration?",
        "opts": [
          "A. BVM with 100% O2",
          "B. Nasal cannula"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-10.q.06",
      "q": "Signs of INADEQUATE breathing include:",
      "opts": [
        "A. Rate 16/min, equal chest rise",
        "B. Pink skin, SpO2 98%",
        "C. Cyanosis, use of accessory muscles",
        "D. Strong radial pulse"
      ],
      "ans": 2,
      "exp": "Cyanosis, retractions, accessory muscle use, and abnormal rate/depth all indicate inadequate breathing requiring intervention.",
      "level1": {
        "q": "What is Signs of INADEQUATE breathing include?",
        "opts": [
          "A. Cyanosis, use of accessory muscles",
          "B. Pink skin, SpO2 98%"
        ],
        "ans": 0
      }
    }
  ]
};
