// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch19: Chapter = {
  "id": "ch-19",
  "number": 19,
  "partId": "part-09",
  "title": "Seizures & Syncope",
  "cards": [
    {
      "id": "ch-19.fc.01",
      "q": "What is a generalized tonic-clonic seizure?",
      "a": "A seizure involving loss of consciousness and rhythmic jerking of all extremities — previously called 'grand mal.'"
    },
    {
      "id": "ch-19.fc.02",
      "q": "What is the postictal phase?",
      "a": "The period of confusion, fatigue, and disorientation following a seizure — can last minutes to hours."
    },
    {
      "id": "ch-19.fc.03",
      "q": "What is status epilepticus?",
      "a": "A seizure lasting more than 5 minutes, or two seizures without regaining consciousness — a medical emergency."
    },
    {
      "id": "ch-19.fc.04",
      "q": "What should NOT be done during an active seizure?",
      "a": "Do not restrain the patient, do not put anything in the mouth, do not leave the patient alone."
    },
    {
      "id": "ch-19.fc.05",
      "q": "What is syncope?",
      "a": "A brief loss of consciousness caused by temporary decrease in cerebral perfusion — commonly 'fainting.'"
    },
    {
      "id": "ch-19.fc.06",
      "q": "What are common causes of syncope?",
      "a": "Vasovagal (emotional/pain), orthostatic hypotension, cardiac arrhythmia, hypoglycemia, and dehydration."
    },
    {
      "id": "ch-19.fc.07",
      "q": "What is a febrile seizure?",
      "a": "A seizure triggered by rapid temperature rise in a child 6 months to 5 years — generally benign but may indicate serious infection."
    },
    {
      "id": "ch-19.fc.08",
      "q": "What is vasovagal syncope?",
      "a": "Syncope triggered by emotional stress, pain, or fear activating the vagus nerve — causing bradycardia and vasodilation."
    }
  ],
  "notes": [
    {
      "id": "ch-19.n.01",
      "title": "Seizure Types & Phases",
      "body": "Seizures can be partial (focal) or generalized. Tonic phase: muscle rigidity. Clonic phase: rhythmic jerking. Postictal phase: confusion and fatigue. Absence seizures are brief staring spells with no postictal period. Always identify the underlying cause and document seizure duration.",
      "terms": [
        "Tonic-clonic",
        "Postictal",
        "Absence seizure",
        "Focal seizure",
        "Status epilepticus"
      ]
    },
    {
      "id": "ch-19.n.02",
      "title": "Seizure Management",
      "body": "During seizure: protect from injury, do not restrain, do not insert anything in mouth, time the seizure. After: lateral position to prevent aspiration, suction if secretions, administer O2, assess LOC. Transport all first-time seizures and status epilepticus.",
      "terms": [
        "Lateral position",
        "Suction",
        "Airway management",
        "Oxygen",
        "Timing"
      ]
    },
    {
      "id": "ch-19.n.03",
      "title": "Syncope Assessment",
      "body": "All new-onset syncope warrants evaluation — it may indicate cardiac arrhythmia. Vasovagal is most common (benign). Orthostatic: hypotension when standing. Cardiac syncope: most dangerous — arrhythmia, structural disease. Obtain 12-lead ECG if available. Presyncope is near-fainting without full LOC.",
      "terms": [
        "Vasovagal",
        "Orthostatic hypotension",
        "Cardiac syncope",
        "Presyncope",
        "ECG"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-19.q.01",
      "q": "During an active seizure, you should:",
      "opts": [
        "A. Insert an OPA to protect the airway",
        "B. Restrain the patient to prevent injury",
        "C. Clear the area and protect from injury without restraining",
        "D. Administer oral glucose"
      ],
      "ans": 2,
      "exp": "Clear the area, protect the head, and let the seizure run its course. Restraining causes injury. Never put anything in the mouth.",
      "level1": {
        "q": "What should NOT be done during an active seizure?",
        "opts": [
          "A. Clear the area and protect from injury without restraining",
          "B. Administer oral glucose"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-19.q.02",
      "q": "Status epilepticus is defined as:",
      "opts": [
        "A. A seizure with aura",
        "B. A seizure lasting more than 5 minutes",
        "C. Two isolated seizures in a week",
        "D. A febrile seizure"
      ],
      "ans": 1,
      "exp": "Status epilepticus = seizure >5 minutes OR recurrent seizures without regaining consciousness — a life-threatening emergency.",
      "level1": {
        "q": "What is status epilepticus?",
        "opts": [
          "A. A seizure lasting more than 5 minutes",
          "B. A febrile seizure"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-19.q.03",
      "q": "The postictal phase is characterized by:",
      "opts": [
        "A. Alertness and cooperation",
        "B. Muscle rigidity",
        "C. Confusion, fatigue, and disorientation",
        "D. Hyperventilation"
      ],
      "ans": 2,
      "exp": "The postictal phase follows seizure activity and includes confusion, fatigue, headache, and disorientation lasting minutes to hours.",
      "level1": {
        "q": "What is the postictal phase?",
        "opts": [
          "A. Confusion, fatigue, and disorientation",
          "B. Muscle rigidity"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-19.q.04",
      "q": "Vasovagal syncope is triggered by:",
      "opts": [
        "A. Ventricular fibrillation",
        "B. Emotional stress or pain activating the vagus nerve",
        "C. Pulmonary embolism",
        "D. Hypoglycemia only"
      ],
      "ans": 1,
      "exp": "Vasovagal syncope is triggered by emotional stress, pain, or fear activating the vagus nerve — causing bradycardia and vasodilation leading to brief LOC.",
      "level1": {
        "q": "What is vasovagal syncope?",
        "opts": [
          "A. Emotional stress or pain activating the vagus nerve",
          "B. Hypoglycemia only"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-19.q.05",
      "q": "After a seizure, the patient should be positioned:",
      "opts": [
        "A. Supine with legs elevated",
        "B. On their side (lateral position)",
        "C. Sitting upright",
        "D. Prone"
      ],
      "ans": 1,
      "exp": "Lateral position after seizure maintains airway patency and allows drainage of secretions, reducing aspiration risk.",
      "level1": {
        "q": "What is After a seizure, the patient should be positioned?",
        "opts": [
          "A. On their side (lateral position)",
          "B. Prone"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-19.q.06",
      "q": "Febrile seizures differ from epilepsy in that they are:",
      "opts": [
        "A. More dangerous and require immediate treatment",
        "B. Triggered by rapid temperature rise in children and are generally benign",
        "C. Always indicative of meningitis",
        "D. Chronic and recurrent"
      ],
      "ans": 1,
      "exp": "Febrile seizures occur in children 6 months to 5 years during rapid temperature rise — usually benign, but infection must be ruled out.",
      "level1": {
        "q": "What is a febrile seizure?",
        "opts": [
          "A. Triggered by rapid temperature rise in children and are generally benign",
          "B. Chronic and recurrent"
        ],
        "ans": 0
      }
    }
  ]
};
