// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch14: Chapter = {
  "id": "ch-14",
  "number": 14,
  "partId": "part-07",
  "title": "General Pharmacology & Medication Administration",
  "cards": [
    {
      "id": "ch-14.fc.01",
      "q": "What are the six rights of medication administration?",
      "a": "Right patient, right drug, right dose, right route, right time, right documentation."
    },
    {
      "id": "ch-14.fc.02",
      "q": "What medications can an EMT administer?",
      "a": "Oxygen, oral glucose, aspirin, epinephrine auto-injector, activated charcoal (if authorized). Assist with: nitroglycerin, bronchodilator inhalers, patient's own medications."
    },
    {
      "id": "ch-14.fc.03",
      "q": "What is a contraindication?",
      "a": "A condition that makes a particular treatment or drug dangerous or inappropriate — do not give the medication."
    },
    {
      "id": "ch-14.fc.04",
      "q": "What is the mechanism of action of aspirin?",
      "a": "Inhibits cyclooxygenase (COX), preventing platelet aggregation and thromboxane A2 production — reduces clot formation."
    },
    {
      "id": "ch-14.fc.05",
      "q": "What is the dose of aspirin given for chest pain?",
      "a": "324 mg (four 81mg baby aspirin) — chewed, not swallowed whole, for fastest absorption."
    },
    {
      "id": "ch-14.fc.06",
      "q": "What are side effects of nitroglycerin?",
      "a": "Hypotension, headache, tachycardia — always check BP before and after each dose."
    },
    {
      "id": "ch-14.fc.07",
      "q": "What routes of medication administration do EMTs use?",
      "a": "Oral (PO), sublingual (SL), inhalation, intramuscular (IM via auto-injector), transdermal (assist)."
    },
    {
      "id": "ch-14.fc.08",
      "q": "What is an indication for a medication?",
      "a": "The specific condition or situation for which the medication is intended and approved to treat."
    }
  ],
  "notes": [
    {
      "id": "ch-14.n.01",
      "title": "EMT-Authorized Medications",
      "body": "EMTs can administer a limited set of medications. Some are given directly (oxygen, oral glucose, epinephrine auto-injector, aspirin). Some are patient-prescribed medications the EMT assists with (nitroglycerin, inhaler). Always confirm authorization and contraindications before administering.",
      "terms": [
        "Oral glucose",
        "Epinephrine",
        "Aspirin",
        "Nitroglycerin",
        "Bronchodilator"
      ]
    },
    {
      "id": "ch-14.n.02",
      "title": "Six Rights of Medication Administration",
      "body": "Before any medication: confirm Right Patient, Right Drug (correct medication), Right Dose (correct amount), Right Route (correct method), Right Time (appropriate timing), Right Documentation (record it). Missing any right is a medication error that can harm the patient.",
      "terms": [
        "Six rights",
        "Medication error",
        "Contraindication",
        "Indication",
        "Documentation"
      ]
    },
    {
      "id": "ch-14.n.03",
      "title": "Routes of Administration",
      "body": "Oral (PO): swallowed, slow absorption. Sublingual (SL): under tongue, rapid absorption — nitroglycerin. Inhalation: direct to lungs — albuterol. IM injection: muscle — epinephrine auto-injector. Transdermal: through skin — nitroglycerin patch. Route affects onset speed and bioavailability.",
      "terms": [
        "Sublingual",
        "Inhalation",
        "Intramuscular",
        "Onset",
        "Bioavailability"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-14.q.01",
      "q": "Before administering any medication, the EMT must verify:",
      "opts": [
        "A. Patient's insurance",
        "B. The six rights of medication administration",
        "C. Scene safety only",
        "D. Patient's employment status"
      ],
      "ans": 1,
      "exp": "The six rights (patient, drug, dose, route, time, documentation) must always be verified to prevent medication errors.",
      "easy": {
        "q": "What is an indication for a medication?",
        "opts": [
          "A. The six rights of medication administration",
          "B. Scene safety only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: EMTs can administer a limited set of medications. Based on this presentation, before administering any medication, the EMT must verify?",
        "opts": [
          "A. Patient's employment status",
          "B. Patient's insurance",
          "C. The six rights of medication administration",
          "D. Scene safety only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-14.q.02",
      "q": "Aspirin for chest pain is given as:",
      "opts": [
        "A. 81 mg swallowed whole",
        "B. 324 mg chewed",
        "C. 500 mg IV",
        "D. 650 mg sublingual"
      ],
      "ans": 1,
      "exp": "324 mg of aspirin (4 baby aspirin) chewed provides faster absorption than swallowing whole — crucial in AMI management.",
      "easy": {
        "q": "What is the dose of aspirin given for chest pain?",
        "opts": [
          "A. 324 mg chewed",
          "B. 500 mg IV"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: EMTs can administer a limited set of medications. Based on this presentation, aspirin for chest pain is given as?",
        "opts": [
          "A. 81 mg swallowed whole",
          "B. 650 mg sublingual",
          "C. 324 mg chewed",
          "D. 500 mg IV"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-14.q.03",
      "q": "A contraindication means:",
      "opts": [
        "A. The medication is indicated",
        "B. A condition making the medication dangerous or inappropriate",
        "C. A recommended drug interaction",
        "D. An alternative route"
      ],
      "ans": 1,
      "exp": "Contraindications are specific conditions that make using a medication dangerous — e.g., nitroglycerin with hypotension.",
      "easy": {
        "q": "What is a contraindication?",
        "opts": [
          "A. A condition making the medication dangerous or inappropriate",
          "B. An alternative route"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. A contraindication means?",
        "opts": [
          "A. A recommended drug interaction",
          "B. The medication is indicated",
          "C. A condition making the medication dangerous or inappropriate",
          "D. An alternative route"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-14.q.04",
      "q": "Nitroglycerin's most concerning side effect is:",
      "opts": [
        "A. Hypertension",
        "B. Bradycardia",
        "C. Hypotension",
        "D. Fever"
      ],
      "ans": 2,
      "exp": "Nitroglycerin causes vasodilation which can cause significant hypotension. Always check BP before each dose.",
      "easy": {
        "q": "What are side effects of nitroglycerin?",
        "opts": [
          "A. Hypotension",
          "B. Fever"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Nitroglycerin's most concerning side effect is?",
        "opts": [
          "A. Hypertension",
          "B. Bradycardia",
          "C. Hypotension",
          "D. Fever"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-14.q.05",
      "q": "An EMT may ASSIST a patient with which medication?",
      "opts": [
        "A. Morphine",
        "B. Epinephrine drip",
        "C. Patient's prescribed nitroglycerin",
        "D. IV antibiotics"
      ],
      "ans": 2,
      "exp": "EMTs can assist patients in using their own prescribed medications, including nitroglycerin and metered-dose inhalers, per protocol.",
      "easy": {
        "q": "What medications can an EMT administer?",
        "opts": [
          "A. Patient's prescribed nitroglycerin",
          "B. Morphine"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: EMTs can administer a limited set of medications. Based on this presentation, an EMT may ASSIST a patient with which medication??",
        "opts": [
          "A. Epinephrine drip",
          "B. IV antibiotics",
          "C. Patient's prescribed nitroglycerin",
          "D. Morphine"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-14.q.06",
      "q": "Sublingual medication administration means:",
      "opts": [
        "A. Swallowing the medication",
        "B. Injecting into the muscle",
        "C. Placing under the tongue for rapid absorption",
        "D. Inhaling through the mouth"
      ],
      "ans": 2,
      "exp": "Sublingual (SL) medications are absorbed directly into the bloodstream through the mucous membranes under the tongue — rapid onset.",
      "easy": {
        "q": "What is Sublingual medication administration means?",
        "opts": [
          "A. Placing under the tongue for rapid absorption",
          "B. Swallowing the medication"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Before any medication: confirm Right Patient, Right Drug (correct medication), Right Dose (correct amount), Right Route (correct method), Right Time (appropriate timing), Right Documentation (record it). Based on this presentation, sublingual medication administration means?",
        "opts": [
          "A. Inhaling through the mouth",
          "B. Swallowing the medication",
          "C. Placing under the tongue for rapid absorption",
          "D. Injecting into the muscle"
        ],
        "ans": 2
      }
    }
  ]
};
