// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch15: Chapter = {
  "id": "ch-15",
  "number": 15,
  "partId": "part-08",
  "title": "Shock and Resuscitation",
  "cards": [
    {
      "id": "ch-15.fc.01",
      "q": "What is shock (hypoperfusion)?",
      "a": "Inadequate tissue perfusion — cells do not receive enough oxygenated blood, leading to cellular hypoxia and, if untreated, cellular death."
    },
    {
      "id": "ch-15.fc.02",
      "q": "What are the three causes of shock related to the perfusion triangle?",
      "a": "Inadequate vascular volume (hypovolemic), inadequate heart function (cardiogenic), and decreased peripheral vascular resistance (distributive)."
    },
    {
      "id": "ch-15.fc.03",
      "q": "What are the compensatory and decompensatory stages of shock?",
      "a": "Compensatory: body maintains BP via tachycardia and vasoconstriction — skin pale/cool/clammy, anxious. Decompensatory (progressive): compensatory mechanisms fail — BP drops, altered mental status, weak pulse."
    },
    {
      "id": "ch-15.fc.04",
      "q": "What are the links in the Chain of Survival for cardiac arrest?",
      "a": "Early recognition, early CPR, early defibrillation, and early advanced care — each link must occur quickly to maximize survival."
    },
    {
      "id": "ch-15.fc.05",
      "q": "How do VF, pulseless VT, asystole, and PEA differ?",
      "a": "VF/VT: shockable rhythms with disorganized or fast ventricular activity. Asystole: flatline, no electrical activity. PEA: organized rhythm on monitor but no pulse — all non-shockable except VF/pulseless VT."
    },
    {
      "id": "ch-15.fc.06",
      "q": "What safety precautions apply during resuscitation?",
      "a": "Scene safety first, use BSI/PPE, clear the area before defibrillation, ensure no one touches the patient during shock, and protect yourself and bystanders from body fluids."
    },
    {
      "id": "ch-15.fc.07",
      "q": "Why are AED maintenance and EMT skills maintenance important?",
      "a": "A reliable AED and current CPR/AED skills ensure the Chain of Survival links work when needed — equipment failure or skill decay costs lives."
    },
    {
      "id": "ch-15.fc.08",
      "q": "How does pediatric cardiac arrest resuscitation differ from adult?",
      "a": "Pediatric arrests are often respiratory in origin — prioritize ventilation. Compression depth and rate differ by age. Use pediatric pads or dose attenuator when available."
    }
  ],
  "notes": [
    {
      "id": "ch-15.n.01",
      "title": "Shock Pathophysiology & Stages (Obj 15-2, 15-3, 15-4, 15-6)",
      "body": "Adequate perfusion requires a functioning heart (pump), sufficient blood volume (fluid), and adequate vascular tone (pipes). Shock results when any component fails. Etiologies include hemorrhage, dehydration, heart failure, sepsis, anaphylaxis, and spinal cord injury. Compensatory stage: tachycardia, vasoconstriction, pale/cool/clammy skin, anxiety — BP may remain normal. Decompensatory (progressive) stage: compensatory mechanisms fail, hypotension develops, mental status deteriorates, and death follows without intervention.",
      "terms": [
        "Hypoperfusion",
        "Perfusion triangle",
        "Hypovolemic",
        "Cardiogenic",
        "Distributive",
        "Compensatory",
        "Decompensatory"
      ]
    },
    {
      "id": "ch-15.n.02",
      "title": "Cardiac Arrest Rhythms & Chain of Survival (Obj 15-13, 15-15, 15-17)",
      "body": "Chain of Survival: early recognition → early CPR → early defibrillation → early advanced care. VF and pulseless VT are shockable rhythms — defibrillate immediately. Asystole and PEA are non-shockable — focus on high-quality CPR and treat reversible causes. Adult arrests are usually cardiac; pediatric arrests are often respiratory — ventilate aggressively. Infant/child CPR uses different compression depth and may use two-thumb encircling technique for infants.",
      "terms": [
        "Chain of Survival",
        "VF",
        "Pulseless VT",
        "Asystole",
        "PEA",
        "Defibrillation",
        "CPR"
      ]
    },
    {
      "id": "ch-15.n.03",
      "title": "Resuscitation Safety & System Readiness (Obj 15-20, 15-21)",
      "body": "Ensure scene safety before approaching. Use BSI throughout. Clear all personnel before delivering a shock — announce \"Clear!\" Obey medical direction protocols. AEDs require regular maintenance checks (battery, pads, self-test). EMTs must maintain CPR/AED skills through ongoing training. Medical direction links field providers to physician oversight for protocol guidance during arrest.",
      "terms": [
        "Scene safety",
        "BSI",
        "AED maintenance",
        "Medical direction",
        "Defibrillation safety"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-15.q.01",
      "q": "Shock is best defined as:",
      "opts": [
        "A. Low blood pressure only",
        "B. Inadequate tissue perfusion leading to cellular hypoxia",
        "C. Loss of consciousness",
        "D. Rapid heart rate"
      ],
      "ans": 1,
      "exp": "Shock is hypoperfusion — inadequate delivery of oxygenated blood to cells, causing cellular hypoxia and death if untreated.",
      "easy": {
        "q": "What is shock (hypoperfusion)?",
        "opts": [
          "A. Inadequate tissue perfusion leading to cellular hypoxia",
          "B. Rapid heart rate"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Shock is is MOST accurately defined as?",
        "opts": [
          "A. Low blood pressure only",
          "B. Loss of consciousness",
          "C. Inadequate tissue perfusion leading to cellular hypoxia",
          "D. Rapid heart rate"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.02",
      "q": "Decreased peripheral vascular resistance causes which type of shock?",
      "opts": [
        "A. Hypovolemic",
        "B. Cardiogenic",
        "C. Distributive",
        "D. Obstructive only"
      ],
      "ans": 2,
      "exp": "Distributive shock results from vasodilation and decreased peripheral vascular resistance — seen in sepsis, anaphylaxis, and neurogenic shock.",
      "easy": {
        "q": "What are the three causes of shock related to the perfusion triangle?",
        "opts": [
          "A. Distributive",
          "B. Hypovolemic"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Adequate perfusion requires a functioning heart (pump), sufficient blood volume (fluid), and adequate vascular tone (pipes). Based on this presentation, decreased peripheral vascular resistance causes which type of shock??",
        "opts": [
          "A. Obstructive only",
          "B. Hypovolemic",
          "C. Distributive",
          "D. Cardiogenic"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.03",
      "q": "During the compensatory stage of shock, you would expect:",
      "opts": [
        "A. Hypotension and unresponsiveness",
        "B. Tachycardia and pale, cool, clammy skin with near-normal BP",
        "C. Bradycardia and flushed skin",
        "D. Normal pulse and warm skin"
      ],
      "ans": 1,
      "exp": "Compensatory mechanisms (tachycardia, vasoconstriction) maintain BP early — skin becomes pale, cool, and clammy.",
      "easy": {
        "q": "What are the compensatory and decompensatory stages of shock?",
        "opts": [
          "A. Tachycardia and pale, cool, clammy skin with near-normal BP",
          "B. Normal pulse and warm skin"
        ],
        "ans": 0
      },
      "hard": {
        "q": "During the compensatory stage of shock, you would expect?",
        "opts": [
          "A. Hypotension and unresponsiveness",
          "B. Bradycardia and flushed skin",
          "C. Tachycardia and pale, cool, clammy skin with near-normal BP",
          "D. Normal pulse and warm skin"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.04",
      "q": "Which cardiac arrest rhythms are shockable?",
      "opts": [
        "A. Asystole and PEA",
        "B. VF and pulseless ventricular tachycardia",
        "C. Sinus bradycardia and junctional rhythm",
        "D. PEA only"
      ],
      "ans": 1,
      "exp": "VF and pulseless VT are the only shockable rhythms — deliver defibrillation immediately when recognized.",
      "easy": {
        "q": "How do VF, pulseless VT, asystole, and PEA differ?",
        "opts": [
          "A. VF and pulseless ventricular tachycardia",
          "B. PEA only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Chain of Survival: early recognition → early CPR → early defibrillation → early advanced care. Based on this presentation, which cardiac arrest rhythms are shockable??",
        "opts": [
          "A. Sinus bradycardia and junctional rhythm",
          "B. Asystole and PEA",
          "C. VF and pulseless ventricular tachycardia",
          "D. PEA only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.05",
      "q": "PEA (pulseless electrical activity) is characterized by:",
      "opts": [
        "A. A flatline on the monitor",
        "B. Organized electrical activity on the monitor but no palpable pulse",
        "C. Rapid irregular ventricular activity",
        "D. A normal sinus rhythm with weak pulse"
      ],
      "ans": 1,
      "exp": "PEA shows organized electrical activity on the monitor but no pulse — treat with CPR and search for reversible causes.",
      "easy": {
        "q": "How do VF, pulseless VT, asystole, and PEA differ?",
        "opts": [
          "A. Organized electrical activity on the monitor but no palpable pulse",
          "B. A flatline on the monitor"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. PEA (pulseless electrical activity) is characterized by?",
        "opts": [
          "A. A normal sinus rhythm with weak pulse",
          "B. Rapid irregular ventricular activity",
          "C. Organized electrical activity on the monitor but no palpable pulse",
          "D. A flatline on the monitor"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.06",
      "q": "The Chain of Survival includes all of the following EXCEPT:",
      "opts": [
        "A. Early recognition",
        "B. Early CPR",
        "C. Early defibrillation",
        "D. Delayed transport for on-scene IV access"
      ],
      "ans": 3,
      "exp": "Chain of Survival links: early recognition, early CPR, early defibrillation, and early advanced care — not delayed transport.",
      "easy": {
        "q": "The Chain of Survival does NOT include?",
        "opts": [
          "A. Delayed transport for on-scene IV access",
          "B. Early CPR"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Chain of Survival: early recognition → early CPR → early defibrillation → early advanced care. Based on this presentation, the Chain of Survival includes all of the following EXCEPT?",
        "opts": [
          "A. Early defibrillation",
          "B. Early recognition",
          "C. Delayed transport for on-scene IV access",
          "D. Early CPR"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.07",
      "q": "Before delivering an AED shock, you must:",
      "opts": [
        "A. Continue compressions through the shock",
        "B. Clear the patient and ensure no one is touching them",
        "C. Remove all clothing including undergarments",
        "D. Wait for ALS arrival"
      ],
      "ans": 1,
      "exp": "Announce \"Clear!\" and ensure no one touches the patient during defibrillation to protect rescuers and allow effective energy delivery.",
      "easy": {
        "q": "What safety precautions apply during resuscitation?",
        "opts": [
          "A. Clear the patient and ensure no one is touching them",
          "B. Wait for ALS arrival"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Ensure scene safety before approaching. Based on this presentation, before delivering an AED shock, you must?",
        "opts": [
          "A. Remove all clothing including undergarments",
          "B. Continue compressions through the shock",
          "C. Clear the patient and ensure no one is touching them",
          "D. Wait for ALS arrival"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-15.q.08",
      "q": "Pediatric cardiac arrest is most often caused by:",
      "opts": [
        "A. Primary cardiac arrhythmia",
        "B. Respiratory failure leading to arrest",
        "C. Hypovolemic shock only",
        "D. Traumatic asystole only"
      ],
      "ans": 1,
      "exp": "Unlike adults, most pediatric arrests begin as respiratory problems — prioritize airway and ventilation in pediatric resuscitation.",
      "easy": {
        "q": "How does pediatric cardiac arrest resuscitation differ from adult?",
        "opts": [
          "A. Respiratory failure leading to arrest",
          "B. Hypovolemic shock only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Chain of Survival: early recognition → early CPR → early defibrillation → early advanced care. Based on this presentation, pediatric cardiac arrest is most often caused by?",
        "opts": [
          "A. Primary cardiac arrhythmia",
          "B. Traumatic asystole only",
          "C. Respiratory failure leading to arrest",
          "D. Hypovolemic shock only"
        ],
        "ans": 2
      }
    }
  ]
};
