// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch27: Chapter = {
  "id": "ch-27",
  "number": 27,
  "partId": "part-10",
  "title": "Trauma Overview & Trauma System",
  "cards": [
    {
      "id": "ch-27.fc.01",
      "q": "Why is understanding kinetics important in trauma care?",
      "a": "Kinetics explains how forces and energy transfer during injury — helps EMTs predict injury patterns from the mechanism before physical findings appear."
    },
    {
      "id": "ch-27.fc.02",
      "q": "What is kinetic energy and how does velocity affect it?",
      "a": "KE = ½mv² — kinetic energy depends on mass and velocity squared. Doubling speed quadruples energy, producing more severe injuries."
    },
    {
      "id": "ch-27.fc.03",
      "q": "When should you have a high index of suspicion in an MVC?",
      "a": "High-speed impact, significant vehicle deformity, unrestrained occupants, ejection, rollover, death in same vehicle, and intrusion into passenger compartment."
    },
    {
      "id": "ch-27.fc.04",
      "q": "What are common injury patterns from frontal, lateral, rear, and rotational MVC impacts?",
      "a": "Frontal: lower extremity, chest, head. Lateral: thorax, pelvis, head on impact side. Rear: cervical spine, torso. Rotational: multi-system, spinal injuries."
    },
    {
      "id": "ch-27.fc.05",
      "q": "What restraint-related injuries should you suspect?",
      "a": "Seat belt sign (lap/shoulder bruising), sternal fracture, mesenteric injury, cervical spine injury, and aortic injury from shoulder harness deceleration forces."
    },
    {
      "id": "ch-27.fc.06",
      "q": "What are the phases of blast injury?",
      "a": "Primary: pressure wave (lung, bowel, ear). Secondary: flying debris. Tertiary: body thrown into objects. Quaternary: burns, crush, exacerbation of chronic illness."
    },
    {
      "id": "ch-27.fc.07",
      "q": "What are the golden principles of trauma care?",
      "a": "Scene safety, rapid assessment, control life threats, limit on-scene time, transport to appropriate facility, and reassess continuously en route."
    },
    {
      "id": "ch-27.fc.08",
      "q": "How does blunt trauma differ from penetrating trauma in energy transfer?",
      "a": "Blunt: energy dispersed over a larger area — compression, deceleration, shear. Penetrating: energy concentrated along the wound tract with cavitation damage."
    }
  ],
  "notes": [
    {
      "id": "ch-27.n.01",
      "title": "Kinetics & Mechanism of Injury (Obj 27-2, 27-3)",
      "body": "Kinetics is the science of motion — understanding how energy transfers during trauma lets you predict injuries before exam findings. Kinetic energy = ½ × mass × velocity². Blunt trauma disperses energy over a broad area (MVC, falls). Penetrating trauma concentrates energy along a tract (GSW, stabbing) with additional cavitation. Higher velocity means exponentially more energy and worse injury.",
      "terms": [
        "Kinetics",
        "Kinetic energy",
        "Blunt trauma",
        "Penetrating trauma",
        "Cavitation",
        "Velocity"
      ]
    },
    {
      "id": "ch-27.n.02",
      "title": "MVC Patterns & High-Index Situations (Obj 27-5, 27-6)",
      "body": "High index of suspicion when: high-speed crash, significant vehicle damage, unrestrained or ejected occupants, rollover, intrusion into passenger space, or death of another occupant. Impact type predicts injury: frontal (femur, chest, head), lateral (thorax/head on struck side), rear (c-spine), rotational (multi-system). Restraints save lives but cause characteristic injuries — seat belt sign, sternal fracture, hollow viscus injury, and cervical spine injury.",
      "terms": [
        "Index of suspicion",
        "Frontal impact",
        "Lateral impact",
        "Seat belt sign",
        "Ejection",
        "Intrusion"
      ]
    },
    {
      "id": "ch-27.n.03",
      "title": "Blast Injuries & Golden Principles (Obj 27-10, 27-14)",
      "body": "Blast phases: primary (pressure wave — tympanic membrane rupture, pulmonary contusion, hollow viscus injury), secondary (fragmentation/debris), tertiary (patient thrown), quaternary (burns, crush, worsening chronic disease). Golden principles: ensure scene safety, perform rapid trauma assessment, address life threats immediately, minimize on-scene time, transport to the appropriate trauma center, and reassess continuously during transport.",
      "terms": [
        "Primary blast",
        "Secondary blast",
        "Tertiary blast",
        "Quaternary blast",
        "Golden principles",
        "Trauma center"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-27.q.01",
      "q": "Kinetics helps EMTs by:",
      "opts": [
        "A. Determining hospital billing codes",
        "B. Predicting injury patterns based on mechanism of injury",
        "C. Replacing the need for physical exam",
        "D. Calculating drug dosages"
      ],
      "ans": 1,
      "exp": "Understanding energy transfer and motion during trauma allows prediction of likely injuries from the mechanism before full assessment.",
      "easy": {
        "q": "Why is understanding kinetics important in trauma care?",
        "opts": [
          "A. Predicting injury patterns based on mechanism of injury",
          "B. Calculating drug dosages"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Kinetics helps EMTs by?",
        "opts": [
          "A. Replacing the need for physical exam",
          "B. Determining hospital billing codes",
          "C. Predicting injury patterns based on mechanism of injury",
          "D. Calculating drug dosages"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.02",
      "q": "Doubling the speed of a vehicle in a crash:",
      "opts": [
        "A. Doubles the kinetic energy",
        "B. Quadruples the kinetic energy",
        "C. Has no effect on kinetic energy",
        "D. Halves the kinetic energy"
      ],
      "ans": 1,
      "exp": "Kinetic energy = ½mv² — velocity is squared, so doubling speed quadruples the energy transferred.",
      "easy": {
        "q": "What is kinetic energy and how does velocity affect it?",
        "opts": [
          "A. Quadruples the kinetic energy",
          "B. Halves the kinetic energy"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: High index of suspicion when: high-speed crash, significant vehicle damage, unrestrained or ejected occupants, rollover, intrusion into passenger space, or death of another occupant. Based on this presentation, doubling the speed of a vehicle in a crash?",
        "opts": [
          "A. Has no effect on kinetic energy",
          "B. Doubles the kinetic energy",
          "C. Quadruples the kinetic energy",
          "D. Halves the kinetic energy"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.03",
      "q": "Which MVC scenario warrants highest index of suspicion for critical injury?",
      "opts": [
        "A. Low-speed fender bender with no damage",
        "B. High-speed crash with passenger compartment intrusion",
        "C. Parking lot scrape",
        "D. Minor bumper damage at 5 mph"
      ],
      "ans": 1,
      "exp": "High-speed impact with intrusion into the passenger compartment indicates massive energy transfer and high risk of serious injury.",
      "easy": {
        "q": "When should you have a high index of suspicion in an MVC?",
        "opts": [
          "A. High-speed crash with passenger compartment intrusion",
          "B. Parking lot scrape"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: High index of suspicion when: high-speed crash, significant vehicle damage, unrestrained or ejected occupants, rollover, intrusion into passenger space, or death of another occupant. Based on this presentation, which MVC scenario warrants highest index of suspicion for critical injury??",
        "opts": [
          "A. Low-speed fender bender with no damage",
          "B. Minor bumper damage at 5 mph",
          "C. High-speed crash with passenger compartment intrusion",
          "D. Parking lot scrape"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.04",
      "q": "A seat belt sign (diagonal bruising across the chest) suggests:",
      "opts": [
        "A. No internal injury possible",
        "B. Potential internal injuries including sternal fracture and hollow viscus injury",
        "C. Only superficial skin injury",
        "D. The patient was unrestrained"
      ],
      "ans": 1,
      "exp": "Seat belt sign indicates significant deceleration force — suspect sternal fracture, mesenteric injury, and spinal injury despite restraint.",
      "easy": {
        "q": "What restraint-related injuries should you suspect?",
        "opts": [
          "A. Potential internal injuries including sternal fracture and hollow viscus injury",
          "B. No internal injury possible"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: High index of suspicion when: high-speed crash, significant vehicle damage, unrestrained or ejected occupants, rollover, intrusion into passenger space, or death of another occupant. Based on this presentation, a seat belt sign (diagonal bruising across the chest) suggests?",
        "opts": [
          "A. Only superficial skin injury",
          "B. The patient was unrestrained",
          "C. Potential internal injuries including sternal fracture and hollow viscus injury",
          "D. No internal injury possible"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.05",
      "q": "Primary blast injury is caused by:",
      "opts": [
        "A. Flying debris striking the patient",
        "B. The pressure wave from the explosion",
        "C. The patient being thrown against a wall",
        "D. Burns from the blast"
      ],
      "ans": 1,
      "exp": "Primary blast injury results from the over-pressurization wave — affects air-filled organs (lungs, bowel, ears).",
      "easy": {
        "q": "What are the phases of blast injury?",
        "opts": [
          "A. The pressure wave from the explosion",
          "B. Burns from the blast"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Blast phases: primary (pressure wave. Based on this presentation, primary blast injury is caused by?",
        "opts": [
          "A. The patient being thrown against a wall",
          "B. Flying debris striking the patient",
          "C. The pressure wave from the explosion",
          "D. Burns from the blast"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.06",
      "q": "A golden principle of trauma care is:",
      "opts": [
        "A. Complete all interventions on scene before transport",
        "B. Minimize on-scene time and transport rapidly to appropriate facility",
        "C. Wait for ALS before any treatment",
        "D. Backboard all patients regardless of mechanism"
      ],
      "ans": 1,
      "exp": "Limit on-scene time, address life threats, and transport to the appropriate trauma center — definitive care is surgical.",
      "easy": {
        "q": "What are the golden principles of trauma care?",
        "opts": [
          "A. Minimize on-scene time and transport rapidly to appropriate facility",
          "B. Wait for ALS before any treatment"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Blast phases: primary (pressure wave. Based on this presentation, a golden principle of trauma care is?",
        "opts": [
          "A. Complete all interventions on scene before transport",
          "B. Backboard all patients regardless of mechanism",
          "C. Minimize on-scene time and transport rapidly to appropriate facility",
          "D. Wait for ALS before any treatment"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.07",
      "q": "Penetrating trauma differs from blunt trauma because:",
      "opts": [
        "A. It never causes internal injury",
        "B. Energy is concentrated along the wound tract",
        "C. It always causes less damage",
        "D. It only affects skin and subcutaneous tissue"
      ],
      "ans": 1,
      "exp": "Penetrating trauma focuses energy along the wound path, causing direct tissue damage and cavitation in surrounding tissue.",
      "easy": {
        "q": "How does blunt trauma differ from penetrating trauma in energy transfer?",
        "opts": [
          "A. Energy is concentrated along the wound tract",
          "B. It always causes less damage"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Kinetics is the science of motion. Based on this presentation, penetrating trauma differs from blunt trauma because?",
        "opts": [
          "A. It only affects skin and subcutaneous tissue",
          "B. It never causes internal injury",
          "C. Energy is concentrated along the wound tract",
          "D. It always causes less damage"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-27.q.08",
      "q": "Tertiary blast injury results from:",
      "opts": [
        "A. The pressure wave",
        "B. Flying shrapnel",
        "C. The patient being thrown into objects",
        "D. Chemical exposure from the blast"
      ],
      "ans": 2,
      "exp": "Tertiary blast injury occurs when the patient's body is hurled by the blast wind into walls, vehicles, or the ground.",
      "easy": {
        "q": "What are the phases of blast injury?",
        "opts": [
          "A. The patient being thrown into objects",
          "B. Flying shrapnel"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Blast phases: primary (pressure wave. Based on this presentation, tertiary blast injury results from?",
        "opts": [
          "A. Chemical exposure from the blast",
          "B. The pressure wave",
          "C. The patient being thrown into objects",
          "D. Flying shrapnel"
        ],
        "ans": 2
      }
    }
  ]
};
