// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch21: Chapter = {
  "id": "ch-21",
  "number": 21,
  "partId": "part-09",
  "title": "Allergic & Anaphylactic Reactions",
  "cards": [
    {
      "id": "ch-21.fc.01",
      "q": "What is anaphylaxis?",
      "a": "A severe, life-threatening allergic reaction involving multiple body systems — airway edema, vasodilation, and cardiovascular collapse."
    },
    {
      "id": "ch-21.fc.02",
      "q": "What is the first-line treatment for anaphylaxis?",
      "a": "Epinephrine IM (auto-injector, 0.3 mg adult / 0.15 mg pediatric) into the outer thigh — immediately."
    },
    {
      "id": "ch-21.fc.03",
      "q": "What are signs of anaphylaxis?",
      "a": "Urticaria (hives), angioedema, bronchospasm (wheezing), stridor, hypotension, tachycardia, nausea, altered LOC."
    },
    {
      "id": "ch-21.fc.04",
      "q": "Where is the epinephrine auto-injector administered?",
      "a": "Outer mid-thigh — can be given through clothing. Hold firmly against thigh for 10 seconds."
    },
    {
      "id": "ch-21.fc.05",
      "q": "Why is epinephrine effective in anaphylaxis?",
      "a": "Epinephrine reverses bronchospasm (beta-2), causes vasoconstriction (alpha-1), and increases heart rate (beta-1)."
    },
    {
      "id": "ch-21.fc.06",
      "q": "What is the difference between a mild allergic reaction and anaphylaxis?",
      "a": "Mild: localized hives, itching, mild swelling. Anaphylaxis: systemic with airway involvement, hypotension, or multi-system compromise."
    },
    {
      "id": "ch-21.fc.07",
      "q": "Can a second dose of epinephrine be given?",
      "a": "Yes — if symptoms don't improve after 5-15 minutes and a second auto-injector is available, per medical direction."
    },
    {
      "id": "ch-21.fc.08",
      "q": "Common triggers for anaphylaxis?",
      "a": "Bee/wasp stings, peanuts/tree nuts, shellfish, latex, medications (penicillin, aspirin, NSAIDs)."
    }
  ],
  "notes": [
    {
      "id": "ch-21.n.01",
      "title": "Anaphylaxis Pathophysiology",
      "body": "Massive release of histamine from mast cells causes systemic vasodilation (distributive shock), increased capillary permeability (edema), and bronchospasm. Airway edema can progress rapidly — early epinephrine is life-saving. Do not delay for antihistamines.",
      "terms": [
        "Histamine",
        "Mast cells",
        "Vasodilation",
        "Bronchospasm",
        "Angioedema"
      ]
    },
    {
      "id": "ch-21.n.02",
      "title": "Epinephrine Auto-Injector Use",
      "body": "Confirm patient's prescription or agency stock. Outer thigh IM injection — can go through clothing. Hold 10 seconds. Massage site to improve absorption. Monitor for response and side effects: tachycardia, hypertension, headache. Repeat in 5-15 minutes if no improvement.",
      "terms": [
        "Epinephrine",
        "Auto-injector",
        "Outer thigh",
        "IM injection",
        "Second dose"
      ]
    },
    {
      "id": "ch-21.n.03",
      "title": "Management of Allergic Reactions",
      "body": "Mild reactions (local hives, itching only): monitor, consider diphenhydramine (if authorized). Anaphylaxis: epinephrine FIRST — always. Then high-flow O2, position of comfort (upright if respiratory distress, supine if hypotensive), rapid transport, reassess frequently.",
      "terms": [
        "Diphenhydramine",
        "Epinephrine first",
        "Position",
        "High-flow O2",
        "Rapid transport"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-21.q.01",
      "q": "First-line treatment for anaphylaxis is:",
      "opts": [
        "A. Diphenhydramine (Benadryl)",
        "B. Albuterol inhaler",
        "C. Epinephrine IM",
        "D. Corticosteroids"
      ],
      "ans": 2,
      "exp": "Epinephrine IM is the only life-saving first-line treatment for anaphylaxis. Antihistamines and steroids are adjuncts only.",
      "level1": {
        "q": "What is the first-line treatment for anaphylaxis?",
        "opts": [
          "A. Epinephrine IM",
          "B. Corticosteroids"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-21.q.02",
      "q": "Epinephrine auto-injector is given in the:",
      "opts": [
        "A. Deltoid (shoulder)",
        "B. Gluteus (buttock)",
        "C. Outer mid-thigh",
        "D. Inner forearm"
      ],
      "ans": 2,
      "exp": "The outer mid-thigh is the correct site — good muscle mass, can be given through clothing, and is easily accessible.",
      "level1": {
        "q": "Where is the epinephrine auto-injector administered?",
        "opts": [
          "A. Outer mid-thigh",
          "B. Inner forearm"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-21.q.03",
      "q": "Which finding distinguishes anaphylaxis from mild allergic reaction?",
      "opts": [
        "A. Localized hives only",
        "B. Mild itching",
        "C. Airway involvement, hypotension, or multi-system compromise",
        "D. Red eyes"
      ],
      "ans": 2,
      "exp": "Anaphylaxis involves systemic compromise — airway edema, bronchospasm, hypotension, or multi-organ involvement.",
      "level1": {
        "q": "What is the difference between a mild allergic reaction and anaphylaxis?",
        "opts": [
          "A. Airway involvement, hypotension, or multi-system compromise",
          "B. Red eyes"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-21.q.04",
      "q": "Epinephrine reverses anaphylaxis by:",
      "opts": [
        "A. Blocking histamine receptors",
        "B. Causing bronchospasm and vasodilation",
        "C. Causing bronchodilation, vasoconstriction, and increased HR",
        "D. Reducing inflammation"
      ],
      "ans": 2,
      "exp": "Epinephrine's alpha-1 (vasoconstriction), beta-1 (increased HR/contractility), and beta-2 (bronchodilation) effects counteract anaphylaxis.",
      "level1": {
        "q": "Why is epinephrine effective in anaphylaxis?",
        "opts": [
          "A. Causing bronchodilation, vasoconstriction, and increased HR",
          "B. Reducing inflammation"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-21.q.05",
      "q": "A second epinephrine dose may be given if:",
      "opts": [
        "A. The patient is still breathing",
        "B. Symptoms don't improve after 5-15 minutes and a second injector is available",
        "C. Always given 2 minutes after first",
        "D. Only at the hospital"
      ],
      "ans": 1,
      "exp": "If symptoms don't resolve after 5-15 minutes and a second auto-injector is available, a repeat dose may be given per protocol.",
      "level1": {
        "q": "Can a second dose of epinephrine be given?",
        "opts": [
          "A. Symptoms don't improve after 5-15 minutes and a second injector is available",
          "B. Only at the hospital"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-21.q.06",
      "q": "Common triggers for anaphylaxis include:",
      "opts": [
        "A. Cold temperatures only",
        "B. Exercise only",
        "C. Bee stings, peanuts, shellfish, latex, medications",
        "D. Stress and anxiety"
      ],
      "ans": 2,
      "exp": "Classic anaphylaxis triggers: insect stings, peanuts/tree nuts, shellfish, latex, and medications like penicillin.",
      "level1": {
        "q": "Common triggers for anaphylaxis?",
        "opts": [
          "A. Bee stings, peanuts, shellfish, latex, medications",
          "B. Exercise only"
        ],
        "ans": 0
      }
    }
  ]
};
