// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch22: Chapter = {
  "id": "ch-22",
  "number": 22,
  "partId": "part-09",
  "title": "Toxicologic Emergencies",
  "cards": [
    {
      "id": "ch-22.fc.01",
      "q": "What is activated charcoal and when is it used?",
      "a": "A substance that binds to certain ingested toxins in the GI tract — given for some oral overdoses within 1-2 hours if patient is alert with intact airway."
    },
    {
      "id": "ch-22.fc.02",
      "q": "What is naloxone (Narcan) and what does it treat?",
      "a": "An opioid antagonist that reverses opioid-induced respiratory depression — given IM or IN for opioid overdose."
    },
    {
      "id": "ch-22.fc.03",
      "q": "What are signs of opioid overdose?",
      "a": "Pinpoint pupils (miosis), respiratory depression, decreased LOC — the 'opioid triad.'"
    },
    {
      "id": "ch-22.fc.04",
      "q": "What are signs of stimulant overdose?",
      "a": "Agitation, tachycardia, hypertension, dilated pupils (mydriasis), hyperthermia, possible seizures."
    },
    {
      "id": "ch-22.fc.05",
      "q": "What is SLUDGEM?",
      "a": "Salivation, Lacrimation, Urination, Defecation, GI distress, Emesis, Miosis — signs of cholinergic toxidrome (nerve agents, organophosphates)."
    },
    {
      "id": "ch-22.fc.06",
      "q": "What are signs of carbon monoxide poisoning?",
      "a": "Headache, dizziness, nausea, confusion, weakness — SpO2 may appear normal (standard pulse ox cannot detect CO poisoning)."
    },
    {
      "id": "ch-22.fc.07",
      "q": "What is a toxidrome?",
      "a": "A cluster of signs and symptoms characteristic of poisoning by a specific class of substance."
    },
    {
      "id": "ch-22.fc.08",
      "q": "What should you do at a scene with suspected carbon monoxide?",
      "a": "Remove patient to fresh air immediately, apply high-flow O2, contact hazmat if source not identified, do not re-enter."
    }
  ],
  "notes": [
    {
      "id": "ch-22.n.01",
      "title": "Toxicologic Assessment",
      "body": "Identify the substance, amount, route, and time of exposure. Contact Poison Control (1-800-222-1222). Recognize toxidromes — specific symptom patterns that identify the drug class. Manage ABCs first, then specific antidotes if available. Scene safety is critical.",
      "terms": [
        "Toxidrome",
        "Poison Control",
        "SLUDGEM",
        "Antidote",
        "Route of exposure"
      ]
    },
    {
      "id": "ch-22.n.02",
      "title": "Common Drug Overdoses",
      "body": "Opioids: pinpoint pupils, respiratory depression, LOC — treat with naloxone. Stimulants: dilated pupils, tachycardia, hyperthermia. Benzodiazepines: sedation, respiratory depression (milder than opioids). Tricyclics: cardiac arrhythmias, seizures, hypotension — very dangerous.",
      "terms": [
        "Opioid triad",
        "Naloxone",
        "Miosis",
        "Mydriasis",
        "Benzodiazepine"
      ]
    },
    {
      "id": "ch-22.n.03",
      "title": "Carbon Monoxide & Inhalation Emergencies",
      "body": "CO is colorless, odorless — detected by CO detector or patient cluster complaints. CO displaces O2 on hemoglobin. Standard pulse oximetry CANNOT distinguish carboxyhemoglobin — CO poisoning can show normal SpO2 despite life-threatening poisoning. Treat with 100% O2.",
      "terms": [
        "Carbon monoxide",
        "Carboxyhemoglobin",
        "CO-oximetry",
        "High-flow oxygen",
        "Scene safety"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-22.q.01",
      "q": "Classic signs of opioid overdose include:",
      "opts": [
        "A. Dilated pupils, hypertension",
        "B. Pinpoint pupils, respiratory depression, decreased LOC",
        "C. Agitation, tachycardia",
        "D. SLUDGEM symptoms"
      ],
      "ans": 1,
      "exp": "Opioid triad: miosis (pinpoint pupils), respiratory depression, and decreased level of consciousness.",
      "level1": {
        "q": "What are signs of opioid overdose?",
        "opts": [
          "A. Pinpoint pupils, respiratory depression, decreased LOC",
          "B. SLUDGEM symptoms"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-22.q.02",
      "q": "Naloxone (Narcan) is used to treat:",
      "opts": [
        "A. Stimulant overdose",
        "B. Benzodiazepine overdose",
        "C. Opioid-induced respiratory depression",
        "D. Carbon monoxide poisoning"
      ],
      "ans": 2,
      "exp": "Naloxone is an opioid receptor antagonist that rapidly reverses opioid-induced respiratory depression. Monitor for re-sedation.",
      "level1": {
        "q": "What is naloxone (Narcan) and what does it treat?",
        "opts": [
          "A. Opioid-induced respiratory depression",
          "B. Stimulant overdose"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-22.q.03",
      "q": "SLUDGEM is associated with what toxidrome?",
      "opts": [
        "A. Opioid overdose",
        "B. Stimulant overdose",
        "C. Cholinergic toxidrome (organophosphates/nerve agents)",
        "D. Anticholinergic toxidrome"
      ],
      "ans": 2,
      "exp": "SLUDGEM is the cholinergic toxidrome — classic for organophosphate pesticides and nerve agents.",
      "level1": {
        "q": "What is SLUDGEM?",
        "opts": [
          "A. Cholinergic toxidrome (organophosphates/nerve agents)",
          "B. Opioid overdose"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-22.q.04",
      "q": "Carbon monoxide poisoning may show normal SpO2 because:",
      "opts": [
        "A. CO increases oxygen saturation",
        "B. Standard pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin",
        "C. CO increases respiratory rate",
        "D. The patient is hyperventilating"
      ],
      "ans": 1,
      "exp": "Standard pulse oximetry reads carboxyhemoglobin as oxygenated hemoglobin — CO poisoning can appear normal despite life-threatening poisoning.",
      "level1": {
        "q": "What are signs of carbon monoxide poisoning?",
        "opts": [
          "A. Standard pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin",
          "B. CO increases respiratory rate"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-22.q.05",
      "q": "First action at a suspected CO poisoning scene:",
      "opts": [
        "A. Administer CPR",
        "B. Remove patient to fresh air immediately",
        "C. Apply oxygen before moving",
        "D. Call poison control before moving"
      ],
      "ans": 1,
      "exp": "Scene safety first — remove patient and yourself from the CO source immediately. Apply high-flow O2 once in fresh air.",
      "level1": {
        "q": "What should you do at a scene with suspected carbon monoxide?",
        "opts": [
          "A. Remove patient to fresh air immediately",
          "B. Administer CPR"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-22.q.06",
      "q": "Activated charcoal works by:",
      "opts": [
        "A. Neutralizing stomach acid",
        "B. Inducing vomiting",
        "C. Binding toxins in the GI tract to reduce absorption",
        "D. Speeding drug metabolism"
      ],
      "ans": 2,
      "exp": "Activated charcoal adsorbs (binds) certain toxins in the GI tract, preventing absorption into the bloodstream. Only used in alert patients with intact airway.",
      "level1": {
        "q": "What is activated charcoal and when is it used?",
        "opts": [
          "A. Binding toxins in the GI tract to reduce absorption",
          "B. Inducing vomiting"
        ],
        "ans": 0
      }
    }
  ]
};
