// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch29: Chapter = {
  "id": "ch-29",
  "number": 29,
  "partId": "part-10",
  "title": "Burns",
  "cards": [
    {
      "id": "ch-29.fc.01",
      "q": "What are the three depths of burns?",
      "a": "Superficial (1st degree): epidermis only — red, painful. Partial thickness (2nd degree): epidermis and dermis — blisters, very painful. Full thickness (3rd degree): all skin layers — leathery, white/charred, painless."
    },
    {
      "id": "ch-29.fc.02",
      "q": "What is the Rule of Nines for adults?",
      "a": "Head/neck 9%, each arm 9%, chest 9%, abdomen 9%, upper back 9%, lower back 9%, each thigh 9%, each lower leg 9%, genitalia 1% = 100%."
    },
    {
      "id": "ch-29.fc.03",
      "q": "What makes a burn 'critical'?",
      "a": "Burns >30% BSA, full-thickness burns >10% BSA, burns to face/hands/feet/genitalia/major joints, circumferential burns, inhalation injury, or associated trauma."
    },
    {
      "id": "ch-29.fc.04",
      "q": "How should burns be cooled?",
      "a": "Room temperature water for 10-20 minutes — never ice (causes vasoconstriction/frostbite). Cool only small burns; large burns risk hypothermia."
    },
    {
      "id": "ch-29.fc.05",
      "q": "What are signs of inhalation injury?",
      "a": "Singed nasal hairs/eyebrows, soot around mouth/nose, hoarse voice, stridor, carbonaceous sputum, and facial burns."
    },
    {
      "id": "ch-29.fc.06",
      "q": "What should NOT be applied to burns?",
      "a": "Ice (causes vasoconstriction and frostbite), butter/toothpaste/home remedies (infection risk), tight bandages over circumferential burns."
    },
    {
      "id": "ch-29.fc.07",
      "q": "How is the Rule of Nines modified for children?",
      "a": "Children have proportionally larger heads (18%) and smaller legs — use the Lund-Browder chart for accurate pediatric burn estimation."
    },
    {
      "id": "ch-29.fc.08",
      "q": "What is the primary concern with circumferential burns?",
      "a": "Circumferential burns on extremities can act as a tourniquet — compromising circulation as swelling develops. On the chest, they restrict breathing."
    }
  ],
  "notes": [
    {
      "id": "ch-29.n.01",
      "title": "Burn Depth & Classification",
      "body": "Superficial (1st degree): red, dry, painful — no blister (sunburn). Partial thickness (2nd degree): blisters, wet, intensely painful — involves dermis. Full thickness (3rd degree): all skin layers destroyed, painless (nerve damage), white/leathery/charred. 4th degree involves underlying structures (muscle, bone).",
      "terms": [
        "Superficial",
        "Partial thickness",
        "Full thickness",
        "Blister",
        "Eschar"
      ]
    },
    {
      "id": "ch-29.n.02",
      "title": "Burn Size & Critical Burns",
      "body": "Rule of Nines estimates total body surface area (TBSA) burned. Critical burns: >30% TBSA, full thickness >10%, face/hands/feet/genitalia, circumferential, inhalation injury, or associated trauma. These require burn center transport. Small burns only: cool with room temp water.",
      "terms": [
        "Rule of Nines",
        "TBSA",
        "Critical burn",
        "Burn center",
        "Circumferential"
      ]
    },
    {
      "id": "ch-29.n.03",
      "title": "Burn Field Management",
      "body": "Stop burning: remove clothing/jewelry (if not stuck). Cool: room temp water for 10-20 min on small burns only. Cover: dry sterile dressings. Prevent heat loss: burn patients lose heat rapidly — keep warm after cooling. Airway priority: inhalation injury can close airway rapidly.",
      "terms": [
        "Stop-cool-cover",
        "Sterile dressing",
        "Hypothermia prevention",
        "Inhalation injury",
        "Airway edema"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-29.q.01",
      "q": "A partial thickness (2nd degree) burn is characterized by:",
      "opts": [
        "A. Dry, red skin only",
        "B. Blisters, wet surface, intense pain",
        "C. White leathery appearance, painless",
        "D. Charred black tissue"
      ],
      "ans": 1,
      "exp": "Partial thickness burns involve epidermis and dermis — blisters, wet/weeping surface, and intense pain are hallmarks."
    },
    {
      "id": "ch-29.q.02",
      "q": "Using the Rule of Nines, each arm accounts for what percentage?",
      "opts": [
        "A. 4.5%",
        "B. 9%",
        "C. 18%",
        "D. 13%"
      ],
      "ans": 1,
      "exp": "Each arm = 9% of body surface area in the adult Rule of Nines."
    },
    {
      "id": "ch-29.q.03",
      "q": "What should NEVER be applied to a burn?",
      "opts": [
        "A. Sterile dry dressing",
        "B. Room temperature water",
        "C. Ice or ice water",
        "D. Loose gauze"
      ],
      "ans": 2,
      "exp": "Ice causes vasoconstriction, worsens tissue damage, and can cause frostbite on burned tissue. Use room temperature water only."
    },
    {
      "id": "ch-29.q.04",
      "q": "Signs of inhalation injury include:",
      "opts": [
        "A. Rash on chest",
        "B. Singed nasal hairs, soot around mouth, hoarse voice",
        "C. Normal voice with facial burns",
        "D. Blistering on upper arms only"
      ],
      "ans": 1,
      "exp": "Inhalation injury signs: singed nasal/facial hair, soot, hoarseness, stridor, carbonaceous sputum — airway edema may develop rapidly."
    },
    {
      "id": "ch-29.q.05",
      "q": "A critical burn includes burns to:",
      "opts": [
        "A. Only the back >5%",
        "B. Face, hands, feet, genitalia, or with inhalation injury",
        "C. The shoulder area only",
        "D. Less than 10% TBSA if full thickness"
      ],
      "ans": 1,
      "exp": "Burns to functional/sensitive areas (face, hands, feet, genitalia, circumferential) and inhalation injuries are automatically critical."
    },
    {
      "id": "ch-29.q.06",
      "q": "The Rule of Nines for children differs because:",
      "opts": [
        "A. Children have smaller torsos",
        "B. Children have proportionally larger heads (18%) and smaller legs",
        "C. The rule is identical for all ages",
        "D. Children always have more severe burns"
      ],
      "ans": 1,
      "exp": "Children have larger heads (18%) and smaller legs — the Lund-Browder chart corrects for age-related body proportion differences."
    }
  ]
};
