// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch28: Chapter = {
  "id": "ch-28",
  "number": 28,
  "partId": "part-10",
  "title": "Bleeding & Soft Tissue Trauma",
  "cards": [
    {
      "id": "ch-28.fc.01",
      "q": "What are the three types of external bleeding by vessel?",
      "a": "Arterial: bright red, spurting. Venous: dark red, steady flow. Capillary: slow oozing, usually self-limiting."
    },
    {
      "id": "ch-28.fc.02",
      "q": "What is the progressive approach to controlling external bleeding?",
      "a": "Direct pressure first → pressure dressing → hemostatic agents/wound packing → tourniquet (extremity) → splinting fractured extremities to reduce bleeding."
    },
    {
      "id": "ch-28.fc.03",
      "q": "Why is bleeding from the nose, ears, or mouth of special concern?",
      "a": "May indicate skull fracture or basilar skull fracture — do not pack ears/nose; allow drainage. Mouth bleeding risks airway obstruction."
    },
    {
      "id": "ch-28.fc.04",
      "q": "What are types of internal bleeding and their care?",
      "a": "Hemothorax, hemoperitoneum, retroperitoneal bleed — no field control of bleeding; maintain airway/O2, treat shock, rapid transport."
    },
    {
      "id": "ch-28.fc.05",
      "q": "How do you manage soft-tissue trauma to the head, face, neck, and scalp?",
      "a": "Scalp bleeds heavily — direct pressure. Face: protect airway. Neck: occlusive dressing to prevent air embolism. Control bleeding without compromising airway."
    },
    {
      "id": "ch-28.fc.06",
      "q": "What are special considerations for impaled objects and amputations?",
      "a": "Impaled: stabilize in place, do not remove. Amputation: tourniquet on stump, wrap amputated part in moist dressing in sealed bag on ice (not directly on ice)."
    },
    {
      "id": "ch-28.fc.07",
      "q": "What is the purpose of different dressings and bandages?",
      "a": "Dressings cover wounds and absorb blood. Bandages secure dressings and maintain pressure. Occlusive dressings seal wounds to prevent air entry (chest, neck)."
    },
    {
      "id": "ch-28.fc.08",
      "q": "What is the assessment-based approach to bleeding and soft-tissue trauma?",
      "a": "Scene size-up → primary survey (control major bleeding, airway) → secondary survey → form field impression → provide appropriate care and rapid transport."
    }
  ],
  "notes": [
    {
      "id": "ch-28.n.01",
      "title": "External Bleeding Control (Obj 28-2, 28-13)",
      "body": "Progressive hemorrhage control: (1) direct pressure with gloved hand and dressing, (2) pressure dressing, (3) hemostatic agents and wound packing for junctional wounds, (4) tourniquet for life-threatening extremity bleeding uncontrolled by pressure, (5) splint fractures to reduce bone-end bleeding. Dressings protect the wound; bandages secure dressings and maintain pressure. Never remove a blood-soaked dressing — add more on top.",
      "terms": [
        "Direct pressure",
        "Tourniquet",
        "Hemostatic agent",
        "Wound packing",
        "Pressure dressing",
        "Occlusive dressing"
      ]
    },
    {
      "id": "ch-28.n.02",
      "title": "Assessment & Special Bleeding Sites (Obj 28-3, 28-4, 28-8)",
      "body": "Use the assessment-based approach: primary survey identifies life-threatening bleeding and airway compromise; secondary survey finds all injuries. Nose/ear/mouth bleeding may signal basilar skull fracture — do not pack ears or nose; loosely cover draining ear. Internal bleeding (abdomen, chest, retroperitoneum) cannot be controlled in the field — recognize shock signs, give O2, and transport rapidly.",
      "terms": [
        "Field impression",
        "Basilar skull fracture",
        "Internal bleeding",
        "Hemothorax",
        "Hemoperitoneum",
        "Primary survey"
      ]
    },
    {
      "id": "ch-28.n.03",
      "title": "Soft Tissue & Special Wounds (Obj 28-9, 28-11)",
      "body": "Scalp wounds bleed profusely due to rich vascular supply — direct pressure. Facial wounds: prioritize airway. Neck wounds: occlusive dressing immediately (air embolism risk). Chest open wounds: three-sided occlusive dressing. Abdominal evisceration: moist sterile dressing, do not push organs back. Impaled objects: stabilize in place. Amputations: control stump bleeding, preserve amputated part in moist cool environment.",
      "terms": [
        "Scalp hemorrhage",
        "Occlusive dressing",
        "Evisceration",
        "Impaled object",
        "Amputation",
        "Sucking chest wound"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-28.q.01",
      "q": "First-line treatment for external bleeding is:",
      "opts": [
        "A. Tourniquet application",
        "B. Direct continuous pressure",
        "C. Elevation alone",
        "D. Pressure points"
      ],
      "ans": 1,
      "exp": "Direct pressure is always first-line. Escalate to hemostatic agents, wound packing, or tourniquet only if direct pressure fails.",
      "level1": {
        "q": "What is the progressive approach to controlling external bleeding?",
        "opts": [
          "A. Direct continuous pressure",
          "B. Elevation alone"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.02",
      "q": "Blood draining from the ear after head trauma suggests:",
      "opts": [
        "A. Minor ear infection",
        "B. Possible basilar skull fracture — do not pack the ear",
        "C. Need to irrigate the ear canal",
        "D. Cerumen impaction"
      ],
      "ans": 1,
      "exp": "Blood or CSF from the ear indicates basilar skull fracture — loosely cover with sterile dressing but do not pack or irrigate.",
      "level1": {
        "q": "Why is bleeding from the nose, ears, or mouth of special concern?",
        "opts": [
          "A. Possible basilar skull fracture — do not pack the ear",
          "B. Cerumen impaction"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.03",
      "q": "Internal abdominal bleeding in the field is managed by:",
      "opts": [
        "A. Attempting to stop the bleed surgically",
        "B. Recognizing shock, maintaining airway/O2, and rapid transport",
        "C. Oral fluid replacement",
        "D. Applying abdominal pressure bandages to stop all bleeding"
      ],
      "ans": 1,
      "exp": "Internal bleeding cannot be controlled in the prehospital setting — treat for shock and transport rapidly to surgical care.",
      "level1": {
        "q": "What are types of internal bleeding and their care?",
        "opts": [
          "A. Recognizing shock, maintaining airway/O2, and rapid transport",
          "B. Oral fluid replacement"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.04",
      "q": "An open wound to the neck requires:",
      "opts": [
        "A. Standard gauze only",
        "B. An occlusive dressing to prevent air embolism",
        "C. Tourniquet application",
        "D. Irrigation with saline"
      ],
      "ans": 1,
      "exp": "Jugular vein injury can allow air embolism — apply an occlusive (airtight) dressing immediately.",
      "level1": {
        "q": "How do you manage soft-tissue trauma to the head, face, neck, and scalp?",
        "opts": [
          "A. An occlusive dressing to prevent air embolism",
          "B. Standard gauze only"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.05",
      "q": "An impaled object in the abdomen should be:",
      "opts": [
        "A. Removed carefully to assess the wound",
        "B. Stabilized in place with bulky dressings",
        "C. Cut shorter then removed",
        "D. Pushed through to the other side"
      ],
      "ans": 1,
      "exp": "Never remove an impaled object — it may be tamponading bleeding. Stabilize in place and transport.",
      "level1": {
        "q": "What are special considerations for impaled objects and amputations?",
        "opts": [
          "A. Stabilized in place with bulky dressings",
          "B. Cut shorter then removed"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.06",
      "q": "A tourniquet is indicated when:",
      "opts": [
        "A. Any visible bleeding occurs",
        "B. Life-threatening extremity bleeding cannot be controlled with direct pressure",
        "C. The patient has a minor laceration",
        "D. Junctional neck bleeding occurs"
      ],
      "ans": 1,
      "exp": "Tourniquets are for life-threatening extremity hemorrhage uncontrolled by direct pressure — not for minor wounds or junctional bleeding.",
      "level1": {
        "q": "What is the progressive approach to controlling external bleeding?",
        "opts": [
          "A. Life-threatening extremity bleeding cannot be controlled with direct pressure",
          "B. Any visible bleeding occurs"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.07",
      "q": "When a dressing becomes soaked with blood, you should:",
      "opts": [
        "A. Remove and replace it",
        "B. Add more dressings on top without removing the original",
        "C. Irrigate the wound first",
        "D. Release all pressure to check the wound"
      ],
      "ans": 1,
      "exp": "Removing a soaked dressing may dislodge clots and restart bleeding — add more dressings and maintain pressure.",
      "level1": {
        "q": "What is When a dressing becomes soaked with blood, you should?",
        "opts": [
          "A. Add more dressings on top without removing the original",
          "B. Remove and replace it"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-28.q.08",
      "q": "Splinting a fractured extremity helps control bleeding by:",
      "opts": [
        "A. Increasing blood flow to the area",
        "B. Stabilizing bone ends to reduce tissue and vessel damage",
        "C. Replacing the need for direct pressure",
        "D. Eliminating the need for transport"
      ],
      "ans": 1,
      "exp": "Splinting immobilizes bone ends, reducing movement that disrupts clots and damages surrounding vessels and tissue.",
      "level1": {
        "q": "What is the progressive approach to controlling external bleeding?",
        "opts": [
          "A. Stabilizing bone ends to reduce tissue and vessel damage",
          "B. Increasing blood flow to the area"
        ],
        "ans": 0
      }
    }
  ]
};
