// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch23: Chapter = {
  "id": "ch-23",
  "number": 23,
  "partId": "part-09",
  "title": "Abdominal, Hematologic, GYN & Renal Emergencies",
  "cards": [
    {
      "id": "ch-23.fc.01",
      "q": "What are signs of an acute abdomen?",
      "a": "Severe abdominal pain, rigidity, guarding, rebound tenderness, nausea/vomiting, fever — may indicate internal organ emergency."
    },
    {
      "id": "ch-23.fc.02",
      "q": "What is rebound tenderness?",
      "a": "Pain that worsens when abdominal pressure is suddenly released — a sign of peritoneal irritation (peritonitis)."
    },
    {
      "id": "ch-23.fc.03",
      "q": "What are signs of a GI bleed?",
      "a": "Hematemesis (vomiting blood), melena (dark tarry stools), hematochezia (bright red rectal bleeding), signs of shock."
    },
    {
      "id": "ch-23.fc.04",
      "q": "What is sickle cell crisis?",
      "a": "A painful condition in sickle cell disease where sickled red blood cells occlude blood vessels — causes severe pain and organ damage."
    },
    {
      "id": "ch-23.fc.05",
      "q": "What are signs of kidney stones (renal calculi)?",
      "a": "Severe, colicky flank pain radiating to the groin, nausea/vomiting, hematuria (blood in urine) — patient cannot find a comfortable position."
    },
    {
      "id": "ch-23.fc.06",
      "q": "What is ectopic pregnancy?",
      "a": "Implantation of a fertilized egg outside the uterus (usually fallopian tube) — causes abdominal pain and vaginal bleeding; can rupture causing life-threatening hemorrhage."
    },
    {
      "id": "ch-23.fc.07",
      "q": "What is dialysis and what emergencies can occur?",
      "a": "A process that filters blood when kidneys fail. Emergencies: missed session (fluid overload, electrolyte imbalance), bleeding from access site, hypotension during dialysis."
    },
    {
      "id": "ch-23.fc.08",
      "q": "What is peritonitis?",
      "a": "Inflammation of the peritoneum from infection or organ rupture — causes diffuse abdominal pain, rigidity, and sepsis."
    }
  ],
  "notes": [
    {
      "id": "ch-23.n.01",
      "title": "Abdominal Emergencies",
      "body": "Abdominal pain can result from nearly any organ system. Use OPQRST to characterize pain. Signs of serious emergency: rigid abdomen, rebound tenderness, peritoneal signs, guarding. GI bleeds present with hematemesis, melena, or hematochezia plus signs of hypovolemic shock.",
      "terms": [
        "Acute abdomen",
        "Rebound tenderness",
        "Peritonitis",
        "GI bleed",
        "Guarding"
      ]
    },
    {
      "id": "ch-23.n.02",
      "title": "Genitourinary & Gynecological Emergencies",
      "body": "Kidney stones: severe colicky flank-to-groin pain, hematuria — supportive care and transport. Ectopic pregnancy: abdominal/pelvic pain + vaginal bleeding in early pregnancy — high shock risk. Assume pregnancy in any female of childbearing age with abdominal pain.",
      "terms": [
        "Renal calculi",
        "Hematuria",
        "Ectopic pregnancy",
        "Dialysis",
        "Pelvic pain"
      ]
    },
    {
      "id": "ch-23.n.03",
      "title": "Hematologic Emergencies",
      "body": "Sickle cell crisis: severe, diffuse pain from vessel occlusion by sickled cells — pain management, O2, hydration, transport. Hemophilia: severe bleeding from clotting factor deficiency — even minor trauma causes significant bleeding. Both require hospital management.",
      "terms": [
        "Sickle cell crisis",
        "Hemophilia",
        "Hematemesis",
        "Melena",
        "Hematochezia"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-23.q.01",
      "q": "Rebound tenderness indicates:",
      "opts": [
        "A. Muscle strain",
        "B. Peritoneal irritation or inflammation",
        "C. Kidney stones",
        "D. Normal finding"
      ],
      "ans": 1,
      "exp": "Rebound tenderness (pain worsening when abdominal pressure is suddenly released) indicates peritoneal irritation — appendicitis, peritonitis.",
      "level1": {
        "q": "What is rebound tenderness?",
        "opts": [
          "A. Peritoneal irritation or inflammation",
          "B. Muscle strain"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-23.q.02",
      "q": "Melena is described as:",
      "opts": [
        "A. Bright red blood in vomit",
        "B. Dark, tarry stools from upper GI bleeding",
        "C. Bright red rectal bleeding",
        "D. Blood in urine"
      ],
      "ans": 1,
      "exp": "Melena = dark, tarry, foul-smelling stools indicating upper GI bleeding where blood has been digested.",
      "level1": {
        "q": "What are signs of a GI bleed?",
        "opts": [
          "A. Dark, tarry stools from upper GI bleeding",
          "B. Blood in urine"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-23.q.03",
      "q": "Ectopic pregnancy is dangerous because:",
      "opts": [
        "A. It causes diabetes",
        "B. The fallopian tube can rupture causing life-threatening hemorrhage",
        "C. It requires immediate C-section",
        "D. It only causes mild pain"
      ],
      "ans": 1,
      "exp": "Ectopic pregnancy can rupture the fallopian tube causing massive internal hemorrhage and rapid cardiovascular collapse.",
      "level1": {
        "q": "What is ectopic pregnancy?",
        "opts": [
          "A. The fallopian tube can rupture causing life-threatening hemorrhage",
          "B. It causes diabetes"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-23.q.04",
      "q": "Classic presentation of kidney stones includes:",
      "opts": [
        "A. Steady dull flank pain",
        "B. Severe colicky flank pain radiating to groin, hematuria",
        "C. Abdominal rigidity with fever",
        "D. Painless hematuria only"
      ],
      "ans": 1,
      "exp": "Kidney stones: severe colicky (comes and goes) flank pain radiating to the groin, nausea, and hematuria — patient cannot find a comfortable position.",
      "level1": {
        "q": "What are signs of kidney stones (renal calculi)?",
        "opts": [
          "A. Severe colicky flank pain radiating to groin, hematuria",
          "B. Steady dull flank pain"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-23.q.05",
      "q": "Signs of upper GI bleeding include:",
      "opts": [
        "A. Hematochezia only",
        "B. Hematemesis and melena",
        "C. Hematuria and flank pain",
        "D. Normal stools with abdominal pain"
      ],
      "ans": 1,
      "exp": "Upper GI bleeding (esophagus, stomach, duodenum) produces hematemesis (blood vomiting) and melena (dark tarry stools).",
      "level1": {
        "q": "What are signs of a GI bleed?",
        "opts": [
          "A. Hematemesis and melena",
          "B. Hematochezia only"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-23.q.06",
      "q": "Sickle cell crisis causes pain by:",
      "opts": [
        "A. Infection spreading to bone",
        "B. Sickled cells occluding blood vessels",
        "C. Low blood glucose",
        "D. Kidney failure"
      ],
      "ans": 1,
      "exp": "Sickled red blood cells occlude small blood vessels, causing ischemia and severe pain in affected areas — bones, chest, abdomen.",
      "level1": {
        "q": "What is sickle cell crisis?",
        "opts": [
          "A. Sickled cells occluding blood vessels",
          "B. Kidney failure"
        ],
        "ans": 0
      }
    }
  ]
};
