// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch27: Chapter = {
  "id": "ch-27",
  "number": 27,
  "partId": "part-10",
  "title": "Trauma Overview & Trauma System",
  "cards": [
    {
      "id": "ch-27.fc.01",
      "q": "What is the leading cause of death in people ages 1-44?",
      "a": "Trauma — unintentional injury is the #1 killer of Americans under age 44."
    },
    {
      "id": "ch-27.fc.02",
      "q": "What is the Trauma System?",
      "a": "A coordinated network of trauma centers, EMS, rehabilitation, and prevention programs designed to optimize outcomes for injured patients."
    },
    {
      "id": "ch-27.fc.03",
      "q": "What is kinematics?",
      "a": "The science of motion — understanding forces, energy transfer, and mechanisms of injury to predict patterns of trauma."
    },
    {
      "id": "ch-27.fc.04",
      "q": "What is the index of suspicion in trauma?",
      "a": "The EMT's anticipation of specific injuries based on MOI, even before physical findings — guides more thorough assessment."
    },
    {
      "id": "ch-27.fc.05",
      "q": "What are the three collision events in a motor vehicle crash?",
      "a": "1) Vehicle hits object, 2) Occupant continues moving and hits vehicle interior, 3) Internal organs hit body structures."
    },
    {
      "id": "ch-27.fc.06",
      "q": "What is a Level I Trauma Center?",
      "a": "The highest level of trauma care — 24/7 surgical capability, highest volume of major trauma, research and education programs."
    },
    {
      "id": "ch-27.fc.07",
      "q": "What is the difference between blunt and penetrating trauma?",
      "a": "Blunt: compression and deceleration forces (MVC, falls). Penetrating: object enters body (gunshot, stabbing) — direct and surrounding tissue damage."
    },
    {
      "id": "ch-27.fc.08",
      "q": "What is 'load and go' vs 'stay and play'?",
      "a": "Load and go: critical trauma patients need rapid transport (Golden Hour). Stay and play: stable patients with isolated injuries may be treated on scene longer."
    }
  ],
  "notes": [
    {
      "id": "ch-27.n.01",
      "title": "Kinematics of Trauma",
      "body": "Energy cannot be created or destroyed — it transfers during trauma. Kinetic energy = 1/2 mass × velocity². Velocity has a squared effect — doubling speed quadruples energy. Understanding MOI allows prediction of injury patterns even before physical exam.",
      "terms": [
        "Kinematics",
        "Kinetic energy",
        "Velocity",
        "Energy transfer",
        "Deceleration"
      ]
    },
    {
      "id": "ch-27.n.02",
      "title": "The Trauma System",
      "body": "Trauma systems improve outcomes through: rapid EMS response, pre-hospital assessment/care, triage to appropriate facility, definitive surgical care, and rehabilitation. Trauma centers are categorized by capability (Level I-IV). EMTs must know local trauma center locations.",
      "terms": [
        "Trauma center",
        "Level I",
        "Golden Hour",
        "Triage",
        "Rehabilitation"
      ]
    },
    {
      "id": "ch-27.n.03",
      "title": "Blunt vs. Penetrating Trauma",
      "body": "Blunt trauma: energy dispersed over larger area — compression, deceleration, shear forces. MVC, falls, assaults. Penetrating trauma: energy concentrated along wound tract — gunshot wounds, stabs. Secondary fragmentation (bullets) causes additional injury beyond the tract.",
      "terms": [
        "Blunt trauma",
        "Penetrating trauma",
        "Compression",
        "Deceleration",
        "Fragmentation"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-27.q.01",
      "q": "The #1 cause of death in Americans ages 1-44 is:",
      "opts": [
        "A. Heart disease",
        "B. Cancer",
        "C. Trauma",
        "D. Stroke"
      ],
      "ans": 2,
      "exp": "Unintentional injury (trauma) is the leading cause of death in Americans ages 1-44 — making EMS trauma care critically important."
    },
    {
      "id": "ch-27.q.02",
      "q": "Kinematics in trauma refers to:",
      "opts": [
        "A. Anatomy of injuries",
        "B. The science of motion and energy transfer predicting injury patterns",
        "C. Surgical techniques",
        "D. Hospital triage protocols"
      ],
      "ans": 1,
      "exp": "Kinematics is the study of motion — understanding energy transfer during trauma allows EMTs to predict injury patterns before exam."
    },
    {
      "id": "ch-27.q.03",
      "q": "The three collision events in an MVC are:",
      "opts": [
        "A. Impact, bounce, roll",
        "B. Vehicle hits object, occupant hits vehicle, organs hit structures",
        "C. Skid, crash, fire",
        "D. Brake, swerve, impact"
      ],
      "ans": 1,
      "exp": "Three collisions: vehicle hits object, occupant continues moving and hits vehicle interior, then internal organs hit body structures."
    },
    {
      "id": "ch-27.q.04",
      "q": "A Level I Trauma Center provides:",
      "opts": [
        "A. Basic emergency care only",
        "B. 24/7 surgical capability and highest-level trauma care",
        "C. Pediatric care only",
        "D. Burns only"
      ],
      "ans": 1,
      "exp": "Level I Trauma Centers have 24/7 surgical capability, highest trauma volumes, and provide research and education in trauma care."
    },
    {
      "id": "ch-27.q.05",
      "q": "'Load and go' applies to:",
      "opts": [
        "A. All trauma patients",
        "B. Critical trauma patients requiring rapid transport to trauma center",
        "C. Medical patients only",
        "D. Patients requesting rapid transport"
      ],
      "ans": 1,
      "exp": "Load and go is the approach for critical trauma — minimal on-scene time with rapid transport to the trauma center to keep patients within the Golden Hour."
    },
    {
      "id": "ch-27.q.06",
      "q": "Penetrating trauma differs from blunt trauma because:",
      "opts": [
        "A. It is always less serious",
        "B. Energy is concentrated along a wound tract rather than dispersed",
        "C. It never causes internal injury",
        "D. It only affects the skin"
      ],
      "ans": 1,
      "exp": "Penetrating trauma concentrates energy along the wound tract causing direct tissue damage plus surrounding tissue injury from cavitation."
    }
  ]
};
