// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch25: Chapter = {
  "id": "ch-25",
  "number": 25,
  "partId": "part-09",
  "title": "Submersion & Diving Emergencies",
  "cards": [
    {
      "id": "ch-25.fc.01",
      "q": "What is the priority in any water rescue?",
      "a": "EMT safety first — Reach, Throw, Tow, Go. Never enter water without proper training and equipment."
    },
    {
      "id": "ch-25.fc.02",
      "q": "Why should all submersion victims be transported?",
      "a": "Secondary drowning — pulmonary edema can develop hours after rescue even in initially asymptomatic patients."
    },
    {
      "id": "ch-25.fc.03",
      "q": "What is decompression sickness ('the bends')?",
      "a": "Nitrogen gas bubbles form in blood and tissues when a diver ascends too quickly — causes joint pain, paralysis, or death."
    },
    {
      "id": "ch-25.fc.04",
      "q": "What is arterial gas embolism (AGE)?",
      "a": "Air bubbles enter the arterial circulation from pulmonary barotrauma — the most serious diving emergency, presents like stroke."
    },
    {
      "id": "ch-25.fc.05",
      "q": "What is the treatment for diving emergencies?",
      "a": "100% oxygen, keep patient supine, transport to hyperbaric chamber (recompression therapy) — do not delay."
    },
    {
      "id": "ch-25.fc.06",
      "q": "What spinal injury concern exists with submersion patients?",
      "a": "Diving into shallow water is a common cause of cervical spine fractures — all submersion patients should be treated as potential spinal injury patients."
    },
    {
      "id": "ch-25.fc.07",
      "q": "What is the Mammalian Diving Reflex?",
      "a": "Bradycardia and peripheral vasoconstriction triggered by cold water submersion — may preserve brain function longer in cold-water drowning."
    },
    {
      "id": "ch-25.fc.08",
      "q": "How long should resuscitation be attempted in cold-water drowning?",
      "a": "Aggressively — even after prolonged submersion in cold water, especially in children. 'Not dead until warm and dead.'"
    }
  ],
  "notes": [
    {
      "id": "ch-25.n.01",
      "title": "Drowning Management",
      "body": "Rescue safely (reach-throw-tow-go). Remove from water. Ensure airway — begin rescue breathing in water if trained. C-spine precautions for dive/unknown mechanism. All patients transported regardless of initial appearance — secondary drowning risk. Suction secretions, high-flow O2.",
      "terms": [
        "Secondary drowning",
        "Rescue priority",
        "C-spine",
        "Suction",
        "Pulmonary edema"
      ]
    },
    {
      "id": "ch-25.n.02",
      "title": "Diving Emergencies",
      "body": "Decompression sickness: nitrogen bubbles from rapid ascent — joint pain, rash, neurological symptoms, shock. Arterial gas embolism: most serious — air bubbles in arteries, stroke-like presentation, immediate onset. Both treated with 100% O2 and hyperbaric chamber.",
      "terms": [
        "Decompression sickness",
        "Arterial gas embolism",
        "Barotrauma",
        "Hyperbaric",
        "Nitrogen bubbles"
      ]
    },
    {
      "id": "ch-25.n.03",
      "title": "Cold Water Submersion",
      "body": "Cold water may preserve brain viability longer through the mammalian diving reflex — shunting blood to the brain and heart. Resuscitate all cold-water drowning victims even after prolonged submersion, especially children. Document submersion time and water temperature.",
      "terms": [
        "Mammalian diving reflex",
        "Cold water",
        "Resuscitation",
        "Hypothermia",
        "Submersion time"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-25.q.01",
      "q": "EMT safety in water rescue follows the priority:",
      "opts": [
        "A. Go in immediately",
        "B. Reach, throw, tow, or go (trained rescuers only)",
        "C. Wait for lifeguard",
        "D. Enter water with PPE"
      ],
      "ans": 1,
      "exp": "Reach, throw, row, then go — never enter water without proper water rescue training and equipment. Rescuer drowning is a significant risk.",
      "easy": {
        "q": "What is the priority in any water rescue?",
        "opts": [
          "A. Reach, throw, tow, or go (trained rescuers only)",
          "B. Go in immediately"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Rescue safely (reach-throw-tow-go). Based on this presentation, EMT safety in water rescue follows the priority?",
        "opts": [
          "A. Enter water with PPE",
          "B. Wait for lifeguard",
          "C. Reach, throw, tow, or go (trained rescuers only)",
          "D. Go in immediately"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-25.q.02",
      "q": "All submersion victims should be transported because of risk of:",
      "opts": [
        "A. Sepsis",
        "B. Secondary drowning (delayed pulmonary edema)",
        "C. Spinal injury only",
        "D. Carbon monoxide poisoning"
      ],
      "ans": 1,
      "exp": "Secondary drowning can cause pulmonary edema hours after a submersion event even in patients who initially appear fine.",
      "easy": {
        "q": "Why should all submersion victims be transported?",
        "opts": [
          "A. Secondary drowning (delayed pulmonary edema)",
          "B. Sepsis"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Rescue safely (reach-throw-tow-go). Based on this presentation, all submersion victims should be transported because of risk of?",
        "opts": [
          "A. Carbon monoxide poisoning",
          "B. Spinal injury only",
          "C. Secondary drowning (delayed pulmonary edema)",
          "D. Sepsis"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-25.q.03",
      "q": "Decompression sickness is caused by:",
      "opts": [
        "A. Breathing compressed air too long",
        "B. Nitrogen bubbles forming during rapid ascent",
        "C. Oxygen toxicity",
        "D. Pulmonary barotrauma"
      ],
      "ans": 1,
      "exp": "Rapid ascent causes dissolved nitrogen to form bubbles in blood and tissue — joint pain, neurological symptoms, and shock may result.",
      "easy": {
        "q": "What is decompression sickness ('the bends')?",
        "opts": [
          "A. Nitrogen bubbles forming during rapid ascent",
          "B. Oxygen toxicity"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Decompression sickness: nitrogen bubbles from rapid ascent. Based on this presentation, decompression sickness is caused by?",
        "opts": [
          "A. Breathing compressed air too long",
          "B. Pulmonary barotrauma",
          "C. Nitrogen bubbles forming during rapid ascent",
          "D. Oxygen toxicity"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-25.q.04",
      "q": "Treatment for diving emergencies includes:",
      "opts": [
        "A. Rapid recompression in water",
        "B. 100% oxygen and transport to hyperbaric chamber",
        "C. Aspirin and rapid ascent",
        "D. Oral fluids and rest"
      ],
      "ans": 1,
      "exp": "Both decompression sickness and AGE are treated with 100% O2 and transport to a hyperbaric recompression facility.",
      "easy": {
        "q": "What is the treatment for diving emergencies?",
        "opts": [
          "A. 100% oxygen and transport to hyperbaric chamber",
          "B. Oral fluids and rest"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Decompression sickness: nitrogen bubbles from rapid ascent. Based on this presentation, treatment for diving emergencies includes?",
        "opts": [
          "A. Rapid recompression in water",
          "B. Aspirin and rapid ascent",
          "C. 100% oxygen and transport to hyperbaric chamber",
          "D. Oral fluids and rest"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-25.q.05",
      "q": "All submersion patients should be treated as potential spinal injury patients because:",
      "opts": [
        "A. Water causes spinal cord swelling",
        "B. Diving into shallow water is a common cause of cervical fractures",
        "C. Cold water hardens the spine",
        "D. Seizures during drowning cause spinal injury"
      ],
      "ans": 1,
      "exp": "Diving into shallow water is a very common mechanism of cervical spine injury — assume spinal injury until cleared.",
      "easy": {
        "q": "What spinal injury concern exists with submersion patients?",
        "opts": [
          "A. Diving into shallow water is a common cause of cervical fractures",
          "B. Cold water hardens the spine"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Rescue safely (reach-throw-tow-go). Based on this presentation, all submersion patients should be treated as potential spinal injury patients because?",
        "opts": [
          "A. Seizures during drowning cause spinal injury",
          "B. Water causes spinal cord swelling",
          "C. Diving into shallow water is a common cause of cervical fractures",
          "D. Cold water hardens the spine"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-25.q.06",
      "q": "The mammalian diving reflex may help cold-water drowning victims by:",
      "opts": [
        "A. Raising body temperature",
        "B. Causing bradycardia and preserving brain oxygenation longer",
        "C. Triggering CPR automatically",
        "D. Opening airways"
      ],
      "ans": 1,
      "exp": "Cold water triggers the mammalian diving reflex — shunting blood to the brain and heart, potentially extending viability.",
      "easy": {
        "q": "What is the Mammalian Diving Reflex?",
        "opts": [
          "A. Causing bradycardia and preserving brain oxygenation longer",
          "B. Opening airways"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Cold water may preserve brain viability longer through the mammalian diving reflex. Based on this presentation, the mammalian diving reflex may help cold-water drowning victims by?",
        "opts": [
          "A. Triggering CPR automatically",
          "B. Raising body temperature",
          "C. Causing bradycardia and preserving brain oxygenation longer",
          "D. Opening airways"
        ],
        "ans": 2
      }
    }
  ]
};
