// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch24: Chapter = {
  "id": "ch-24",
  "number": 24,
  "partId": "part-09",
  "title": "Environmental Emergencies",
  "cards": [
    {
      "id": "ch-24.fc.01",
      "q": "What is heat stroke?",
      "a": "A life-threatening emergency with core temperature >104°F, hot/dry or wet skin, and altered mental status — requires immediate aggressive cooling."
    },
    {
      "id": "ch-24.fc.02",
      "q": "What is the difference between heat exhaustion and heat stroke?",
      "a": "Heat exhaustion: heavy sweating, weakness, nausea, normal-elevated temp, LOC intact. Heat stroke: temp >104°F, AMS, hot skin — life-threatening."
    },
    {
      "id": "ch-24.fc.03",
      "q": "How is heat stroke treated?",
      "a": "Immediate aggressive cooling — ice packs to neck/groin/axillae, cool misting, remove clothing, prevent hypothermia after cooling, rapid transport."
    },
    {
      "id": "ch-24.fc.04",
      "q": "What is hypothermia?",
      "a": "Core body temperature below 95°F (35°C) — impairs cardiac, respiratory, and neurological function progressively."
    },
    {
      "id": "ch-24.fc.05",
      "q": "What cardiac rhythm is associated with severe hypothermia?",
      "a": "Ventricular fibrillation — severely hypothermic patients are prone to VF. 'Not dead until warm and dead.'"
    },
    {
      "id": "ch-24.fc.06",
      "q": "What should NOT be done with frostbitten tissue?",
      "a": "Do not rub frostbitten tissue (causes ice crystal damage). Do not rewarm if refreezing is possible — walking on thawed feet causes worse damage."
    },
    {
      "id": "ch-24.fc.07",
      "q": "What are signs of heat cramps?",
      "a": "Painful muscle spasms during or after exercise in heat — caused by salt and water loss. Treated with rest, oral fluids, and electrolyte replacement."
    },
    {
      "id": "ch-24.fc.08",
      "q": "What is the 'not dead until warm and dead' principle?",
      "a": "Severely hypothermic patients may appear dead (no pulse, no respirations) but can survive with aggressive rewarming — do not withhold resuscitation."
    }
  ],
  "notes": [
    {
      "id": "ch-24.n.01",
      "title": "Heat Emergencies",
      "body": "Heat cramps: muscle spasm from electrolyte loss. Heat exhaustion: heavy sweating, weakness, mild temp elevation — move to cool environment, oral/IV hydration. Heat stroke: emergency — temp >104°F, AMS, hot skin. Aggressive immediate cooling saves lives. Do not delay transport.",
      "terms": [
        "Heat cramps",
        "Heat exhaustion",
        "Heat stroke",
        "Core temperature",
        "Active cooling"
      ]
    },
    {
      "id": "ch-24.n.02",
      "title": "Cold Emergencies — Hypothermia",
      "body": "Mild hypothermia (90-95°F): shivering, confusion. Moderate (82-90°F): loss of shivering, muscle rigidity. Severe (<82°F): VF risk, apparent death. Handle gently — rough movement triggers VF. Rewarm from core out. Continue CPR even if patient appears dead.",
      "terms": [
        "Hypothermia",
        "Shivering",
        "VF",
        "Rewarming",
        "Core temperature"
      ]
    },
    {
      "id": "ch-24.n.03",
      "title": "Frostbite Management",
      "body": "Frostbite freezes tissue — ice crystals form in cells. Do not rub or massage. Do not rewarm if risk of refreezing (walking on thawed feet causes worse damage than staying frozen). Protect with loose dry dressing, elevate, transport. Rewarm in warm water (100-108°F) only if refreezing impossible.",
      "terms": [
        "Frostbite",
        "Ice crystals",
        "Rewarm",
        "Refreezing",
        "Local cold injury"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-24.q.01",
      "q": "Heat stroke differs from heat exhaustion by:",
      "opts": [
        "A. Lower body temperature",
        "B. Presence of sweating",
        "C. Altered mental status and temp >104°F",
        "D. Muscle cramps only"
      ],
      "ans": 2,
      "exp": "Heat stroke = core temp >104°F with altered mental status — a life-threatening emergency requiring immediate aggressive cooling.",
      "easy": {
        "q": "What is heat stroke?",
        "opts": [
          "A. Altered mental status and temp >104°F",
          "B. Muscle cramps only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Heat cramps: muscle spasm from electrolyte loss. Based on this presentation, heat stroke differs from heat exhaustion by?",
        "opts": [
          "A. Lower body temperature",
          "B. Presence of sweating",
          "C. Altered mental status and temp >104°F",
          "D. Muscle cramps only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-24.q.02",
      "q": "Treatment for heat stroke includes:",
      "opts": [
        "A. Warm blankets",
        "B. Immediate aggressive cooling to neck, groin, and axillae",
        "C. Oral fluids only",
        "D. Wait for ALS before cooling"
      ],
      "ans": 1,
      "exp": "Begin aggressive cooling immediately — ice packs to neck, axillae, and groin; cool misting; remove clothing. Do not delay transport.",
      "easy": {
        "q": "How is heat stroke treated?",
        "opts": [
          "A. Immediate aggressive cooling to neck, groin, and axillae",
          "B. Warm blankets"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Heat cramps: muscle spasm from electrolyte loss. Based on this presentation, treatment for heat stroke includes?",
        "opts": [
          "A. Wait for ALS before cooling",
          "B. Oral fluids only",
          "C. Immediate aggressive cooling to neck, groin, and axillae",
          "D. Warm blankets"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-24.q.03",
      "q": "A severely hypothermic patient appears pulseless. You should:",
      "opts": [
        "A. Pronounce death",
        "B. Begin CPR and transport — 'not dead until warm and dead'",
        "C. Check blood glucose first",
        "D. Attempt defibrillation without CPR"
      ],
      "ans": 1,
      "exp": "Hypothermic patients may appear dead but are viable. Begin CPR and transport for active core rewarming. VF may not convert until warmed.",
      "easy": {
        "q": "What cardiac rhythm is associated with severe hypothermia?",
        "opts": [
          "A. Begin CPR and transport — 'not dead until warm and dead'",
          "B. Pronounce death"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Mild hypothermia (90-95°F): shivering, confusion. Based on this presentation, a severely hypothermic patient appears pulseless. You should?",
        "opts": [
          "A. Attempt defibrillation without CPR",
          "B. Check blood glucose first",
          "C. Begin CPR and transport — 'not dead until warm and dead'",
          "D. Pronounce death"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-24.q.04",
      "q": "Frostbitten fingers should NOT be:",
      "opts": [
        "A. Protected with loose dressing",
        "B. Rubbed to restore circulation",
        "C. Elevated during transport",
        "D. Kept from further cold exposure"
      ],
      "ans": 1,
      "exp": "Never rub frostbitten tissue — ice crystals in cells cause further damage when rubbed. Protect gently and transport.",
      "easy": {
        "q": "What is Frostbitten fingers should NOT be?",
        "opts": [
          "A. Rubbed to restore circulation",
          "B. Elevated during transport"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Frostbitten fingers should NOT be?",
        "opts": [
          "A. Kept from further cold exposure",
          "B. Protected with loose dressing",
          "C. Rubbed to restore circulation",
          "D. Elevated during transport"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-24.q.05",
      "q": "The cardiac rhythm most associated with severe hypothermia is:",
      "opts": [
        "A. Normal sinus rhythm",
        "B. Atrial fibrillation",
        "C. Ventricular fibrillation",
        "D. Sinus bradycardia"
      ],
      "ans": 2,
      "exp": "Severe hypothermia (especially with rough handling) predisposes patients to ventricular fibrillation.",
      "easy": {
        "q": "What cardiac rhythm is associated with severe hypothermia?",
        "opts": [
          "A. Ventricular fibrillation",
          "B. Sinus bradycardia"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Mild hypothermia (90-95°F): shivering, confusion. Based on this presentation, the cardiac rhythm most associated with severe hypothermia is?",
        "opts": [
          "A. Normal sinus rhythm",
          "B. Atrial fibrillation",
          "C. Ventricular fibrillation",
          "D. Sinus bradycardia"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-24.q.06",
      "q": "Heat cramps are caused by:",
      "opts": [
        "A. Excess water intake",
        "B. Salt and water loss during exercise in heat",
        "C. Fever from infection",
        "D. Dehydration alone"
      ],
      "ans": 1,
      "exp": "Heat cramps result from electrolyte (sodium) depletion during sweating — treated with oral electrolyte fluids and rest.",
      "easy": {
        "q": "What are signs of heat cramps?",
        "opts": [
          "A. Salt and water loss during exercise in heat",
          "B. Dehydration alone"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Heat cramps: muscle spasm from electrolyte loss. Based on this presentation, heat cramps are caused by?",
        "opts": [
          "A. Fever from infection",
          "B. Excess water intake",
          "C. Salt and water loss during exercise in heat",
          "D. Dehydration alone"
        ],
        "ans": 2
      }
    }
  ]
};
