// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch20: Chapter = {
  "id": "ch-20",
  "number": 20,
  "partId": "part-09",
  "title": "Acute Diabetic Emergencies",
  "cards": [
    {
      "id": "ch-20.fc.01",
      "q": "What is hypoglycemia and its signs?",
      "a": "Low blood glucose (<70 mg/dL). Signs: altered mental status, diaphoresis, weakness, shakiness, combativeness."
    },
    {
      "id": "ch-20.fc.02",
      "q": "What is the EMT treatment for conscious hypoglycemia?",
      "a": "Oral glucose gel if patient is conscious and can protect their airway — 15-25 grams administered."
    },
    {
      "id": "ch-20.fc.03",
      "q": "What is DKA?",
      "a": "Diabetic Ketoacidosis — life-threatening complication of Type 1 diabetes. High blood glucose, ketones, metabolic acidosis."
    },
    {
      "id": "ch-20.fc.04",
      "q": "What are signs of DKA?",
      "a": "Kussmaul respirations (deep, rapid), fruity/acetone breath, nausea/vomiting, polydipsia, polyuria, dehydration."
    },
    {
      "id": "ch-20.fc.05",
      "q": "What is the first step in managing any AMS patient?",
      "a": "Check blood glucose — hypoglycemia is rapidly treatable and mimics many serious conditions."
    },
    {
      "id": "ch-20.fc.06",
      "q": "What blood glucose level is considered hypoglycemia?",
      "a": "Below 70 mg/dL — though symptoms can vary; treat based on clinical presentation in the field."
    },
    {
      "id": "ch-20.fc.07",
      "q": "Why can't oral glucose be given to an unconscious patient?",
      "a": "Unconscious patients cannot protect their airway — oral glucose risks aspiration. These patients need ALS and IV dextrose."
    },
    {
      "id": "ch-20.fc.08",
      "q": "What is HHNS?",
      "a": "Hyperosmolar Hyperglycemic Nonketotic Syndrome — extreme hyperglycemia in Type 2 diabetics without ketoacidosis; very high glucose, severe dehydration, AMS."
    }
  ],
  "notes": [
    {
      "id": "ch-20.n.01",
      "title": "Diabetic Emergencies Overview",
      "body": "Type 1 (insulin-dependent) and Type 2 diabetes both produce emergencies. Hypoglycemia (low blood sugar) is most common — develops rapidly and is dangerous. Hyperglycemia (DKA, HHNS) develops slowly but becomes life-threatening. Always check blood glucose in AMS.",
      "terms": [
        "Hypoglycemia",
        "Hyperglycemia",
        "DKA",
        "HHNS",
        "Blood glucose"
      ]
    },
    {
      "id": "ch-20.n.02",
      "title": "Hypoglycemia Management",
      "body": "Recognizable by AMS, sweating, trembling, and hunger. Treat with oral glucose in conscious patients with intact airway. Reassess after 15 minutes. If no improvement or deterioration: ALS, IV dextrose. Never give oral glucose to unconscious patients — aspiration risk.",
      "terms": [
        "Oral glucose",
        "Airway protection",
        "ALS",
        "IV dextrose",
        "Reassessment"
      ]
    },
    {
      "id": "ch-20.n.03",
      "title": "Hyperglycemia Recognition",
      "body": "DKA: Kussmaul breathing (deep/rapid to blow off CO2), fruity/acetone breath, gradual onset, usually Type 1. HHNS: extreme hyperglycemia, severe dehydration, no ketones, usually Type 2 elderly. Both require hospital management — EMT provides supportive care and transport.",
      "terms": [
        "Kussmaul respirations",
        "Fruity breath",
        "Ketoacidosis",
        "Dehydration",
        "Supportive care"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-20.q.01",
      "q": "A diabetic patient is confused with blood glucose 45 mg/dL. Treatment is:",
      "opts": [
        "A. Insulin",
        "B. Oral glucose if conscious and can swallow",
        "C. IV fluids",
        "D. Aspirin"
      ],
      "ans": 1,
      "exp": "Hypoglycemia with intact gag reflex is treated with oral glucose gel. Never give anything by mouth if the patient cannot protect their airway."
    },
    {
      "id": "ch-20.q.02",
      "q": "Kussmaul respirations are associated with:",
      "opts": [
        "A. Hypoglycemia",
        "B. Normal breathing",
        "C. DKA (diabetic ketoacidosis)",
        "D. Seizures"
      ],
      "ans": 2,
      "exp": "Kussmaul respirations are deep, rapid breaths — the body's attempt to blow off CO2 and compensate for metabolic acidosis in DKA."
    },
    {
      "id": "ch-20.q.03",
      "q": "You cannot give oral glucose to an unconscious patient because:",
      "opts": [
        "A. It won't be absorbed",
        "B. It causes aspiration risk without airway protection",
        "C. It raises glucose too slowly",
        "D. It is only for Type 1 diabetics"
      ],
      "ans": 1,
      "exp": "Unconscious patients cannot protect their airway — oral glucose would aspirate into the lungs. These patients need ALS and IV dextrose."
    },
    {
      "id": "ch-20.q.04",
      "q": "First step in managing any AMS patient:",
      "opts": [
        "A. Administer oral glucose empirically",
        "B. Check blood glucose",
        "C. Perform detailed neurological exam",
        "D. Obtain full SAMPLE history"
      ],
      "ans": 1,
      "exp": "Check blood glucose first in any AMS patient — hypoglycemia is immediately treatable and can mimic stroke, overdose, and other emergencies."
    },
    {
      "id": "ch-20.q.05",
      "q": "DKA is characterized by:",
      "opts": [
        "A. Low glucose, sweating, trembling",
        "B. High glucose, Kussmaul respirations, fruity breath",
        "C. Normal glucose, seizures",
        "D. Low glucose, Kussmaul respirations"
      ],
      "ans": 1,
      "exp": "DKA: elevated glucose, ketones, Kussmaul respirations (deep/rapid), fruity/acetone breath, nausea, and gradual onset."
    },
    {
      "id": "ch-20.q.06",
      "q": "Normal blood glucose range is approximately:",
      "opts": [
        "A. 40-60 mg/dL",
        "B. 70-120 mg/dL",
        "C. 150-200 mg/dL",
        "D. 200-300 mg/dL"
      ],
      "ans": 1,
      "exp": "Normal blood glucose is approximately 70-120 mg/dL. Below 70 = hypoglycemia. Above 200 consistently = hyperglycemia."
    }
  ]
};
