// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch28: Chapter = {
  "id": "ch-28",
  "number": 28,
  "partId": "part-10",
  "title": "Bleeding & Soft Tissue Trauma",
  "cards": [
    {
      "id": "ch-28.fc.01",
      "q": "What is the most effective first-line treatment for external bleeding?",
      "a": "Direct, continuous pressure — apply and hold firmly with a gloved hand and dressing. Do not remove once applied."
    },
    {
      "id": "ch-28.fc.02",
      "q": "What are the three types of external bleeding by vessel type?",
      "a": "Arterial: bright red, spurting, difficult to control. Venous: dark red, steady flow. Capillary: slow oozing, usually self-limiting."
    },
    {
      "id": "ch-28.fc.03",
      "q": "What is a pressure dressing?",
      "a": "A dressing that maintains constant pressure over a wound during transport — secured firmly but without cutting off circulation."
    },
    {
      "id": "ch-28.fc.04",
      "q": "What are the indications for tourniquet use?",
      "a": "Life-threatening extremity bleeding not controlled by direct pressure — usually arterial bleeding from amputation or major laceration."
    },
    {
      "id": "ch-28.fc.05",
      "q": "How do you treat an impaled object?",
      "a": "Do NOT remove — stabilize in place with bulky dressings. Removal can cause massive hemorrhage. Exception: object impaling the cheek obstructing airway."
    },
    {
      "id": "ch-28.fc.06",
      "q": "What is an avulsion?",
      "a": "A piece of skin/tissue that is torn or separated from the body — cover with moist dressing, transport the avulsed tissue if possible."
    },
    {
      "id": "ch-28.fc.07",
      "q": "What is the treatment for an open neck wound?",
      "a": "Immediately cover with an occlusive dressing — risk of air embolism if jugular vein is lacerated."
    },
    {
      "id": "ch-28.fc.08",
      "q": "What is wound packing?",
      "a": "Filling a deep wound with hemostatic gauze and applying sustained direct pressure — used for junctional wounds where tourniquets cannot be applied."
    }
  ],
  "notes": [
    {
      "id": "ch-28.n.01",
      "title": "Hemorrhage Control",
      "body": "Control external bleeding: direct pressure first. For arterial bleeding uncontrolled by pressure: tourniquet (extremity) or wound packing (junctional). Time tourniquet application. Hemostatic dressings enhance clotting. Never remove dressings once applied — add more if soaking through.",
      "terms": [
        "Direct pressure",
        "Tourniquet",
        "Wound packing",
        "Hemostatic gauze",
        "Pressure dressing"
      ]
    },
    {
      "id": "ch-28.n.02",
      "title": "Wound Types & Treatment",
      "body": "Abrasions: clean and dress. Lacerations: control bleeding, dress. Avulsions: moist dressing, transport tissue. Amputations: control bleeding at stump (tourniquet), wrap amputated part in moist dressing in sealed bag, keep cool (not frozen). Impaled objects: stabilize, do not remove.",
      "terms": [
        "Avulsion",
        "Amputation",
        "Impaled object",
        "Laceration",
        "Abrasion"
      ]
    },
    {
      "id": "ch-28.n.03",
      "title": "Special Wound Considerations",
      "body": "Open neck wounds: immediate occlusive dressing (air embolism risk). Evisceration (abdominal organs out): moist sterile dressing, do not push organs back in. Chest wounds with air sucking: three-sided occlusive dressing. All require careful monitoring and rapid transport.",
      "terms": [
        "Occlusive dressing",
        "Evisceration",
        "Air embolism",
        "Sucking chest wound",
        "Moist dressing"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-28.q.01",
      "q": "First-line treatment for external bleeding is:",
      "opts": [
        "A. Tourniquet",
        "B. Pressure point",
        "C. Direct continuous pressure",
        "D. Elevation only"
      ],
      "ans": 2,
      "exp": "Direct, continuous pressure is always first-line for external hemorrhage. Tourniquets and wound packing are for bleeding uncontrolled by pressure."
    },
    {
      "id": "ch-28.q.02",
      "q": "Arterial bleeding is characterized by:",
      "opts": [
        "A. Dark red, slow oozing",
        "B. Bright red, spurting, difficult to control",
        "C. Dark red, steady flow",
        "D. Slow capillary oozing"
      ],
      "ans": 1,
      "exp": "Arterial bleeding is bright red (highly oxygenated), spurts with each heartbeat, and is most difficult to control."
    },
    {
      "id": "ch-28.q.03",
      "q": "An impaled object should be:",
      "opts": [
        "A. Removed to allow wound care",
        "B. Stabilized in place with bulky dressings",
        "C. Removed if it is more than 2 inches long",
        "D. Removed and the wound packed"
      ],
      "ans": 1,
      "exp": "Never remove an impaled object — it may be controlling bleeding. Stabilize in place. Exception: cheek impalement obstructing airway."
    },
    {
      "id": "ch-28.q.04",
      "q": "Treatment for an open neck wound includes:",
      "opts": [
        "A. Pressure dressing only",
        "B. Immediate occlusive dressing to prevent air embolism",
        "C. Tourniquet",
        "D. Irrigation with saline"
      ],
      "ans": 1,
      "exp": "Jugular vein lacerations can cause fatal air embolism — immediately cover with an occlusive (airtight) dressing."
    },
    {
      "id": "ch-28.q.05",
      "q": "Wound packing is used for:",
      "opts": [
        "A. All extremity wounds",
        "B. Junctional wounds where tourniquets cannot be applied",
        "C. Minor abrasions",
        "D. Impaled object wounds"
      ],
      "ans": 1,
      "exp": "Wound packing (hemostatic gauze with sustained pressure) is used for junctional wounds in the groin, axilla, or neck where tourniquets cannot be applied."
    },
    {
      "id": "ch-28.q.06",
      "q": "When a dressing becomes soaked with blood, you should:",
      "opts": [
        "A. Remove and replace with a new dressing",
        "B. Add more dressings on top — do not remove",
        "C. Irrigate and re-dress",
        "D. Apply a tourniquet regardless of location"
      ],
      "ans": 1,
      "exp": "Never remove a blood-soaked dressing — removing it may dislodge the clot and restart bleeding. Add more dressings on top and apply more pressure."
    }
  ]
};
