// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch26: Chapter = {
  "id": "ch-26",
  "number": 26,
  "partId": "part-09",
  "title": "Psychiatric Emergencies",
  "cards": [
    {
      "id": "ch-26.fc.01",
      "q": "What is excited delirium?",
      "a": "A state of extreme agitation, combativeness, hyperthermia, and apparent superhuman strength — high risk of sudden cardiac death. Associated with stimulant use or psychiatric illness."
    },
    {
      "id": "ch-26.fc.02",
      "q": "How should an EMT approach an agitated psychiatric patient?",
      "a": "Calm, non-threatening demeanor, maintain safe distance, avoid sudden movements, speak slowly and clearly, reduce environmental stimuli."
    },
    {
      "id": "ch-26.fc.03",
      "q": "What is the EMT's role in patient restraint?",
      "a": "Restrain only when necessary for safety. Use minimum force. Document thoroughly. Never restrain face-down (positional asphyxia risk). Reassess continuously."
    },
    {
      "id": "ch-26.fc.04",
      "q": "What is positional asphyxia?",
      "a": "Death from body position restricting breathing — risk with face-down or hog-tied restraint. Keep restrained patients supine or lateral."
    },
    {
      "id": "ch-26.fc.05",
      "q": "When can an EMT transport a patient against their will?",
      "a": "When the patient poses an imminent danger to self or others, is incompetent to refuse, or a legal involuntary hold has been initiated."
    },
    {
      "id": "ch-26.fc.06",
      "q": "What should be ruled out before assuming a psychiatric cause for AMS?",
      "a": "Medical causes — hypoglycemia, hypoxia, overdose, head injury, sepsis. These can mimic psychiatric disorders and are immediately treatable."
    },
    {
      "id": "ch-26.fc.07",
      "q": "What signs indicate high risk for suicide?",
      "a": "Previous attempts, specific plan, access to means, hopelessness, recent major loss, substance use, social isolation."
    },
    {
      "id": "ch-26.fc.08",
      "q": "What is de-escalation?",
      "a": "Verbal and non-verbal techniques used to calm an agitated patient without use of force — preferred first approach before restraint."
    }
  ],
  "notes": [
    {
      "id": "ch-26.n.01",
      "title": "Approaching Psychiatric Patients",
      "body": "Assume any unusual behavior may have a medical cause (hypoglycemia, hypoxia, overdose) — rule out medical emergencies first. Use calm, non-judgmental therapeutic communication. Reduce environmental stimuli (lights, noise). Never leave a suicidal patient alone.",
      "terms": [
        "Therapeutic communication",
        "Medical rule-out",
        "Stimuli reduction",
        "De-escalation",
        "Suicidal ideation"
      ]
    },
    {
      "id": "ch-26.n.02",
      "title": "Restraint & Excited Delirium",
      "body": "Restraint is a last resort — use minimum force with law enforcement assistance. Never restrain face-down (positional asphyxia). Excited delirium: hyperthermia, extreme agitation, insensitivity to pain — requires rapid sedation (ALS) and cooling. Monitor continuously — high mortality risk.",
      "terms": [
        "Positional asphyxia",
        "Excited delirium",
        "Restraint",
        "Monitoring",
        "Hyperthermia"
      ]
    },
    {
      "id": "ch-26.n.03",
      "title": "Suicide & Involuntary Transport",
      "body": "Take all suicidal statements seriously. Assess for plan, means, and intent. Remove access to means if safe to do so. Transport for psychiatric evaluation. Involuntary transport (5150, Baker Act) is legal when patient is danger to self/others or gravely disabled. Document thoroughly.",
      "terms": [
        "Suicide assessment",
        "5150",
        "Baker Act",
        "Involuntary hold",
        "Gravely disabled"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-26.q.01",
      "q": "When approaching an agitated psychiatric patient, you should:",
      "opts": [
        "A. Move quickly and take control",
        "B. Approach calmly, speak slowly, maintain safe distance",
        "C. Immediately restrain for safety",
        "D. Ignore behavior and treat medically"
      ],
      "ans": 1,
      "exp": "Calm, non-threatening approach reduces escalation. Sudden movements and raised voices can trigger violent behavior.",
      "easy": {
        "q": "How should an EMT approach an agitated psychiatric patient?",
        "opts": [
          "A. Approach calmly, speak slowly, maintain safe distance",
          "B. Move quickly and take control"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Assume any unusual behavior may have a medical cause (hypoglycemia, hypoxia, overdose). Based on this presentation, when approaching an agitated psychiatric patient, you should?",
        "opts": [
          "A. Ignore behavior and treat medically",
          "B. Immediately restrain for safety",
          "C. Approach calmly, speak slowly, maintain safe distance",
          "D. Move quickly and take control"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-26.q.02",
      "q": "Positional asphyxia is a risk when a restrained patient is:",
      "opts": [
        "A. Seated upright",
        "B. Supine with arms restrained",
        "C. Placed face-down (prone)",
        "D. In the lateral position"
      ],
      "ans": 2,
      "exp": "Face-down (prone) restraint can cause positional asphyxia — body weight restricts chest expansion. Always keep restrained patients supine or lateral.",
      "easy": {
        "q": "What is positional asphyxia?",
        "opts": [
          "A. Placed face-down (prone)",
          "B. Seated upright"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Positional asphyxia is a risk when a restrained patient is?",
        "opts": [
          "A. Supine with arms restrained",
          "B. In the lateral position",
          "C. Placed face-down (prone)",
          "D. Seated upright"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-26.q.03",
      "q": "Excited delirium is characterized by:",
      "opts": [
        "A. Calm behavior with hallucinations",
        "B. Extreme agitation, hyperthermia, combativeness, and risk of sudden cardiac death",
        "C. Bradycardia and hypothermia",
        "D. Weakness and confusion"
      ],
      "ans": 1,
      "exp": "Excited delirium involves extreme agitation, high body temperature, and high risk of sudden cardiac death — treat as emergent.",
      "easy": {
        "q": "What is excited delirium?",
        "opts": [
          "A. Extreme agitation, hyperthermia, combativeness, and risk of sudden cardiac death",
          "B. Weakness and confusion"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Excited delirium is characterized by?",
        "opts": [
          "A. Calm behavior with hallucinations",
          "B. Bradycardia and hypothermia",
          "C. Extreme agitation, hyperthermia, combativeness, and risk of sudden cardiac death",
          "D. Weakness and confusion"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-26.q.04",
      "q": "Before assuming a patient has a psychiatric cause for AMS:",
      "opts": [
        "A. Apply restraints",
        "B. Rule out medical causes (hypoglycemia, hypoxia, drugs)",
        "C. Contact family members",
        "D. Give oral glucose empirically"
      ],
      "ans": 1,
      "exp": "Medical emergencies can mimic psychiatric disorders — always rule out hypoglycemia, hypoxia, overdose, and head injury first.",
      "easy": {
        "q": "What should be ruled out before assuming a psychiatric cause for AMS?",
        "opts": [
          "A. Rule out medical causes (hypoglycemia, hypoxia, drugs)",
          "B. Apply restraints"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Assume any unusual behavior may have a medical cause (hypoglycemia, hypoxia, overdose). Based on this presentation, before assuming a patient has a psychiatric cause for AMS?",
        "opts": [
          "A. Give oral glucose empirically",
          "B. Contact family members",
          "C. Rule out medical causes (hypoglycemia, hypoxia, drugs)",
          "D. Apply restraints"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-26.q.05",
      "q": "An EMT may transport a patient against their will when:",
      "opts": [
        "A. Family requests it",
        "B. The patient seems upset",
        "C. A legal involuntary hold exists or patient poses imminent danger",
        "D. The patient refuses but is ambulatory"
      ],
      "ans": 2,
      "exp": "Involuntary transport requires legal authority (involuntary hold/5150/Baker Act) or imminent danger to self or others.",
      "easy": {
        "q": "When can an EMT transport a patient against their will?",
        "opts": [
          "A. A legal involuntary hold exists or patient poses imminent danger",
          "B. Family requests it"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Take all suicidal statements seriously. Based on this presentation, an EMT may transport a patient against their will when?",
        "opts": [
          "A. The patient refuses but is ambulatory",
          "B. The patient seems upset",
          "C. A legal involuntary hold exists or patient poses imminent danger",
          "D. Family requests it"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-26.q.06",
      "q": "All suicidal statements from patients should be:",
      "opts": [
        "A. Minimized if the patient seems stable",
        "B. Taken seriously and documented",
        "C. Ignored if no attempt was made",
        "D. Only reported if a plan exists"
      ],
      "ans": 1,
      "exp": "All suicidal ideation must be taken seriously. Suicidal statements, even vague ones, require transport for psychiatric evaluation.",
      "easy": {
        "q": "What is All suicidal statements from patients should be?",
        "opts": [
          "A. Taken seriously and documented",
          "B. Ignored if no attempt was made"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Assume any unusual behavior may have a medical cause (hypoglycemia, hypoxia, overdose). Based on this presentation, all suicidal statements from patients should be?",
        "opts": [
          "A. Minimized if the patient seems stable",
          "B. Ignored if no attempt was made",
          "C. Taken seriously and documented",
          "D. Only reported if a plan exists"
        ],
        "ans": 2
      }
    }
  ]
};
