// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch30: Chapter = {
  "id": "ch-30",
  "number": 30,
  "partId": "part-10",
  "title": "Musculoskeletal Trauma & Fractures",
  "cards": [
    {
      "id": "ch-30.fc.01",
      "q": "What is the difference between open and closed fractures?",
      "a": "Open (compound): bone breaks through skin — infection risk. Closed: bone breaks without skin disruption."
    },
    {
      "id": "ch-30.fc.02",
      "q": "What are the 6 Ps of musculoskeletal injury?",
      "a": "Pain, Pallor, Paralysis, Paresthesia, Pressure, Pulselessness — signs of neurovascular compromise."
    },
    {
      "id": "ch-30.fc.03",
      "q": "What is the EMT's priority in trauma assessment?",
      "a": "Life over limb — identify and treat life threats first (ABCs), then manage orthopedic injuries."
    },
    {
      "id": "ch-30.fc.04",
      "q": "How should an angulated fracture be splinted?",
      "a": "Splint in position found unless circulation/sensation is compromised — then gently straighten to restore distal perfusion."
    },
    {
      "id": "ch-30.fc.05",
      "q": "What splint is used for femur fractures?",
      "a": "Traction splint (Hare or Sager) — applies longitudinal traction to relieve muscle spasm and reduce blood loss into the thigh."
    },
    {
      "id": "ch-30.fc.06",
      "q": "What is CSM and when is it assessed?",
      "a": "Circulation, Sensation, Motor function — assessed before AND after any splinting or manipulation."
    },
    {
      "id": "ch-30.fc.07",
      "q": "How much blood can be lost into a femur fracture?",
      "a": "Up to 1-1.5 liters of blood can be lost into the thigh from a femur fracture — significant shock risk."
    },
    {
      "id": "ch-30.fc.08",
      "q": "What is a dislocation?",
      "a": "Separation of a bone from its normal position in a joint — do not reduce in the field unless circulation is severely compromised."
    }
  ],
  "notes": [
    {
      "id": "ch-30.n.01",
      "title": "Musculoskeletal Injuries",
      "body": "Fractures, dislocations, sprains, and strains are common trauma injuries. Assess neurovascular status (6 Ps and CSM) before and after splinting. All suspected fractures are splinted to prevent further injury, reduce pain, and immobilize for transport.",
      "terms": [
        "Fracture",
        "Dislocation",
        "6 Ps",
        "CSM",
        "Neurovascular status"
      ]
    },
    {
      "id": "ch-30.n.02",
      "title": "Splinting Principles",
      "body": "Immobilize the joint above and below the fracture site. Splint in position found unless distal pulse is absent. Pad bony prominences. Reassess CSM before and after splinting. Traction splints for femur only. Never use traction splint for open fractures or fractures near the knee or hip.",
      "terms": [
        "CSM",
        "Immobilize",
        "Traction splint",
        "Padding",
        "Femur"
      ]
    },
    {
      "id": "ch-30.n.03",
      "title": "Femur Fractures & Blood Loss",
      "body": "Femur fractures are serious — powerful thigh muscles contract and cause shortening. Blood loss into the thigh can be 1-1.5 liters. Traction splint counteracts muscle spasm, reduces blood loss, and decreases pain. Assess CSM before and after application.",
      "terms": [
        "Femur fracture",
        "Blood loss",
        "Traction splint",
        "Muscle spasm",
        "Neurovascular compromise"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-30.q.01",
      "q": "Before and after splinting a fracture, you must assess:",
      "opts": [
        "A. Blood pressure",
        "B. CSM — circulation, sensation, motor function",
        "C. Blood glucose",
        "D. Pupils"
      ],
      "ans": 1,
      "exp": "CSM (circulation, sensation, and motor function) must be checked before and after any splinting intervention to detect neurovascular compromise.",
      "level1": {
        "q": "What is CSM and when is it assessed?",
        "opts": [
          "A. CSM — circulation, sensation, motor function",
          "B. Pupils"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-30.q.02",
      "q": "A traction splint is specifically used for:",
      "opts": [
        "A. All lower extremity fractures",
        "B. Mid-shaft femur fractures",
        "C. Ankle fractures",
        "D. Open fractures of the thigh"
      ],
      "ans": 1,
      "exp": "Traction splints are used for mid-shaft femur fractures to counteract muscle spasm, reduce pain, and decrease blood loss into the thigh.",
      "level1": {
        "q": "What is traction splint is specifically used for?",
        "opts": [
          "A. Mid-shaft femur fractures",
          "B. Ankle fractures"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-30.q.03",
      "q": "Blood loss into a femur fracture can be:",
      "opts": [
        "A. 100-200 mL",
        "B. 200-500 mL",
        "C. 1-1.5 liters",
        "D. Less than 100 mL"
      ],
      "ans": 2,
      "exp": "Up to 1-1.5 liters of blood can be lost into the thigh from a femur fracture — enough to cause significant hypovolemic shock.",
      "level1": {
        "q": "How much blood can be lost into a femur fracture?",
        "opts": [
          "A. 1-1.5 liters",
          "B. 100-200 mL"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-30.q.04",
      "q": "An angulated fracture with an absent distal pulse should be:",
      "opts": [
        "A. Splinted in position found",
        "B. Gently realigned to restore circulation",
        "C. Immediately transported without splinting",
        "D. Reduced (popped back in) by EMT"
      ],
      "ans": 1,
      "exp": "If distal circulation is compromised, gently attempt to realign the fracture to restore perfusion. If you cannot, splint in position and rapid transport.",
      "level1": {
        "q": "How should an angulated fracture be splinted?",
        "opts": [
          "A. Gently realigned to restore circulation",
          "B. Splinted in position found"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-30.q.05",
      "q": "The 6 Ps of musculoskeletal injury include:",
      "opts": [
        "A. Pain, Pulse, Position, Pallor, Pressure, Paresthesia",
        "B. Pain, Pallor, Paralysis, Paresthesia, Pressure, Pulselessness",
        "C. Pain, Pallor, Perfusion, Pulse, Paralysis, Protection",
        "D. Palpation, Pressure, Pain, Position, Pulse, Paresthesia"
      ],
      "ans": 1,
      "exp": "6 Ps: Pain, Pallor, Paralysis, Paresthesia, Pressure, Pulselessness — signs of neurovascular compromise requiring immediate action.",
      "level1": {
        "q": "What are the 6 Ps of musculoskeletal injury?",
        "opts": [
          "A. Pain, Pallor, Paralysis, Paresthesia, Pressure, Pulselessness",
          "B. Pain, Pulse, Position, Pallor, Pressure, Paresthesia"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-30.q.06",
      "q": "A dislocation in the field should be:",
      "opts": [
        "A. Always reduced by the EMT",
        "B. Left in position found and splinted unless circulation is severely compromised",
        "C. Manually reduced if painful",
        "D. Ignored if the patient can move the extremity"
      ],
      "ans": 1,
      "exp": "Do not reduce dislocations in the field — splint in position found. Reduction attempts can cause fractures, nerve, and vessel damage.",
      "level1": {
        "q": "How should an angulated fracture be splinted?",
        "opts": [
          "A. Left in position found and splinted unless circulation is severely compromised",
          "B. Always reduced by the EMT"
        ],
        "ans": 0
      }
    }
  ]
};
