// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch34: Chapter = {
  "id": "ch-34",
  "number": 34,
  "partId": "part-10",
  "title": "Chest Trauma",
  "cards": [
    {
      "id": "ch-34.fc.01",
      "q": "What is a tension pneumothorax?",
      "a": "Air builds up in the pleural space under pressure, compressing the lung and shifting mediastinal structures — immediately life-threatening."
    },
    {
      "id": "ch-34.fc.02",
      "q": "What are signs of tension pneumothorax?",
      "a": "Absent breath sounds on affected side, tracheal deviation (away from injury), JVD, severe respiratory distress, hypotension, cyanosis."
    },
    {
      "id": "ch-34.fc.03",
      "q": "What is a flail chest?",
      "a": "Three or more adjacent ribs fractured in two places each, creating a floating segment that moves paradoxically (opposite direction) with breathing."
    },
    {
      "id": "ch-34.fc.04",
      "q": "What is the treatment for a sucking chest wound?",
      "a": "Apply a three-sided occlusive dressing (or vented chest seal) — seals on three sides to allow air to escape but not enter."
    },
    {
      "id": "ch-34.fc.05",
      "q": "What is a hemothorax?",
      "a": "Blood in the pleural space — compresses the lung. Large hemothorax can cause significant hypovolemic shock."
    },
    {
      "id": "ch-34.fc.06",
      "q": "What is pericardial tamponade?",
      "a": "Blood in the pericardial sac compressing the heart — prevents adequate filling. Signs: Beck's Triad (JVD, muffled heart sounds, hypotension)."
    },
    {
      "id": "ch-34.fc.07",
      "q": "What is a simple pneumothorax?",
      "a": "Air in the pleural space without pressure buildup or mediastinal shift — causes dyspnea and decreased breath sounds on affected side."
    },
    {
      "id": "ch-34.fc.08",
      "q": "What is the treatment for flail chest?",
      "a": "High-flow O2, positive pressure ventilation if breathing inadequate, consider stabilizing the flail segment with bulky padding, rapid transport."
    }
  ],
  "notes": [
    {
      "id": "ch-34.n.01",
      "title": "Pneumothorax & Hemothorax",
      "body": "Simple pneumothorax: air in pleural space, decreased breath sounds, dyspnea. Tension pneumothorax: air under pressure — tracheal deviation, JVD, hypotension — life-threatening, requires immediate needle decompression (ALS). Hemothorax: blood in pleural space — can cause significant volume loss.",
      "terms": [
        "Pneumothorax",
        "Tension pneumothorax",
        "Hemothorax",
        "Breath sounds",
        "Tracheal deviation"
      ]
    },
    {
      "id": "ch-34.n.02",
      "title": "Chest Wall Injuries",
      "body": "Rib fractures: painful breathing, splinting (shallow breathing risks pneumonia). Flail chest: paradoxical movement, respiratory failure — treat with positive pressure ventilation. Sucking chest wound: three-sided occlusive dressing. These injuries are often associated with pneumo/hemothorax.",
      "terms": [
        "Flail chest",
        "Rib fracture",
        "Sucking chest wound",
        "Paradoxical movement",
        "Occlusive dressing"
      ]
    },
    {
      "id": "ch-34.n.03",
      "title": "Cardiac Tamponade",
      "body": "Blood accumulates in the rigid pericardial sac, compressing the heart — even small amounts (150-200 mL) can be fatal. Beck's Triad: JVD (increased venous pressure), muffled heart sounds, hypotension. Requires emergency pericardiocentesis (hospital). EMT: recognize and transport rapidly.",
      "terms": [
        "Pericardial tamponade",
        "Beck's Triad",
        "JVD",
        "Muffled heart sounds",
        "Pericardiocentesis"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-34.q.01",
      "q": "Signs of tension pneumothorax include:",
      "opts": [
        "A. Equal breath sounds, hypertension",
        "B. Absent breath sounds on affected side, tracheal deviation, JVD, hypotension",
        "C. Bilateral crackles, normal BP",
        "D. Productive cough, fever"
      ],
      "ans": 1,
      "exp": "Tension pneumothorax: absent breath sounds (affected side), tracheal deviation away from injury, JVD, severe respiratory distress, and hypotension.",
      "level1": {
        "q": "What are signs of tension pneumothorax?",
        "opts": [
          "A. Absent breath sounds on affected side, tracheal deviation, JVD, hypotension",
          "B. Productive cough, fever"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-34.q.02",
      "q": "A sucking chest wound is treated with:",
      "opts": [
        "A. Standard gauze dressing taped on all four sides",
        "B. Three-sided occlusive dressing or vented chest seal",
        "C. Tourniquet around the chest",
        "D. Wound packing with hemostatic gauze"
      ],
      "ans": 1,
      "exp": "Three-sided occlusive dressing seals the wound on three sides, allowing air to escape on exhalation but preventing air entry on inhalation.",
      "level1": {
        "q": "What is the treatment for a sucking chest wound?",
        "opts": [
          "A. Three-sided occlusive dressing or vented chest seal",
          "B. Tourniquet around the chest"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-34.q.03",
      "q": "Flail chest is defined as:",
      "opts": [
        "A. A single rib fracture",
        "B. Three or more adjacent ribs fractured in two places creating a floating segment",
        "C. Sternal fracture",
        "D. Clavicle fracture only"
      ],
      "ans": 1,
      "exp": "Flail chest = 3+ adjacent ribs broken in 2 places each, creating a floating segment with paradoxical movement opposite to normal chest wall.",
      "level1": {
        "q": "What is a flail chest?",
        "opts": [
          "A. Three or more adjacent ribs fractured in two places creating a floating segment",
          "B. Sternal fracture"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-34.q.04",
      "q": "Beck's Triad indicates:",
      "opts": [
        "A. Tension pneumothorax",
        "B. Pericardial tamponade",
        "C. Hemothorax",
        "D. Flail chest"
      ],
      "ans": 1,
      "exp": "Beck's Triad (JVD, muffled heart sounds, hypotension) is the classic presentation of pericardial tamponade — blood compressing the heart.",
      "level1": {
        "q": "What is Beck's Triad indicates?",
        "opts": [
          "A. Pericardial tamponade",
          "B. Hemothorax"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-34.q.05",
      "q": "Tracheal deviation in chest trauma suggests:",
      "opts": [
        "A. Simple rib fracture",
        "B. Tension pneumothorax with mediastinal shift",
        "C. Normal anatomical variation",
        "D. Hemothorax only"
      ],
      "ans": 1,
      "exp": "Tracheal deviation away from the injured side indicates tension pneumothorax — pressure buildup is shifting all mediastinal structures.",
      "level1": {
        "q": "What is a simple pneumothorax?",
        "opts": [
          "A. Tension pneumothorax with mediastinal shift",
          "B. Hemothorax only"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-34.q.06",
      "q": "Treatment for flail chest includes:",
      "opts": [
        "A. Stabilizing the flail segment with splints",
        "B. High-flow O2 and positive pressure ventilation if breathing is inadequate",
        "C. Tourniquet around chest",
        "D. Immediate needle decompression by EMT"
      ],
      "ans": 1,
      "exp": "Flail chest treatment: high-flow O2, positive pressure ventilation if breathing is inadequate, bulky dressing over segment, rapid transport.",
      "level1": {
        "q": "What is the treatment for flail chest?",
        "opts": [
          "A. High-flow O2 and positive pressure ventilation if breathing is inadequate",
          "B. Tourniquet around chest"
        ],
        "ans": 0
      }
    }
  ]
};
