// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch32: Chapter = {
  "id": "ch-32",
  "number": 32,
  "partId": "part-10",
  "title": "Spinal Trauma & Spine Motion Restriction",
  "cards": [
    {
      "id": "ch-32.fc.01",
      "q": "What is MILS and when is it used?",
      "a": "Manual Inline Stabilization — used to maintain the head and neck in neutral alignment from first contact until secured to a backboard."
    },
    {
      "id": "ch-32.fc.02",
      "q": "What are signs of spinal cord injury?",
      "a": "Weakness or paralysis, loss of sensation, loss of bladder/bowel control, priapism (males), diaphragmatic breathing, spinal shock."
    },
    {
      "id": "ch-32.fc.03",
      "q": "What is neurogenic shock?",
      "a": "Hypotension and bradycardia from spinal cord injury disrupting sympathetic nervous system — presents with warm, dry skin (opposite of hypovolemic shock)."
    },
    {
      "id": "ch-32.fc.04",
      "q": "What is priapism and what does it indicate?",
      "a": "Sustained penile erection — a sign of spinal cord injury indicating loss of autonomic nervous system control."
    },
    {
      "id": "ch-32.fc.05",
      "q": "What is the current approach to spinal immobilization?",
      "a": "Selective immobilization based on clinical criteria — not automatic backboarding of all trauma patients."
    },
    {
      "id": "ch-32.fc.06",
      "q": "What is rapid extrication?",
      "a": "Quickly moving a patient from a vehicle with spinal precautions when there is immediate life threat — sacrifices ideal immobilization for speed."
    },
    {
      "id": "ch-32.fc.07",
      "q": "What is the KED?",
      "a": "Kendrick Extrication Device — a vest-style device used to immobilize seated patients with suspected spinal injury before removal from a vehicle."
    },
    {
      "id": "ch-32.fc.08",
      "q": "What are criteria for spinal motion restriction?",
      "a": "High-risk MOI, altered LOC, midline spinal tenderness, neurological deficits, or distracting injuries making exam unreliable."
    }
  ],
  "notes": [
    {
      "id": "ch-32.n.01",
      "title": "Spinal Anatomy & Injury Mechanisms",
      "body": "The spine has 33 vertebrae: 7 cervical (most vulnerable), 12 thoracic, 5 lumbar, 5 sacral (fused), 4 coccygeal. Spinal cord runs through the vertebral canal. Flexion, extension, rotation, compression, and distraction forces can cause injury — cervical spine is most at risk.",
      "terms": [
        "Cervical",
        "Thoracic",
        "Lumbar",
        "Spinal cord",
        "Mechanism of injury"
      ]
    },
    {
      "id": "ch-32.n.02",
      "title": "Spinal Motion Restriction Principles",
      "body": "Selective immobilization replaces universal backboarding. Immobilize if: high-risk MOI, altered LOC, midline tenderness, neurological deficit, or distracting injury makes exam unreliable. MILS from first contact. C-collar restricts but does not eliminate motion — it is an adjunct, not a fix.",
      "terms": [
        "MILS",
        "C-collar",
        "Selective immobilization",
        "Midline tenderness",
        "Long backboard"
      ]
    },
    {
      "id": "ch-32.n.03",
      "title": "Spinal Cord Injury Presentations",
      "body": "Complete cord injury: total loss of motor and sensory below injury level. Incomplete: partial deficit with some function preserved. Neurogenic shock: vasodilation from loss of sympathetic tone — warm, dry skin, hypotension, paradoxical bradycardia (opposite of hypovolemic). Priapism indicates autonomic disruption.",
      "terms": [
        "Complete injury",
        "Incomplete injury",
        "Neurogenic shock",
        "Priapism",
        "Spinal shock"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-32.q.01",
      "q": "MILS should be maintained:",
      "opts": [
        "A. Until C-collar is applied only",
        "B. From first contact until patient is fully secured to backboard",
        "C. Only during transport",
        "D. Only if patient has neurological deficits"
      ],
      "ans": 1,
      "exp": "MILS must be maintained from initial patient contact until the patient is fully secured to the backboard and the head is immobilized."
    },
    {
      "id": "ch-32.q.02",
      "q": "Neurogenic shock presents with:",
      "opts": [
        "A. Tachycardia and cool, clammy skin",
        "B. Hypotension and bradycardia with warm, dry skin",
        "C. Hypertension and tachycardia",
        "D. Hypotension with tachycardia"
      ],
      "ans": 1,
      "exp": "Neurogenic shock results from loss of sympathetic tone — vasodilation causes warm, dry skin, hypotension, and paradoxical bradycardia."
    },
    {
      "id": "ch-32.q.03",
      "q": "Priapism in a trauma patient indicates:",
      "opts": [
        "A. Genitourinary trauma",
        "B. Spinal cord injury with autonomic disruption",
        "C. Normal physiological response",
        "D. Cardiovascular emergency"
      ],
      "ans": 1,
      "exp": "Priapism is a sustained erection caused by loss of autonomic nervous system control from spinal cord injury."
    },
    {
      "id": "ch-32.q.04",
      "q": "Current guidelines for spinal immobilization favor:",
      "opts": [
        "A. Universal backboarding of all trauma patients",
        "B. Selective immobilization based on clinical criteria",
        "C. Immobilization of all patients over 65",
        "D. Backboarding only when patient requests it"
      ],
      "ans": 1,
      "exp": "Research shows universal backboarding doesn't improve outcomes and may cause harm. Selective immobilization based on clinical assessment is now standard."
    },
    {
      "id": "ch-32.q.05",
      "q": "Rapid extrication is used when:",
      "opts": [
        "A. The patient requests quick removal",
        "B. There is an immediate life threat requiring rapid removal",
        "C. Standard extrication takes more than 5 minutes",
        "D. The patient is unresponsive alone"
      ],
      "ans": 1,
      "exp": "Rapid extrication sacrifices ideal immobilization when immediate danger exists — fire, explosion risk, or when immediate lifesaving care is needed."
    },
    {
      "id": "ch-32.q.06",
      "q": "The KED is used for:",
      "opts": [
        "A. All trauma patients",
        "B. Seated patients with suspected spinal injury prior to extrication",
        "C. Lying patients with pelvic fractures",
        "D. Head injuries only"
      ],
      "ans": 1,
      "exp": "The KED immobilizes the thorax and head, used to stabilize seated patients before extrication from vehicles."
    }
  ]
};
