// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch39: Chapter = {
  "id": "ch-39",
  "number": 39,
  "partId": "part-11",
  "title": "Geriatrics",
  "cards": [
    {
      "id": "ch-39.fc.01",
      "q": "Why do geriatric patients present atypically?",
      "a": "Physiological changes, multiple comorbidities, medications, and blunted inflammatory/compensatory responses mask classic symptoms."
    },
    {
      "id": "ch-39.fc.02",
      "q": "What is elder abuse?",
      "a": "Physical, emotional, sexual, financial, or neglectful mistreatment of an older adult — EMTs are mandated reporters in most states."
    },
    {
      "id": "ch-39.fc.03",
      "q": "What are signs of elder abuse or neglect?",
      "a": "Unexplained injuries, poor hygiene, malnutrition, fearfulness around caregiver, dehydration, conflicting accounts of injury mechanism."
    },
    {
      "id": "ch-39.fc.04",
      "q": "Why is trauma more dangerous in older patients?",
      "a": "Decreased physiologic reserve, osteoporosis, anticoagulants, and blunted compensatory response make even minor trauma potentially fatal."
    },
    {
      "id": "ch-39.fc.05",
      "q": "What is delirium vs. dementia?",
      "a": "Delirium: acute, reversible cognitive change — often from infection, medication, or metabolic cause. Dementia: chronic, progressive, irreversible."
    },
    {
      "id": "ch-39.fc.06",
      "q": "Why is medication history especially important in geriatric patients?",
      "a": "Polypharmacy increases risk of drug interactions, adverse effects, and toxicity — beta-blockers may blunt the tachycardia of shock."
    },
    {
      "id": "ch-39.fc.07",
      "q": "What is the leading cause of injury-related death in geriatric patients?",
      "a": "Falls — the leading cause of hip fractures, traumatic brain injury, and significant morbidity/mortality in older adults."
    },
    {
      "id": "ch-39.fc.08",
      "q": "What physiological change affects blood pressure measurement in the elderly?",
      "a": "Chronic hypertension is common — what appears 'normal' BP for a young adult may represent hypotension in an elder who is normally at 180 systolic."
    }
  ],
  "notes": [
    {
      "id": "ch-39.n.01",
      "title": "Physiologic Changes of Aging",
      "body": "Cardiovascular: decreased cardiac reserve, stiff vessels, higher resting BP. Respiratory: decreased lung compliance, weaker cough reflex, reduced O2 reserve. Neurological: slower reflexes, decreased pain sensation, confusion as common AMS sign. Musculoskeletal: osteoporosis, reduced muscle mass.",
      "terms": [
        "Cardiac reserve",
        "Osteoporosis",
        "Polypharmacy",
        "Blunted response",
        "Sensory deficit"
      ]
    },
    {
      "id": "ch-39.n.02",
      "title": "Geriatric Trauma Considerations",
      "body": "Beta-blockers prevent compensatory tachycardia — elderly trauma patients may not show tachycardia of shock. Anticoagulants increase bleeding risk dramatically. Thin, fragile skin tears easily. Minor MOI can cause significant injury. Assume serious injury until proven otherwise with geriatric trauma.",
      "terms": [
        "Beta-blocker",
        "Anticoagulant",
        "Osteoporosis",
        "Physiologic reserve",
        "Falls"
      ]
    },
    {
      "id": "ch-39.n.03",
      "title": "Elder Abuse & Neglect",
      "body": "Types: physical, emotional, sexual, financial exploitation, neglect, abandonment, self-neglect. EMTs are mandated reporters in most states. Document objectively — photograph injuries if allowed by protocol. Separate patient from suspected abuser to obtain private history. Document exact patient statements.",
      "terms": [
        "Mandated reporter",
        "Elder abuse",
        "Neglect",
        "Documentation",
        "Objective findings"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-39.q.01",
      "q": "Geriatric patients may not show tachycardia in shock because:",
      "opts": [
        "A. They have higher heart rates normally",
        "B. Beta-blockers blunt compensatory tachycardia",
        "C. Their hearts pump more efficiently",
        "D. Shock always presents atypically in elderly"
      ],
      "ans": 1,
      "exp": "Many elderly patients take beta-blockers for cardiac conditions, preventing the compensatory tachycardia that normally indicates developing shock.",
      "easy": {
        "q": "Why is medication history especially important in geriatric patients?",
        "opts": [
          "A. Beta-blockers blunt compensatory tachycardia",
          "B. Their hearts pump more efficiently"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Beta-blockers prevent compensatory tachycardia. Based on this presentation, geriatric patients may not show tachycardia in shock because?",
        "opts": [
          "A. Shock always presents atypically in elderly",
          "B. They have higher heart rates normally",
          "C. Beta-blockers blunt compensatory tachycardia",
          "D. Their hearts pump more efficiently"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-39.q.02",
      "q": "The leading cause of injury death in geriatric patients is:",
      "opts": [
        "A. Motor vehicle crashes",
        "B. Burns",
        "C. Falls",
        "D. Assaults"
      ],
      "ans": 2,
      "exp": "Falls are the #1 cause of injury-related death in older adults, leading to hip fractures, TBI, and serious complications.",
      "easy": {
        "q": "What is the leading cause of injury-related death in geriatric patients?",
        "opts": [
          "A. Falls",
          "B. Burns"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Beta-blockers prevent compensatory tachycardia. Based on this presentation, the leading cause of injury death in geriatric patients is?",
        "opts": [
          "A. Motor vehicle crashes",
          "B. Assaults",
          "C. Falls",
          "D. Burns"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-39.q.03",
      "q": "Delirium differs from dementia in that delirium is:",
      "opts": [
        "A. Chronic and progressive",
        "B. Acute and often reversible",
        "C. Caused by genetics only",
        "D. Never reversible"
      ],
      "ans": 1,
      "exp": "Delirium is an acute change in mental status — often caused by infection, medication, or metabolic disturbance and is potentially reversible.",
      "easy": {
        "q": "What is delirium vs. dementia?",
        "opts": [
          "A. Acute and often reversible",
          "B. Never reversible"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Delirium differs from dementia in that delirium is?",
        "opts": [
          "A. Chronic and progressive",
          "B. Caused by genetics only",
          "C. Acute and often reversible",
          "D. Never reversible"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-39.q.04",
      "q": "EMTs are mandated reporters for elder abuse, which means:",
      "opts": [
        "A. They may report if they choose",
        "B. They are legally required to report suspected abuse",
        "C. Only nurses must report",
        "D. Reports are optional unless injury is severe"
      ],
      "ans": 1,
      "exp": "In most states, EMTs are mandated reporters required by law to report suspected elder abuse or neglect to appropriate authorities.",
      "easy": {
        "q": "What is EMTs are mandated reporters for elder abuse, which means?",
        "opts": [
          "A. They are legally required to report suspected abuse",
          "B. Only nurses must report"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Types: physical, emotional, sexual, financial exploitation, neglect, abandonment, self-neglect. Based on this presentation, EMTs are mandated reporters for elder abuse, which means?",
        "opts": [
          "A. Reports are optional unless injury is severe",
          "B. They may report if they choose",
          "C. They are legally required to report suspected abuse",
          "D. Only nurses must report"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-39.q.05",
      "q": "Signs that should raise suspicion for elder abuse include:",
      "opts": [
        "A. Patient living independently",
        "B. Unexplained injuries, poor hygiene, and fearfulness around caregiver",
        "C. Multiple medications",
        "D. History of diabetes"
      ],
      "ans": 1,
      "exp": "Unexplained injuries inconsistent with the mechanism, poor hygiene, malnutrition, and fearful behavior are red flags for elder abuse.",
      "easy": {
        "q": "What are signs of elder abuse or neglect?",
        "opts": [
          "A. Unexplained injuries, poor hygiene, and fearfulness around caregiver",
          "B. History of diabetes"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Types: physical, emotional, sexual, financial exploitation, neglect, abandonment, self-neglect. Based on this presentation, signs that should raise suspicion for elder abuse include?",
        "opts": [
          "A. Patient living independently",
          "B. Multiple medications",
          "C. Unexplained injuries, poor hygiene, and fearfulness around caregiver",
          "D. History of diabetes"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-39.q.06",
      "q": "Anticoagulant medications in elderly trauma patients are important because:",
      "opts": [
        "A. They improve healing",
        "B. They increase bleeding risk, making even minor trauma dangerous",
        "C. They prevent clotting at injury sites",
        "D. They have no effect on trauma"
      ],
      "ans": 1,
      "exp": "Anticoagulants (warfarin, aspirin, NOACs) increase bleeding risk significantly — minor trauma can cause life-threatening internal hemorrhage.",
      "easy": {
        "q": "Why is trauma more dangerous in older patients?",
        "opts": [
          "A. They increase bleeding risk, making even minor trauma dangerous",
          "B. They improve healing"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Beta-blockers prevent compensatory tachycardia. Based on this presentation, anticoagulant medications in elderly trauma patients are important because?",
        "opts": [
          "A. They prevent clotting at injury sites",
          "B. They have no effect on trauma",
          "C. They increase bleeding risk, making even minor trauma dangerous",
          "D. They improve healing"
        ],
        "ans": 2
      }
    }
  ]
};
