// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch37: Chapter = {
  "id": "ch-37",
  "number": 37,
  "partId": "part-11",
  "title": "Obstetrics & Care of the Newborn",
  "cards": [
    {
      "id": "ch-37.fc.01",
      "q": "What are the three stages of labor?",
      "a": "Stage 1: cervical dilation. Stage 2: delivery of the baby. Stage 3: delivery of the placenta."
    },
    {
      "id": "ch-37.fc.02",
      "q": "What is crowning?",
      "a": "Presentation of the baby's head at the vaginal opening — delivery is imminent, do not transport."
    },
    {
      "id": "ch-37.fc.03",
      "q": "How do you handle the umbilical cord around the baby's neck?",
      "a": "Try to slip the cord over the head. If too tight, clamp and cut before delivery."
    },
    {
      "id": "ch-37.fc.04",
      "q": "When should you clamp and cut the cord?",
      "a": "After delivery, once the cord stops pulsating — clamp 6-8 inches from infant, then again a few inches further, cut between clamps."
    },
    {
      "id": "ch-37.fc.05",
      "q": "What is a prolapsed cord?",
      "a": "Umbilical cord precedes the baby through the birth canal — a true obstetric emergency causing fetal hypoxia."
    },
    {
      "id": "ch-37.fc.06",
      "q": "How do you treat a prolapsed cord?",
      "a": "Position mother knee-chest, elevate presenting part off cord with gloved hand, high-flow O2, rapid transport — do NOT pull the cord."
    },
    {
      "id": "ch-37.fc.07",
      "q": "What is placenta previa?",
      "a": "Placenta implanted over the cervical os — causes painless, bright red vaginal bleeding in late pregnancy."
    },
    {
      "id": "ch-37.fc.08",
      "q": "What are Apgar scores?",
      "a": "1 and 5 minute assessment: Appearance (color), Pulse, Grimace, Activity (tone), Respiration. Max score = 10."
    }
  ],
  "notes": [
    {
      "id": "ch-37.n.01",
      "title": "Normal Delivery",
      "body": "Transport if time allows. If delivery imminent (crowning), prepare for field delivery. Control head delivery with gentle pressure, check for nuchal cord, suction mouth then nose, deliver shoulders and body. Clamp and cut cord after pulsation stops. Keep infant warm — dry, stimulate, wrap.",
      "terms": [
        "Crowning",
        "Nuchal cord",
        "Suction",
        "Clamp and cut",
        "Warmth"
      ]
    },
    {
      "id": "ch-37.n.02",
      "title": "Newborn Resuscitation",
      "body": "Dry, warm, stimulate, and position. If breathing inadequate: BVM at 40-60 breaths/min. If HR <60 despite 30 sec of PPV: start compressions at 3:1 ratio. Newborns lose heat rapidly — keep warm throughout resuscitation.",
      "terms": [
        "Apgar",
        "PPV",
        "3:1 ratio",
        "Newborn warmth",
        "Stimulation"
      ]
    },
    {
      "id": "ch-37.n.03",
      "title": "Obstetric Complications",
      "body": "Placenta previa: painless bright red bleeding. Abruptio placentae: painful dark bleeding, rigid uterus. Prolapsed cord: elevate presenting part, knee-chest, rapid transport. Ectopic pregnancy: abdominal pain + early pregnancy vaginal bleeding — shock risk. Preeclampsia: HTN + proteinuria.",
      "terms": [
        "Placenta previa",
        "Abruptio placentae",
        "Ectopic pregnancy",
        "Prolapsed cord",
        "Preeclampsia"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-37.q.01",
      "q": "Crowning means:",
      "opts": [
        "A. Amniotic sac has ruptured",
        "B. Placenta is delivering",
        "C. Baby's head is visible at vaginal opening",
        "D. Cord is prolapsed"
      ],
      "ans": 2,
      "exp": "Crowning is when the presenting part (usually head) is visible at the vaginal opening — delivery is imminent, do not attempt to transport.",
      "level1": {
        "q": "What is crowning?",
        "opts": [
          "A. Baby's head is visible at vaginal opening",
          "B. Cord is prolapsed"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-37.q.02",
      "q": "A prolapsed cord is managed by:",
      "opts": [
        "A. Pushing the cord back in",
        "B. Elevating presenting part off cord, knee-chest position, rapid transport",
        "C. Clamping and cutting the cord",
        "D. Positioning supine"
      ],
      "ans": 1,
      "exp": "Keep cord moist, elevate presenting part off cord with gloved hand, knee-chest position reduces pressure. Never pull on the cord. Rapid transport.",
      "level1": {
        "q": "How do you treat a prolapsed cord?",
        "opts": [
          "A. Elevating presenting part off cord, knee-chest position, rapid transport",
          "B. Positioning supine"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-37.q.03",
      "q": "Placenta previa presents with:",
      "opts": [
        "A. Painful dark red bleeding",
        "B. Rigid uterus",
        "C. Painless bright red vaginal bleeding",
        "D. Abdominal trauma"
      ],
      "ans": 2,
      "exp": "Placenta previa: placenta covers cervical os — painless bright red bleeding. Abruptio placentae is painful with dark blood.",
      "level1": {
        "q": "What is placenta previa?",
        "opts": [
          "A. Painless bright red vaginal bleeding",
          "B. Rigid uterus"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-37.q.04",
      "q": "The cord should be clamped:",
      "opts": [
        "A. Immediately at delivery",
        "B. After cord stops pulsating, 6-8 inches from infant",
        "C. Before the placenta delivers",
        "D. Only if cord is around neck"
      ],
      "ans": 1,
      "exp": "Wait for cord pulsation to stop, clamp 6-8 inches from infant and again a few inches further, then cut between clamps.",
      "level1": {
        "q": "When should you clamp and cut the cord?",
        "opts": [
          "A. After cord stops pulsating, 6-8 inches from infant",
          "B. Immediately at delivery"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-37.q.05",
      "q": "Apgar score is assessed at:",
      "opts": [
        "A. Delivery and 10 minutes",
        "B. 1 minute and 5 minutes after birth",
        "C. 2 and 10 minutes",
        "D. Only at 5 minutes"
      ],
      "ans": 1,
      "exp": "Apgar (Appearance, Pulse, Grimace, Activity, Respiration) is assessed at 1 and 5 minutes to evaluate newborn status.",
      "level1": {
        "q": "What are Apgar scores?",
        "opts": [
          "A. 1 minute and 5 minutes after birth",
          "B. 2 and 10 minutes"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-37.q.06",
      "q": "To keep a newborn warm after delivery:",
      "opts": [
        "A. Submerge in warm water",
        "B. Dry thoroughly, wrap in blanket, cover head",
        "C. Place near vehicle heater",
        "D. Leave undressed to monitor color"
      ],
      "ans": 1,
      "exp": "Newborns lose heat rapidly through evaporation. Dry immediately, wrap in warm blanket, and cover the large surface area of the head.",
      "level1": {
        "q": "What is To keep a newborn warm after delivery?",
        "opts": [
          "A. Dry thoroughly, wrap in blanket, cover head",
          "B. Submerge in warm water"
        ],
        "ans": 0
      }
    }
  ]
};
