// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch36: Chapter = {
  "id": "ch-36",
  "number": 36,
  "partId": "part-10",
  "title": "Trauma in Special Populations",
  "cards": [
    {
      "id": "ch-36.fc.01",
      "q": "What is the uteroplacental unit and why does it matter in trauma?",
      "a": "The placenta supplies oxygen/nutrients to the fetus — maternal shock or hypotension reduces placental perfusion, causing fetal distress or death before maternal vitals change."
    },
    {
      "id": "ch-36.fc.02",
      "q": "How do maternal injuries relate to fetal distress?",
      "a": "Maternal hypoxia, hypotension, or shock reduces blood flow to the placenta — fetus can deteriorate even when mother appears stable. Always assess pregnancy and monitor both patients."
    },
    {
      "id": "ch-36.fc.03",
      "q": "What is the assessment-based approach to trauma in pregnancy?",
      "a": "Standard trauma assessment plus pregnancy history, fundal height, fetal viability assessment, left lateral tilt, and high index of suspicion for occult injury and placental abruption."
    },
    {
      "id": "ch-36.fc.04",
      "q": "How should a pregnant trauma patient be positioned?",
      "a": "Left lateral tilt (or backboard tilted left) to prevent the uterus from compressing the inferior vena cava and reducing cardiac output."
    },
    {
      "id": "ch-36.fc.05",
      "q": "What anatomical changes in pregnancy affect trauma management?",
      "a": "Enlarged uterus (abdominal organ displacement, IVC compression supine), increased blood volume (can mask shock), and loosened ligaments."
    },
    {
      "id": "ch-36.fc.06",
      "q": "What physiological changes in older adults affect trauma assessment?",
      "a": "Blunted tachycardia (beta-blockers, aging heart), decreased physiologic reserve, osteoporosis (fractures from minor MOI), anticoagulants (increased bleeding)."
    },
    {
      "id": "ch-36.fc.07",
      "q": "Why is geriatric trauma often under-triaged?",
      "a": "Vital signs may not show expected shock response — elderly patients can be in severe shock with near-normal heart rate and BP due to medications and age."
    },
    {
      "id": "ch-36.fc.08",
      "q": "What is placental abruption and how does it present?",
      "a": "Placenta separates from uterine wall after trauma — abdominal pain, vaginal bleeding, uterine tenderness, and fetal distress. Obstetric emergency."
    }
  ],
  "notes": [
    {
      "id": "ch-36.n.01",
      "title": "Key Terms & Pregnancy Trauma (Obj 36-1, 36-5)",
      "body": "Key terms: uteroplacental unit, placental abruption, supine hypotensive syndrome, fundal height. Maternal injuries directly threaten the fetus — maternal hypoxia and hypotension reduce placental perfusion. Fetal distress or death can occur before maternal vital signs reflect severity. Placental abruption from blunt abdominal trauma causes fetal mortality — suspect with abdominal pain, vaginal bleeding, and rigid uterus after trauma.",
      "terms": [
        "Uteroplacental unit",
        "Placental abruption",
        "Fetal distress",
        "Fundal height",
        "Supine hypotensive syndrome"
      ]
    },
    {
      "id": "ch-36.n.02",
      "title": "Assessment-Based Approach to Pregnancy Trauma (Obj 36-6)",
      "body": "Perform standard trauma assessment with pregnancy modifications: ask LMP/gravida/para, assess fundal height, evaluate fetal viability if trained. Form field impression including both mother and fetus. Care: left lateral tilt to relieve IVC compression, high-flow O2, treat maternal shock aggressively (saves fetus), rapid transport to trauma center with OB capability. Do not withhold treatment due to pregnancy.",
      "terms": [
        "Field impression",
        "Left lateral tilt",
        "IVC compression",
        "Maternal resuscitation",
        "OB capability"
      ]
    },
    {
      "id": "ch-36.n.03",
      "title": "Geriatric Trauma Considerations (Obj 36-8)",
      "body": "Anatomical changes: osteoporosis (fractures from low-energy MOI), decreased skin elasticity, reduced chest wall compliance. Physiological changes: blunted heart rate response to shock (beta-blockers, pacemakers), decreased cardiac reserve, reduced renal function. Anticoagulants increase internal bleeding risk. Polypharmacy complicates assessment. Maintain high index of suspicion — elderly patients need trauma center triage even with seemingly minor mechanisms.",
      "terms": [
        "Osteoporosis",
        "Beta-blockers",
        "Anticoagulants",
        "Blunted shock response",
        "Polypharmacy",
        "Low-energy MOI"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-36.q.01",
      "q": "Maternal hypotension in a pregnant trauma patient:",
      "opts": [
        "A. Has no effect on the fetus",
        "B. Reduces placental perfusion and can cause fetal distress before maternal vitals worsen",
        "C. Only matters in the third trimester",
        "D. Should be treated by placing the patient flat on her back"
      ],
      "ans": 1,
      "exp": "Maternal shock reduces blood flow to the placenta — the fetus can deteriorate even when the mother appears relatively stable.",
      "level1": {
        "q": "What is the uteroplacental unit and why does it matter in trauma?",
        "opts": [
          "A. Reduces placental perfusion and can cause fetal distress before maternal vitals worsen",
          "B. Has no effect on the fetus"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.02",
      "q": "A pregnant trauma patient should be positioned with:",
      "opts": [
        "A. Supine flat on her back",
        "B. Left lateral tilt to relieve inferior vena cava compression",
        "C. Right lateral tilt",
        "D. Prone positioning"
      ],
      "ans": 1,
      "exp": "The enlarged uterus compresses the IVC when supine — left lateral tilt maintains maternal cardiac output and placental perfusion.",
      "level1": {
        "q": "How should a pregnant trauma patient be positioned?",
        "opts": [
          "A. Left lateral tilt to relieve inferior vena cava compression",
          "B. Prone positioning"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.03",
      "q": "Placental abruption after trauma may present with:",
      "opts": [
        "A. No symptoms until delivery",
        "B. Abdominal pain, vaginal bleeding, and uterine tenderness",
        "C. Only maternal tachycardia",
        "D. Isolated headache"
      ],
      "ans": 1,
      "exp": "Placental abruption separates the placenta from the uterine wall — presents with pain, bleeding, rigid/tender uterus, and fetal compromise.",
      "level1": {
        "q": "What is placental abruption and how does it present?",
        "opts": [
          "A. Abdominal pain, vaginal bleeding, and uterine tenderness",
          "B. Isolated headache"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.04",
      "q": "In the assessment-based approach to pregnancy trauma, you should:",
      "opts": [
        "A. Skip the primary survey to focus on the fetus",
        "B. Perform standard trauma assessment with pregnancy-specific additions",
        "C. Transport only to an OB clinic regardless of injuries",
        "D. Withhold oxygen to prevent fetal harm"
      ],
      "ans": 1,
      "exp": "Use the standard trauma assessment framework plus pregnancy history, fundal height, and fetal assessment — treat the mother to save the fetus.",
      "level1": {
        "q": "What is the assessment-based approach to trauma in pregnancy?",
        "opts": [
          "A. Perform standard trauma assessment with pregnancy-specific additions",
          "B. Withhold oxygen to prevent fetal harm"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.05",
      "q": "Geriatric trauma patients may not show tachycardia in shock because:",
      "opts": [
        "A. Their hearts respond faster than younger patients",
        "B. Beta-blockers and age-related changes blunt the compensatory heart rate response",
        "C. They always have hypertension",
        "D. Shock does not occur in elderly patients"
      ],
      "ans": 1,
      "exp": "Many elderly patients take beta-blockers or have pacemakers that mask the tachycardia normally seen in compensatory shock.",
      "level1": {
        "q": "Why is geriatric trauma often under-triaged?",
        "opts": [
          "A. Beta-blockers and age-related changes blunt the compensatory heart rate response",
          "B. They always have hypertension"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.06",
      "q": "Osteoporosis in geriatric patients means:",
      "opts": [
        "A. They cannot fracture bones",
        "B. Fractures can occur from low-energy mechanisms that would not injure younger patients",
        "C. Only the skull is affected",
        "D. Spinal injury is impossible"
      ],
      "ans": 1,
      "exp": "Osteoporotic bone fractures easily — a fall from standing or minor MVC can cause serious fractures in elderly patients.",
      "level1": {
        "q": "What physiological changes in older adults affect trauma assessment?",
        "opts": [
          "A. Fractures can occur from low-energy mechanisms that would not injure younger patients",
          "B. They cannot fracture bones"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.07",
      "q": "Anticoagulant use in elderly trauma patients increases the risk of:",
      "opts": [
        "A. Decreased bleeding",
        "B. Internal bleeding and delayed hemorrhage from minor injuries",
        "C. Only external bleeding",
        "D. Allergic reactions"
      ],
      "ans": 1,
      "exp": "Anticoagulants (warfarin, DOACs) impair clotting — elderly patients on these medications bleed more and longer from injuries.",
      "level1": {
        "q": "What physiological changes in older adults affect trauma assessment?",
        "opts": [
          "A. Internal bleeding and delayed hemorrhage from minor injuries",
          "B. Decreased bleeding"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-36.q.08",
      "q": "When managing trauma in pregnancy, the best way to help the fetus is to:",
      "opts": [
        "A. Avoid all treatment that might affect the fetus",
        "B. Aggressively resuscitate the mother — fetal survival depends on maternal survival",
        "C. Focus only on fetal monitoring and delay maternal treatment",
        "D. Transport to any hospital regardless of trauma capability"
      ],
      "ans": 1,
      "exp": "Treat the mother aggressively — maternal resuscitation is the primary intervention for fetal survival. Do not withhold care due to pregnancy.",
      "level1": {
        "q": "What is the uteroplacental unit and why does it matter in trauma?",
        "opts": [
          "A. Aggressively resuscitate the mother — fetal survival depends on maternal survival",
          "B. Avoid all treatment that might affect the fetus"
        ],
        "ans": 0
      }
    }
  ]
};
