// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch33: Chapter = {
  "id": "ch-33",
  "number": 33,
  "partId": "part-10",
  "title": "Eye, Face & Neck Trauma",
  "cards": [
    {
      "id": "ch-33.fc.01",
      "q": "What are signs of a serious eye injury?",
      "a": "Decreased or absent vision, pain, foreign body sensation, irregular pupil, blood visible in anterior chamber (hyphema), penetrating object."
    },
    {
      "id": "ch-33.fc.02",
      "q": "How do you treat a chemical burn to the eye?",
      "a": "Irrigate immediately with large amounts of water or saline for at least 20 minutes — do not delay transport for irrigation, irrigate en route."
    },
    {
      "id": "ch-33.fc.03",
      "q": "How do you treat an impaled object in the eye?",
      "a": "Do NOT remove. Stabilize with a paper cup or cone over the eye, cover both eyes (reducing movement), transport immediately."
    },
    {
      "id": "ch-33.fc.04",
      "q": "What is the treatment for an avulsed (knocked out) tooth?",
      "a": "Handle by crown (not root), rinse gently, replace in socket if possible, or transport in milk/saline — reimplantation is time-sensitive."
    },
    {
      "id": "ch-33.fc.05",
      "q": "What are signs of a Le Fort fracture?",
      "a": "Midface instability, 'floating' or mobile midface, malocclusion (teeth don't align), facial swelling, and airway compromise."
    },
    {
      "id": "ch-33.fc.06",
      "q": "What is the primary concern with facial trauma?",
      "a": "Airway compromise — facial injuries can cause bleeding, swelling, and fractures that rapidly obstruct the airway."
    },
    {
      "id": "ch-33.fc.07",
      "q": "How do you treat a nosebleed (epistaxis) in the field?",
      "a": "Pinch the fleshy part of the nose (not the bridge), lean slightly forward, apply pressure for 15 minutes. Do NOT tilt head back."
    },
    {
      "id": "ch-33.fc.08",
      "q": "What is the treatment for an open wound to the throat?",
      "a": "Occlusive dressing immediately — risk of air embolism from jugular vein injury and airway obstruction from hematoma."
    }
  ],
  "notes": [
    {
      "id": "ch-33.n.01",
      "title": "Eye Injuries",
      "body": "Foreign bodies: do not rub — gently irrigate. Chemical burns: immediate copious irrigation for 20+ minutes — alkaline burns (bleach) penetrate deeper and longer. Impaled objects: stabilize, cover both eyes. Hyphema: blood in anterior chamber — cover, upright position, avoid aspirin.",
      "terms": [
        "Hyphema",
        "Irrigation",
        "Impaled object",
        "Corneal abrasion",
        "Cover both eyes"
      ]
    },
    {
      "id": "ch-33.n.02",
      "title": "Facial Trauma",
      "body": "Facial injuries are dramatic but rarely immediately life-threatening unless they compromise the airway. Assess airway first: bleeding into the oropharynx, fractures, avulsed teeth, and soft tissue swelling can all obstruct. Midface instability suggests Le Fort fracture.",
      "terms": [
        "Airway priority",
        "Le Fort fracture",
        "Midface instability",
        "Epistaxis",
        "Malocclusion"
      ]
    },
    {
      "id": "ch-33.n.03",
      "title": "Neck Trauma",
      "body": "Neck injuries are high-stakes: major vessels (carotid, jugular), airway (trachea/larynx), and spinal cord all pass through. Open wounds: occlusive dressing immediately. Blunt neck trauma: tracheal injury, hematoma, laryngeal fracture — may cause rapid airway deterioration.",
      "terms": [
        "Occlusive dressing",
        "Air embolism",
        "Tracheal injury",
        "Laryngeal fracture",
        "Hematoma"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-33.q.01",
      "q": "An impaled object in the eye should be:",
      "opts": [
        "A. Gently removed with tweezers",
        "B. Left in place, stabilized, both eyes covered",
        "C. Irrigated away",
        "D. Removed if small"
      ],
      "ans": 1,
      "exp": "Never remove an impaled eye object — stabilize with a paper cup or cone, cover both eyes to reduce movement, transport immediately."
    },
    {
      "id": "ch-33.q.02",
      "q": "Chemical eye burns are treated by:",
      "opts": [
        "A. Patching the eye and transporting",
        "B. Immediate copious irrigation with water for 20+ minutes",
        "C. Neutralizing with an opposite pH solution",
        "D. Covering and waiting for ALS"
      ],
      "ans": 1,
      "exp": "Immediate, copious water irrigation for 20+ minutes is life-saving for chemical eye burns. Never delay to find a neutralizing agent."
    },
    {
      "id": "ch-33.q.03",
      "q": "Primary concern with significant facial trauma is:",
      "opts": [
        "A. Cosmetic appearance",
        "B. Airway compromise",
        "C. Pain management",
        "D. Spinal injury only"
      ],
      "ans": 1,
      "exp": "Facial trauma can rapidly compromise the airway through bleeding, swelling, and fractures — airway assessment and management is the top priority."
    },
    {
      "id": "ch-33.q.04",
      "q": "To treat a nosebleed (epistaxis), you should:",
      "opts": [
        "A. Tilt head back and pinch bridge",
        "B. Tilt slightly forward and pinch fleshy part of nose",
        "C. Pack with gauze only",
        "D. Apply ice to the forehead"
      ],
      "ans": 1,
      "exp": "Pinch the fleshy part of the nose (not the bridge) with the patient leaning slightly forward — prevents blood from draining into the airway."
    },
    {
      "id": "ch-33.q.05",
      "q": "An open wound to the throat requires:",
      "opts": [
        "A. Standard gauze dressing",
        "B. Immediate occlusive dressing",
        "C. Direct pressure only",
        "D. Cervical collar before dressing"
      ],
      "ans": 1,
      "exp": "Open neck wounds risk fatal air embolism from jugular vein laceration — apply an occlusive dressing immediately."
    },
    {
      "id": "ch-33.q.06",
      "q": "An avulsed tooth should be transported in:",
      "opts": [
        "A. Dry gauze",
        "B. Ice water",
        "C. The patient's own blood or milk/saline",
        "D. A plastic bag with air"
      ],
      "ans": 2,
      "exp": "Avulsed teeth transported in milk, saline, or the patient's saliva have the best reimplantation outcomes. Never let the root dry out."
    }
  ]
};
