// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch35: Chapter = {
  "id": "ch-35",
  "number": 35,
  "partId": "part-10",
  "title": "Abdominal & Genitourinary Trauma",
  "cards": [
    {
      "id": "ch-35.fc.01",
      "q": "What are signs of abdominal trauma?",
      "a": "Pain, tenderness, guarding, rigidity, distension, bruising (seat belt sign, flank ecchymosis), and signs of shock."
    },
    {
      "id": "ch-35.fc.02",
      "q": "What is an evisceration?",
      "a": "Abdominal organs (usually intestines) protruding through an open abdominal wound — cover with moist sterile dressing, do NOT push back in."
    },
    {
      "id": "ch-35.fc.03",
      "q": "What is the 'seat belt sign'?",
      "a": "Bruising across the abdomen from a seat belt during a high-speed MVC — associated with significant internal organ injury."
    },
    {
      "id": "ch-35.fc.04",
      "q": "What is Grey Turner's sign?",
      "a": "Ecchymosis (bruising) of the flanks — indicates retroperitoneal bleeding (behind the peritoneum), often from kidney injury or aortic dissection."
    },
    {
      "id": "ch-35.fc.05",
      "q": "What is Cullen's sign?",
      "a": "Periumbilical bruising (around the navel) — indicates intra-abdominal bleeding, often associated with pancreatic injury or ruptured aortic aneurysm."
    },
    {
      "id": "ch-35.fc.06",
      "q": "What are signs of bladder trauma?",
      "a": "Inability to urinate, hematuria (blood in urine), pelvic pain, and pelvic tenderness — often associated with pelvic fractures."
    },
    {
      "id": "ch-35.fc.07",
      "q": "How do you treat an evisceration?",
      "a": "Cover with moist sterile dressing (saline-soaked gauze), cover with occlusive dressing to retain moisture, position supine with knees up, rapid transport."
    },
    {
      "id": "ch-35.fc.08",
      "q": "What is a pelvic fracture and why is it serious?",
      "a": "Fracture of the pelvic ring — can cause massive internal bleeding (2-3+ liters) into the pelvis from disrupted vessels."
    }
  ],
  "notes": [
    {
      "id": "ch-35.n.01",
      "title": "Abdominal Trauma Assessment",
      "body": "Blunt abdominal trauma is difficult to assess — internal organs can bleed significantly without external signs. Solid organs (liver, spleen) bleed profusely. Hollow organs (bowel, bladder) leak contents causing peritonitis. Assess for tenderness, guarding, rigidity, distension, and bruising patterns.",
      "terms": [
        "Solid organ",
        "Hollow organ",
        "Guarding",
        "Rigidity",
        "Peritonitis"
      ]
    },
    {
      "id": "ch-35.n.02",
      "title": "Specific Abdominal Injuries",
      "body": "Evisceration: moist sterile cover, do not replace organs, knees up. Impaled objects: stabilize in place. Seat belt sign: significant MOI, assume internal injury. Grey Turner's/Cullen's sign: late signs of internal bleeding (may not appear for hours). All require rapid transport.",
      "terms": [
        "Evisceration",
        "Seat belt sign",
        "Grey Turner's sign",
        "Cullen's sign",
        "Impaled object"
      ]
    },
    {
      "id": "ch-35.n.03",
      "title": "Pelvic & Genitourinary Trauma",
      "body": "Pelvic fractures are life-threatening from massive blood loss. Do not compress the pelvis to check for stability — do it once only. Pelvic binders reduce blood loss. Genitourinary trauma: hematuria, inability to urinate, priapism in spinal injury. Female patients: consider pregnancy.",
      "terms": [
        "Pelvic fracture",
        "Pelvic binder",
        "Hematuria",
        "Retroperitoneal",
        "Blood loss"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-35.q.01",
      "q": "An evisceration is treated by:",
      "opts": [
        "A. Pushing organs back into the abdomen",
        "B. Covering with moist sterile dressing, do not replace organs",
        "C. Applying direct pressure to the organs",
        "D. Leaving uncovered to transport quickly"
      ],
      "ans": 1,
      "exp": "Cover eviscerated organs with moist sterile gauze — do not push them back in, do not dry them out. Position supine with knees flexed.",
      "easy": {
        "q": "What is an evisceration?",
        "opts": [
          "A. Covering with moist sterile dressing, do not replace organs",
          "B. Pushing organs back into the abdomen"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. An evisceration is treated by?",
        "opts": [
          "A. Applying direct pressure to the organs",
          "B. Leaving uncovered to transport quickly",
          "C. Covering with moist sterile dressing, do not replace organs",
          "D. Pushing organs back into the abdomen"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-35.q.02",
      "q": "The 'seat belt sign' indicates:",
      "opts": [
        "A. The patient was wearing a seat belt",
        "B. Significant MOI with possible internal organ injury",
        "C. Superficial abrasion only",
        "D. No internal injury if seat belt was on"
      ],
      "ans": 1,
      "exp": "Seat belt sign (bruising across the abdomen) indicates a significant deceleration force was applied — associated with serious internal injuries.",
      "easy": {
        "q": "What is the 'seat belt sign'?",
        "opts": [
          "A. Significant MOI with possible internal organ injury",
          "B. Superficial abrasion only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Evisceration: moist sterile cover, do not replace organs, knees up. Based on this presentation, the 'seat belt sign' indicates?",
        "opts": [
          "A. No internal injury if seat belt was on",
          "B. The patient was wearing a seat belt",
          "C. Significant MOI with possible internal organ injury",
          "D. Superficial abrasion only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-35.q.03",
      "q": "Grey Turner's sign is:",
      "opts": [
        "A. Periumbilical bruising",
        "B. Flank bruising indicating retroperitoneal bleeding",
        "C. Chest wall bruising",
        "D. Bruising around the eye"
      ],
      "ans": 1,
      "exp": "Grey Turner's sign = flank ecchymosis (bruising) indicating retroperitoneal bleeding, often from kidney injury or major vessel disruption.",
      "easy": {
        "q": "What is Grey Turner's sign?",
        "opts": [
          "A. Flank bruising indicating retroperitoneal bleeding",
          "B. Chest wall bruising"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Evisceration: moist sterile cover, do not replace organs, knees up. Based on this presentation, grey Turner's sign is?",
        "opts": [
          "A. Bruising around the eye",
          "B. Periumbilical bruising",
          "C. Flank bruising indicating retroperitoneal bleeding",
          "D. Chest wall bruising"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-35.q.04",
      "q": "Pelvic fractures are dangerous because:",
      "opts": [
        "A. They cause immediate paralysis",
        "B. Massive internal bleeding (2-3+ liters) can occur into the pelvis",
        "C. They always cause bladder rupture",
        "D. They are immediately visible on exam"
      ],
      "ans": 1,
      "exp": "Pelvic fractures can cause massive internal hemorrhage from disrupted pelvic vessels — 2-3 liters or more, causing severe shock.",
      "easy": {
        "q": "What is a pelvic fracture and why is it serious?",
        "opts": [
          "A. Massive internal bleeding (2-3+ liters) can occur into the pelvis",
          "B. They cause immediate paralysis"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Pelvic fractures are life-threatening from massive blood loss. Based on this presentation, pelvic fractures are dangerous because?",
        "opts": [
          "A. They are immediately visible on exam",
          "B. They always cause bladder rupture",
          "C. Massive internal bleeding (2-3+ liters) can occur into the pelvis",
          "D. They cause immediate paralysis"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-35.q.05",
      "q": "Treatment for abdominal impaled object includes:",
      "opts": [
        "A. Remove and pack the wound",
        "B. Stabilize in place with bulky dressings",
        "C. Remove if less than 2 inches deep",
        "D. Apply ice and transport"
      ],
      "ans": 1,
      "exp": "Abdominal impaled objects are stabilized in place — removing them can cause uncontrolled hemorrhage. Do not remove in the field.",
      "easy": {
        "q": "What is Treatment for abdominal impaled object includes?",
        "opts": [
          "A. Stabilize in place with bulky dressings",
          "B. Apply ice and transport"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Evisceration: moist sterile cover, do not replace organs, knees up. Based on this presentation, treatment for abdominal impaled object includes?",
        "opts": [
          "A. Remove if less than 2 inches deep",
          "B. Remove and pack the wound",
          "C. Stabilize in place with bulky dressings",
          "D. Apply ice and transport"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-35.q.06",
      "q": "Cullen's sign (periumbilical bruising) indicates:",
      "opts": [
        "A. Superficial abdominal contusion",
        "B. Intra-abdominal bleeding (late sign)",
        "C. Appendicitis",
        "D. Kidney stones"
      ],
      "ans": 1,
      "exp": "Cullen's sign is periumbilical bruising — a late sign of significant intra-abdominal bleeding that appears hours after injury.",
      "easy": {
        "q": "What is Cullen's sign?",
        "opts": [
          "A. Intra-abdominal bleeding (late sign)",
          "B. Appendicitis"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Evisceration: moist sterile cover, do not replace organs, knees up. Based on this presentation, cullen's sign (periumbilical bruising) indicates?",
        "opts": [
          "A. Superficial abdominal contusion",
          "B. Kidney stones",
          "C. Intra-abdominal bleeding (late sign)",
          "D. Appendicitis"
        ],
        "ans": 2
      }
    }
  ]
};
