// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch38: Chapter = {
  "id": "ch-38",
  "number": 38,
  "partId": "part-11",
  "title": "Pediatrics",
  "cards": [
    {
      "id": "ch-38.fc.01",
      "q": "What is the Pediatric Assessment Triangle (PAT)?",
      "a": "Appearance, Work of Breathing, Circulation to skin — a rapid across-the-room assessment of pediatric stability requiring no equipment."
    },
    {
      "id": "ch-38.fc.02",
      "q": "Normal respiratory rate for an infant?",
      "a": "25-50 breaths per minute."
    },
    {
      "id": "ch-38.fc.03",
      "q": "How do you open an infant's airway?",
      "a": "Neutral position (or slight sniffing position) — do NOT hyperextend. The infant's proportionally large head causes tracheal kinking if over-extended."
    },
    {
      "id": "ch-38.fc.04",
      "q": "Two-rescuer infant CPR compression-to-ventilation ratio?",
      "a": "15:2 — two rescuers use 15 compressions followed by 2 ventilations."
    },
    {
      "id": "ch-38.fc.05",
      "q": "Correct chest compression technique for an infant?",
      "a": "Two-finger technique (one rescuer) or two thumb-encircling hands technique (two rescuers), lower half of sternum, 1.5 inches deep."
    },
    {
      "id": "ch-38.fc.06",
      "q": "Pediatric AED pads used for ages?",
      "a": "Ages 1-8 or under 55 lbs. Adult pads may be used if pediatric unavailable — place anterior/posterior to avoid pad overlap."
    },
    {
      "id": "ch-38.fc.07",
      "q": "Signs of respiratory distress in a child?",
      "a": "Nasal flaring, retractions (suprasternal, intercostal, subcostal), head bobbing, grunting, see-saw breathing, inability to complete sentences."
    },
    {
      "id": "ch-38.fc.08",
      "q": "Most common cause of cardiac arrest in children?",
      "a": "Respiratory failure — children arrest from hypoxia, not primary cardiac events as in adults."
    }
  ],
  "notes": [
    {
      "id": "ch-38.n.01",
      "title": "Pediatric Anatomy Differences",
      "body": "Children have proportionally larger tongues, heads, and softer airways than adults. Trachea is smaller and more flexible. Infants are obligate nose breathers. Fontanelles are open in infants — bulging may indicate increased ICP. Neutral airway position differs from adults — DO NOT hyperextend.",
      "terms": [
        "Obligate nose breather",
        "Fontanelle",
        "Sniffing position",
        "Neutral position",
        "Soft airway"
      ]
    },
    {
      "id": "ch-38.n.02",
      "title": "Pediatric Assessment Triangle",
      "body": "PAT assesses: Appearance (tone, interactivity, consolability, gaze, speech/cry), Work of Breathing (effort, sounds, positioning), Circulation to skin (color, mottling, pallor, cyanosis). Can be assessed in seconds from across the room without touching the child.",
      "terms": [
        "PAT",
        "Appearance",
        "Work of breathing",
        "Mottling",
        "Cyanosis"
      ]
    },
    {
      "id": "ch-38.n.03",
      "title": "Pediatric CPR & Common Emergencies",
      "body": "Infant compression depth: 1.5 inches. Child: 2 inches. Two-rescuer infant ratio: 15:2. Croup: barking cough, inspiratory stridor — keep calm, cool mist. Epiglottitis: life-threatening upper airway swelling — do NOT examine throat or agitate. Febrile seizure: generally benign.",
      "terms": [
        "Two-thumb technique",
        "15:2 ratio",
        "Croup",
        "Epiglottitis",
        "Febrile seizure"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-38.q.01",
      "q": "Most common cause of cardiac arrest in children is:",
      "opts": [
        "A. Ventricular fibrillation",
        "B. Respiratory failure and hypoxia",
        "C. AMI",
        "D. Trauma"
      ],
      "ans": 1,
      "exp": "Children arrest from respiratory failure and hypoxia unlike adults who commonly arrest from VF. High-quality ventilation is critical in pediatric CPR.",
      "easy": {
        "q": "Most common cause of cardiac arrest in children?",
        "opts": [
          "A. Respiratory failure and hypoxia",
          "B. AMI"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Most common cause of cardiac arrest in children is?",
        "opts": [
          "A. Ventricular fibrillation",
          "B. Trauma",
          "C. Respiratory failure and hypoxia",
          "D. AMI"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-38.q.02",
      "q": "Infant CPR compression depth:",
      "opts": [
        "A. 1 inch",
        "B. 1.5 inches",
        "C. 2 inches",
        "D. 2.5 inches"
      ],
      "ans": 1,
      "exp": "Infant compressions should be approximately 1.5 inches (4 cm) deep — about 1/3 the anterior-posterior chest diameter.",
      "easy": {
        "q": "Correct chest compression technique for an infant?",
        "opts": [
          "A. 1.5 inches",
          "B. 1 inch"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Infant CPR compression depth?",
        "opts": [
          "A. 2.5 inches",
          "B. 2 inches",
          "C. 1.5 inches",
          "D. 1 inch"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-38.q.03",
      "q": "Two-rescuer infant CPR ratio:",
      "opts": [
        "A. 30:2",
        "B. 15:1",
        "C. 15:2",
        "D. 10:2"
      ],
      "ans": 2,
      "exp": "Two-rescuer infant CPR uses 15 compressions to 2 ventilations. Single-rescuer uses 30:2 same as adults.",
      "easy": {
        "q": "Two-rescuer infant CPR compression-to-ventilation ratio?",
        "opts": [
          "A. 15:2",
          "B. 30:2"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Two-rescuer infant CPR ratio?",
        "opts": [
          "A. 30:2",
          "B. 15:1",
          "C. 15:2",
          "D. 10:2"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-38.q.04",
      "q": "Pediatric AED pads are used for:",
      "opts": [
        "A. Under 1 year",
        "B. Ages 1-8 or under 55 lbs",
        "C. Ages 1-12",
        "D. All children under 18"
      ],
      "ans": 1,
      "exp": "Pediatric pads (attenuated dose) for ages 1-8 or under 55 lbs. Infants under 1: manual defibrillator preferred.",
      "easy": {
        "q": "Pediatric AED pads used for ages?",
        "opts": [
          "A. Ages 1-8 or under 55 lbs",
          "B. Ages 1-12"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. Pediatric AED pads are used for?",
        "opts": [
          "A. All children under 18",
          "B. Under 1 year",
          "C. Ages 1-8 or under 55 lbs",
          "D. Ages 1-12"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-38.q.05",
      "q": "A barking cough with inspiratory stridor likely indicates:",
      "opts": [
        "A. Epiglottitis",
        "B. Asthma",
        "C. Croup",
        "D. Bronchiolitis"
      ],
      "ans": 2,
      "exp": "Croup causes a classic barking/seal-like cough with inspiratory stridor due to subglottic edema — keep calm, avoid agitation.",
      "easy": {
        "q": "What is barking cough with inspiratory stridor likely indicates?",
        "opts": [
          "A. Croup",
          "B. Asthma"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. A barking cough with inspiratory stridor likely indicates?",
        "opts": [
          "A. Bronchiolitis",
          "B. Epiglottitis",
          "C. Croup",
          "D. Asthma"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-38.q.06",
      "q": "When opening an infant's airway, avoid:",
      "opts": [
        "A. Neutral positioning",
        "B. Sniffing position",
        "C. Hyperextension of the neck",
        "D. Jaw thrust"
      ],
      "ans": 2,
      "exp": "Infant's proportionally large head causes the neck to over-flex the trachea if hyperextended. Use neutral or slight sniffing position.",
      "easy": {
        "q": "What is When opening an infant's airway, avoid?",
        "opts": [
          "A. Hyperextension of the neck",
          "B. Jaw thrust"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. When opening an infant's airway, avoid?",
        "opts": [
          "A. Neutral positioning",
          "B. Sniffing position",
          "C. Hyperextension of the neck",
          "D. Jaw thrust"
        ],
        "ans": 2
      }
    }
  ]
};
