// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch36: Chapter = {
  "id": "ch-36",
  "number": 36,
  "partId": "part-10",
  "title": "Multisystem Trauma & Special Populations",
  "cards": [
    {
      "id": "ch-36.fc.01",
      "q": "What is multisystem trauma?",
      "a": "Injury to two or more body systems — significantly increases mortality and requires rapid transport to a trauma center."
    },
    {
      "id": "ch-36.fc.02",
      "q": "What is the Golden Period in trauma?",
      "a": "The concept that critically injured trauma patients have the best survival if they receive definitive surgical care rapidly — traditionally called 'Golden Hour.'"
    },
    {
      "id": "ch-36.fc.03",
      "q": "What are special considerations for pregnant trauma patients?",
      "a": "Two patients (mother and fetus). Position left lateral to relieve IUA pressure on vena cava. Fetal heart rate may drop before maternal vital signs change."
    },
    {
      "id": "ch-36.fc.04",
      "q": "What are signs of traumatic aortic rupture?",
      "a": "Tearing/ripping pain radiating to back, unequal blood pressures in arms, pulse deficits, widened mediastinum on X-ray — from high-speed deceleration."
    },
    {
      "id": "ch-36.fc.05",
      "q": "How does trauma presentation differ in geriatric patients?",
      "a": "Blunted physiologic response (beta-blockers mask tachycardia), osteoporosis increases fracture risk, anticoagulants increase bleeding, decreased physiologic reserve."
    },
    {
      "id": "ch-36.fc.06",
      "q": "What is commotio cordis?",
      "a": "Sudden cardiac arrest from blunt chest impact during a vulnerable phase of the cardiac cycle — classically from a baseball or hockey puck impact."
    },
    {
      "id": "ch-36.fc.07",
      "q": "How does obesity affect trauma assessment?",
      "a": "Increased difficulty examining, assessing vitals, airway management, and IV access. Underlying conditions increase risk. More force needed to cause injury — but also more force absorbed."
    },
    {
      "id": "ch-36.fc.08",
      "q": "What MOI produces traumatic aortic injury?",
      "a": "High-speed deceleration (high-speed MVC, fall from height) — the aorta tears at the ligamentum arteriosum where it is tethered."
    }
  ],
  "notes": [
    {
      "id": "ch-36.n.01",
      "title": "Multisystem Trauma Management",
      "body": "Multisystem trauma patients are load-and-go. Limit on-scene time to <10 minutes. Control life-threatening hemorrhage, maintain airway, provide spinal motion restriction. Ongoing assessment during transport. High index of suspicion based on MOI. Rapid transport to trauma center is the definitive treatment.",
      "terms": [
        "Load and go",
        "On-scene time",
        "Hemorrhage control",
        "Trauma center",
        "High index of suspicion"
      ]
    },
    {
      "id": "ch-36.n.02",
      "title": "Special Trauma Populations",
      "body": "Pregnant: two patients, left lateral tilt, fetal monitoring limited in field. Pediatric: different anatomy, different vital sign norms, non-verbal. Geriatric: blunted response, anticoagulants, osteoporosis, polypharmacy. Bariatric: assessment and access challenges.",
      "terms": [
        "Pregnant trauma",
        "Left lateral tilt",
        "Pediatric trauma",
        "Geriatric trauma",
        "Bariatric"
      ]
    },
    {
      "id": "ch-36.n.03",
      "title": "Traumatic Aortic Injury",
      "body": "Traumatic aortic rupture occurs at the ligamentum arteriosum from severe deceleration. Classic presentation: tearing chest/back pain, unequal arm BPs, BP differential between arms. Immediately life-threatening. Most patients die at the scene — survivors have partial tears (aortic dissection). Rapid transport only.",
      "terms": [
        "Aortic rupture",
        "Deceleration",
        "Ligamentum arteriosum",
        "Tearing pain",
        "Unequal BP"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-36.q.01",
      "q": "Multisystem trauma patients require:",
      "opts": [
        "A. Extended on-scene assessment",
        "B. Rapid transport to trauma center with minimal on-scene time",
        "C. Stabilization before transport",
        "D. Field surgery"
      ],
      "ans": 1,
      "exp": "Multisystem trauma patients are load-and-go — limit on-scene time, control hemorrhage, maintain airway, and transport to definitive surgical care."
    },
    {
      "id": "ch-36.q.02",
      "q": "A pregnant trauma patient should be positioned:",
      "opts": [
        "A. Supine flat",
        "B. Left lateral or left tilt to relieve vena cava compression",
        "C. Right lateral",
        "D. Prone"
      ],
      "ans": 1,
      "exp": "Supine positioning in pregnancy causes the uterus to compress the inferior vena cava — left lateral tilt relieves this and improves cardiac output."
    },
    {
      "id": "ch-36.q.03",
      "q": "Commotio cordis is caused by:",
      "opts": [
        "A. High-speed MVC",
        "B. Blunt chest impact during a vulnerable cardiac phase causing cardiac arrest",
        "C. Penetrating chest trauma",
        "D. Rib fractures"
      ],
      "ans": 1,
      "exp": "Commotio cordis is sudden cardiac arrest from blunt chest impact (baseball, hockey puck) during the T-wave of the cardiac cycle."
    },
    {
      "id": "ch-36.q.04",
      "q": "Traumatic aortic rupture classically results from:",
      "opts": [
        "A. Penetrating trauma",
        "B. High-speed deceleration injury",
        "C. Fall from standing",
        "D. Crush injury"
      ],
      "ans": 1,
      "exp": "High-speed deceleration (MVC, fall from height) causes the aorta to tear at the ligamentum arteriosum where it is tethered."
    },
    {
      "id": "ch-36.q.05",
      "q": "Geriatric trauma patients may not show tachycardia in shock because:",
      "opts": [
        "A. They have higher resting heart rates",
        "B. Beta-blockers blunt the compensatory tachycardia response",
        "C. Their hearts are more efficient",
        "D. They always present atypically"
      ],
      "ans": 1,
      "exp": "Many elderly patients take beta-blockers, which blunt the compensatory tachycardia that normally indicates developing shock."
    },
    {
      "id": "ch-36.q.06",
      "q": "On-scene time for multisystem trauma should be:",
      "opts": [
        "A. 30 minutes for thorough assessment",
        "B. Less than 10 minutes",
        "C. As long as needed for assessment",
        "D. Only limited if ALS is unavailable"
      ],
      "ans": 1,
      "exp": "Limit on-scene time to <10 minutes for multisystem trauma — the trauma center is the only place that can provide definitive surgical care."
    }
  ]
};
