// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch33: Chapter = {
  "id": "ch-33",
  "number": 33,
  "partId": "part-10",
  "title": "Eye, Face & Neck Trauma",
  "cards": [
    {
      "id": "ch-33.fc.01",
      "q": "What are the key structures of the eye?",
      "a": "Cornea (clear front), iris, pupil, lens, retina (back), and vitreous humor. The orbit is the bony socket protecting the eye."
    },
    {
      "id": "ch-33.fc.02",
      "q": "What mechanisms injure the eye, face, and neck?",
      "a": "Blunt force (fists, MVC), penetrating trauma, chemical splash, foreign bodies, burns, and assault. Neck: blunt or penetrating trauma to vessels, airway, and spine."
    },
    {
      "id": "ch-33.fc.03",
      "q": "How do you manage a foreign object on the surface of the eye?",
      "a": "Do not rub. Irrigate gently with saline or water. If embedded in the cornea, cover both eyes and transport — do not attempt removal."
    },
    {
      "id": "ch-33.fc.04",
      "q": "How do you treat a chemical burn to the eye?",
      "a": "Immediate copious irrigation with water or saline for at least 20 minutes — alkaline burns penetrate deeper. Irrigate en route if needed."
    },
    {
      "id": "ch-33.fc.05",
      "q": "How do you manage an extruded (protruding) eyeball?",
      "a": "Do not push back in. Cover with a moist sterile dressing and a cup/cone — cover both eyes to reduce movement. Transport immediately."
    },
    {
      "id": "ch-33.fc.06",
      "q": "How do you treat a globe (open eyeball) injury?",
      "a": "Do not apply pressure. Stabilize with a rigid shield/cup over the eye, cover both eyes, keep patient supine if possible, rapid transport."
    },
    {
      "id": "ch-33.fc.07",
      "q": "What is the primary concern with facial trauma?",
      "a": "Airway compromise — bleeding, swelling, fractures, and avulsed teeth can rapidly obstruct the airway."
    },
    {
      "id": "ch-33.fc.08",
      "q": "How do you treat an open neck wound?",
      "a": "Apply an occlusive dressing immediately — risk of air embolism from jugular vein injury and airway obstruction from expanding hematoma."
    }
  ],
  "notes": [
    {
      "id": "ch-33.n.01",
      "title": "Anatomy & Mechanisms (Obj 33-1, 33-2)",
      "body": "Eye structures: cornea, iris/pupil, lens, retina, optic nerve, orbit (bony socket). Face: mandible, maxilla, zygomatic arches, nasal bones, soft tissue — airway runs through. Neck: carotid arteries, jugular veins, trachea/larynx, cervical spine, esophagus. MOI includes blunt assault, MVC, falls, penetrating trauma, chemical exposure, and thermal burns. High-energy mechanisms to the face and neck carry risk to airway, vessels, and spine simultaneously.",
      "terms": [
        "Cornea",
        "Orbit",
        "Retina",
        "Trachea",
        "Jugular vein",
        "Mechanism of injury"
      ]
    },
    {
      "id": "ch-33.n.02",
      "title": "Eye Injury Assessment & Treatment (Obj 33-4)",
      "body": "Foreign body on surface: irrigate, do not rub. Corneal abrasion: painful, photophobic — cover and transport. Chemical burn: immediate irrigation 20+ min (alkali worse than acid). Globe injury (ruptured eye): rigid shield, no pressure, cover both eyes. Extruded eyeball: moist dressing and cup, never reinsert. Orbit fracture: raccoon eyes, diplopia — protect eye, transport. Hyphema (blood in anterior chamber): keep head elevated, no aspirin.",
      "terms": [
        "Foreign body",
        "Chemical burn",
        "Globe injury",
        "Extruded eyeball",
        "Hyphema",
        "Corneal abrasion"
      ]
    },
    {
      "id": "ch-33.n.03",
      "title": "Face & Neck Trauma Priorities",
      "body": "Facial trauma: assess airway first — suction blood, position, prepare for intubation. Control bleeding without compromising airway. Le Fort fractures cause midface instability. Neck trauma: occlusive dressing for open wounds (air embolism), monitor airway for laryngeal fracture or expanding hematoma, maintain SMR for blunt neck trauma. Cover both eyes for any unilateral eye injury to reduce movement.",
      "terms": [
        "Airway compromise",
        "Le Fort fracture",
        "Occlusive dressing",
        "Air embolism",
        "Cover both eyes",
        "Laryngeal fracture"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-33.q.01",
      "q": "The cornea is:",
      "opts": [
        "A. The colored part of the eye",
        "B. The clear front surface of the eye",
        "C. The back of the eye where images form",
        "D. The bony socket surrounding the eye"
      ],
      "ans": 1,
      "exp": "The cornea is the transparent front surface of the eye — injuries here cause significant pain and vision impairment.",
      "easy": {
        "q": "What are the key structures of the eye?",
        "opts": [
          "A. The clear front surface of the eye",
          "B. The colored part of the eye"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. The cornea is?",
        "opts": [
          "A. The back of the eye where images form",
          "B. The bony socket surrounding the eye",
          "C. The clear front surface of the eye",
          "D. The colored part of the eye"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.02",
      "q": "A chemical splash to the eye should be treated with:",
      "opts": [
        "A. Neutralizing solution before irrigation",
        "B. Immediate copious irrigation for at least 20 minutes",
        "C. Patching the eye and rapid transport without irrigation",
        "D. Topical anesthetic only"
      ],
      "ans": 1,
      "exp": "Immediate, copious irrigation is critical — alkaline chemicals penetrate deeper and longer than acids.",
      "easy": {
        "q": "How do you treat a chemical burn to the eye?",
        "opts": [
          "A. Immediate copious irrigation for at least 20 minutes",
          "B. Topical anesthetic only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "You arrive on scene and complete your primary assessment. A chemical splash to the eye should be treated with?",
        "opts": [
          "A. Patching the eye and rapid transport without irrigation",
          "B. Neutralizing solution before irrigation",
          "C. Immediate copious irrigation for at least 20 minutes",
          "D. Topical anesthetic only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.03",
      "q": "An extruded eyeball should be:",
      "opts": [
        "A. Pushed back into the socket",
        "B. Covered with moist dressing and a rigid cup — do not reinsert",
        "C. Irrigated vigorously",
        "D. Left uncovered for assessment"
      ],
      "ans": 1,
      "exp": "Never attempt to reinsert an extruded eyeball — cover with moist dressing and a cup/cone, cover both eyes, transport immediately.",
      "easy": {
        "q": "How do you manage an extruded (protruding) eyeball?",
        "opts": [
          "A. Covered with moist dressing and a rigid cup — do not reinsert",
          "B. Irrigated vigorously"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Foreign body on surface: irrigate, do not rub. Based on this presentation, an extruded eyeball should be?",
        "opts": [
          "A. Left uncovered for assessment",
          "B. Pushed back into the socket",
          "C. Covered with moist dressing and a rigid cup — do not reinsert",
          "D. Irrigated vigorously"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.04",
      "q": "For any serious unilateral eye injury, you should:",
      "opts": [
        "A. Cover only the injured eye",
        "B. Cover both eyes to reduce movement of the injured eye",
        "C. Patch both eyes permanently on scene",
        "D. Have the patient keep both eyes open"
      ],
      "ans": 1,
      "exp": "Covering both eyes reduces consensual movement of the injured eye — always explain this to the patient first.",
      "easy": {
        "q": "How do you manage an extruded (protruding) eyeball?",
        "opts": [
          "A. Cover both eyes to reduce movement of the injured eye",
          "B. Cover only the injured eye"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Facial trauma: assess airway first. Based on this presentation, for any serious unilateral eye injury, you should?",
        "opts": [
          "A. Patch both eyes permanently on scene",
          "B. Have the patient keep both eyes open",
          "C. Cover both eyes to reduce movement of the injured eye",
          "D. Cover only the injured eye"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.05",
      "q": "Primary concern with significant facial trauma is:",
      "opts": [
        "A. Cosmetic appearance",
        "B. Airway compromise from bleeding and swelling",
        "C. Spinal injury only",
        "D. Pain management as the only priority"
      ],
      "ans": 1,
      "exp": "Facial injuries can rapidly obstruct the airway — assess and manage airway before other interventions.",
      "easy": {
        "q": "What is the primary concern with facial trauma?",
        "opts": [
          "A. Airway compromise from bleeding and swelling",
          "B. Spinal injury only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Facial trauma: assess airway first. Based on this presentation, primary concern with significant facial trauma is?",
        "opts": [
          "A. Pain management as the only priority",
          "B. Cosmetic appearance",
          "C. Airway compromise from bleeding and swelling",
          "D. Spinal injury only"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.06",
      "q": "An open wound to the neck requires:",
      "opts": [
        "A. Standard gauze dressing",
        "B. Immediate occlusive dressing to prevent air embolism",
        "C. Direct pressure with a tourniquet",
        "D. Irrigation with saline"
      ],
      "ans": 1,
      "exp": "Open neck wounds risk fatal air embolism through jugular vein injury — occlusive dressing is mandatory.",
      "easy": {
        "q": "How do you treat an open neck wound?",
        "opts": [
          "A. Immediate occlusive dressing to prevent air embolism",
          "B. Irrigation with saline"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Facial trauma: assess airway first. Based on this presentation, an open wound to the neck requires?",
        "opts": [
          "A. Direct pressure with a tourniquet",
          "B. Standard gauze dressing",
          "C. Immediate occlusive dressing to prevent air embolism",
          "D. Irrigation with saline"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.07",
      "q": "A globe (ruptured eyeball) injury should be managed by:",
      "opts": [
        "A. Applying direct pressure to stop bleeding",
        "B. Placing a rigid shield over the eye without applying pressure",
        "C. Irrigating the eye thoroughly",
        "D. Removing visible foreign material from the eye interior"
      ],
      "ans": 1,
      "exp": "Never apply pressure to a ruptured globe — use a rigid shield/cup, cover both eyes, and transport for surgical repair.",
      "easy": {
        "q": "How do you treat a globe (open eyeball) injury?",
        "opts": [
          "A. Placing a rigid shield over the eye without applying pressure",
          "B. Irrigating the eye thoroughly"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Foreign body on surface: irrigate, do not rub. Based on this presentation, a globe (ruptured eyeball) injury should be managed by?",
        "opts": [
          "A. Removing visible foreign material from the eye interior",
          "B. Applying direct pressure to stop bleeding",
          "C. Placing a rigid shield over the eye without applying pressure",
          "D. Irrigating the eye thoroughly"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-33.q.08",
      "q": "Blunt trauma to the orbit may cause:",
      "opts": [
        "A. Only external bruising with no deeper injury",
        "B. Orbital fracture, globe injury, and potential intracranial injury",
        "C. Injury to the ear only",
        "D. Cervical spine injury only"
      ],
      "ans": 1,
      "exp": "Orbital blows can fracture the orbit, injure the globe, and transmit force to the brain — assess fully.",
      "easy": {
        "q": "How do you treat an open neck wound?",
        "opts": [
          "A. Orbital fracture, globe injury, and potential intracranial injury",
          "B. Injury to the ear only"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Eye structures: cornea, iris/pupil, lens, retina, optic nerve, orbit (bony socket). Based on this presentation, blunt trauma to the orbit may cause?",
        "opts": [
          "A. Only external bruising with no deeper injury",
          "B. Cervical spine injury only",
          "C. Orbital fracture, globe injury, and potential intracranial injury",
          "D. Injury to the ear only"
        ],
        "ans": 2
      }
    }
  ]
};
