// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch43: Chapter = {
  "id": "ch-43",
  "number": 43,
  "partId": "part-12",
  "title": "Gaining Access & Patient Extrication",
  "cards": [
    {
      "id": "ch-43.fc.01",
      "q": "What is vehicle extrication?",
      "a": "The process of safely removing a trapped patient from a vehicle while protecting the patient from further injury."
    },
    {
      "id": "ch-43.fc.02",
      "q": "What is the priority sequence in vehicle extrication?",
      "a": "Scene safety → Stabilize vehicle → Gain access → Patient assessment/care → Disentangle → Remove patient."
    },
    {
      "id": "ch-43.fc.03",
      "q": "Why must a vehicle be stabilized before extrication?",
      "a": "An unstable vehicle can shift during extrication, causing additional injury to the patient and rescuers."
    },
    {
      "id": "ch-43.fc.04",
      "q": "What is the difference between simple and complex access?",
      "a": "Simple access: opening doors, windows without tools. Complex access: requires tools and specialized techniques — call rescue/fire."
    },
    {
      "id": "ch-43.fc.05",
      "q": "What PPE is required for vehicle extrication?",
      "a": "Turnout gear (helmet, gloves, eye protection, structural firefighting coat), and respiratory protection if hazmat present."
    },
    {
      "id": "ch-43.fc.06",
      "q": "What is 'disentanglement'?",
      "a": "Removing the vehicle from around the patient after gaining access — cutting posts, folding the dash, removing the roof."
    },
    {
      "id": "ch-43.fc.07",
      "q": "When is rapid extrication used?",
      "a": "When the patient requires immediate care that cannot be provided in the vehicle — compromised airway, immediate life threat, need for CPR."
    },
    {
      "id": "ch-43.fc.08",
      "q": "What is the purpose of cribbing in extrication?",
      "a": "Cribbing uses wood or plastic blocks to stabilize a vehicle and prevent movement during patient extrication."
    }
  ],
  "notes": [
    {
      "id": "ch-43.n.01",
      "title": "Vehicle Stabilization",
      "body": "Never enter an unstable vehicle — it can roll or shift causing further injury. Stabilize with cribbing, straps, or chocks before entry. Disconnect battery if possible to prevent airbag deployment during extrication. Hybrid/electric vehicles have high-voltage systems requiring special precautions.",
      "terms": [
        "Cribbing",
        "Vehicle stabilization",
        "Battery disconnect",
        "Airbag",
        "Hybrid vehicle"
      ]
    },
    {
      "id": "ch-43.n.02",
      "title": "Gaining Access",
      "body": "Simple access: try all doors first (car doors often open after impact). Complex access: requires tools (Hurst tools, glass punches, saws) and trained rescue personnel. EMT role: patient assessment and care once access is gained — not tool operation unless trained.",
      "terms": [
        "Simple access",
        "Complex access",
        "Hurst tool",
        "Glass punch",
        "EMT role"
      ]
    },
    {
      "id": "ch-43.n.03",
      "title": "Patient Care During Extrication",
      "body": "Maintain MILS during entire extrication. Assess and treat immediately accessible life threats. Monitor patient condition continuously. EMT inside with patient if possible. Communicate changes to extrication team. Rapid extrication if condition deteriorates.",
      "terms": [
        "MILS",
        "Spinal precautions",
        "Continuous monitoring",
        "Rapid extrication",
        "Communication"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-43.q.01",
      "q": "First priority in vehicle extrication is:",
      "opts": [
        "A. Gaining access to patient",
        "B. Scene safety and vehicle stabilization",
        "C. Patient assessment",
        "D. Calling for additional resources"
      ],
      "ans": 1,
      "exp": "Scene safety first, then vehicle stabilization — an unstable vehicle can shift and injure both patient and rescuers during extrication.",
      "easy": {
        "q": "What is the priority sequence in vehicle extrication?",
        "opts": [
          "A. Scene safety and vehicle stabilization",
          "B. Patient assessment"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Never enter an unstable vehicle. Based on this presentation, first priority in vehicle extrication is?",
        "opts": [
          "A. Calling for additional resources",
          "B. Gaining access to patient",
          "C. Scene safety and vehicle stabilization",
          "D. Patient assessment"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-43.q.02",
      "q": "An unstable vehicle is stabilized using:",
      "opts": [
        "A. Airbags",
        "B. Cribbing — wood or plastic blocks to prevent movement",
        "C. Ropes only",
        "D. Parking brakes only"
      ],
      "ans": 1,
      "exp": "Cribbing uses wood or plastic blocks placed strategically to prevent vehicle movement and create a stable working platform during extrication.",
      "easy": {
        "q": "What is the purpose of cribbing in extrication?",
        "opts": [
          "A. Cribbing — wood or plastic blocks to prevent movement",
          "B. Airbags"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Never enter an unstable vehicle. Based on this presentation, an unstable vehicle is stabilized using?",
        "opts": [
          "A. Parking brakes only",
          "B. Ropes only",
          "C. Cribbing — wood or plastic blocks to prevent movement",
          "D. Airbags"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-43.q.03",
      "q": "Simple access in vehicle extrication means:",
      "opts": [
        "A. Only fire department can perform it",
        "B. Opening doors or windows without specialized tools",
        "C. Always requires hydraulic tools",
        "D. Can only be done after patient assessment"
      ],
      "ans": 1,
      "exp": "Simple access uses no specialized tools — trying door handles, breaking windows. Always attempt simple access before complex access.",
      "easy": {
        "q": "What is the difference between simple and complex access?",
        "opts": [
          "A. Opening doors or windows without specialized tools",
          "B. Always requires hydraulic tools"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Never enter an unstable vehicle. Based on this presentation, simple access in vehicle extrication means?",
        "opts": [
          "A. Can only be done after patient assessment",
          "B. Only fire department can perform it",
          "C. Opening doors or windows without specialized tools",
          "D. Always requires hydraulic tools"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-43.q.04",
      "q": "MILS during extrication should be maintained:",
      "opts": [
        "A. Only until C-collar is applied",
        "B. Throughout the entire extrication process",
        "C. Only after vehicle is stabilized",
        "D. Only if patient is unconscious"
      ],
      "ans": 1,
      "exp": "MILS must be maintained from first patient contact throughout the entire extrication until the patient is fully secured on a backboard.",
      "easy": {
        "q": "What is vehicle extrication?",
        "opts": [
          "A. Throughout the entire extrication process",
          "B. Only until C-collar is applied"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Maintain MILS during entire extrication. Based on this presentation, MILS during extrication should be maintained?",
        "opts": [
          "A. Only after vehicle is stabilized",
          "B. Only until C-collar is applied",
          "C. Throughout the entire extrication process",
          "D. Only if patient is unconscious"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-43.q.05",
      "q": "Rapid extrication from a vehicle is indicated when:",
      "opts": [
        "A. The patient is calm",
        "B. The patient has an immediate life threat requiring care that cannot be provided in vehicle",
        "C. Standard extrication takes over 10 minutes",
        "D. Family requests speed"
      ],
      "ans": 1,
      "exp": "Rapid extrication is used for immediate life threats (cardiac arrest, airway compromise) that cannot be managed inside the vehicle.",
      "easy": {
        "q": "When is rapid extrication used?",
        "opts": [
          "A. The patient has an immediate life threat requiring care that cannot be provided in vehicle",
          "B. The patient is calm"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Never enter an unstable vehicle. Based on this presentation, rapid extrication from a vehicle is indicated when?",
        "opts": [
          "A. Standard extrication takes over 10 minutes",
          "B. Family requests speed",
          "C. The patient has an immediate life threat requiring care that cannot be provided in vehicle",
          "D. The patient is calm"
        ],
        "ans": 2
      }
    },
    {
      "id": "ch-43.q.06",
      "q": "Hybrid and electric vehicles require special precautions because:",
      "opts": [
        "A. They are heavier",
        "B. They have high-voltage electrical systems that pose electrocution risk",
        "C. They cannot be stabilized",
        "D. Their airbags are larger"
      ],
      "ans": 1,
      "exp": "Hybrid and electric vehicles contain high-voltage battery systems (300-400+ volts) — cutting certain cables or areas can cause electrocution. Follow specific protocols.",
      "easy": {
        "q": "What is Hybrid and electric vehicles require special precautions because?",
        "opts": [
          "A. They have high-voltage electrical systems that pose electrocution risk",
          "B. They are heavier"
        ],
        "ans": 0
      },
      "hard": {
        "q": "Clinical context: Never enter an unstable vehicle. Based on this presentation, hybrid and electric vehicles require special precautions because?",
        "opts": [
          "A. They cannot be stabilized",
          "B. Their airbags are larger",
          "C. They have high-voltage electrical systems that pose electrocution risk",
          "D. They are heavier"
        ],
        "ans": 2
      }
    }
  ]
};
