// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch44: Chapter = {
  "id": "ch-44",
  "number": 44,
  "partId": "part-12",
  "title": "Hazardous Materials",
  "cards": [
    {
      "id": "ch-44.fc.01",
      "q": "What is the EMT's role at a hazmat incident?",
      "a": "Identify hazmat presence from a safe distance, isolate and deny entry, call for hazmat team — do NOT enter the hot zone without proper training and PPE."
    },
    {
      "id": "ch-44.fc.02",
      "q": "What are the three hazmat zones?",
      "a": "Hot zone (contaminated area), Warm zone (decontamination corridor), Cold zone (command/staging/EMS treatment area)."
    },
    {
      "id": "ch-44.fc.03",
      "q": "What is the Emergency Response Guidebook (ERG)?",
      "a": "A reference guide to identify hazardous materials and initial emergency response actions based on placard/UN ID number."
    },
    {
      "id": "ch-44.fc.04",
      "q": "What are placards and where are they found?",
      "a": "Diamond-shaped warning signs on vehicles/containers indicating the type of hazardous material — color-coded by hazard class."
    },
    {
      "id": "ch-44.fc.05",
      "q": "What is decontamination?",
      "a": "The process of removing or neutralizing hazardous substances from patients, personnel, and equipment before entering the cold zone."
    },
    {
      "id": "ch-44.fc.06",
      "q": "What is the primary decontamination method for most chemical exposures?",
      "a": "Remove contaminated clothing (eliminates ~80% of contamination) and flush with copious water (dilution)."
    },
    {
      "id": "ch-44.fc.07",
      "q": "What is the NFPA 704 diamond?",
      "a": "A four-quadrant diamond: red (fire hazard), blue (health hazard), yellow (reactivity), white (special hazards) — rated 0-4."
    },
    {
      "id": "ch-44.fc.08",
      "q": "When can EMS treat patients at a hazmat scene?",
      "a": "Only in the cold zone, after patients have been properly decontaminated by hazmat personnel."
    }
  ],
  "notes": [
    {
      "id": "ch-44.n.01",
      "title": "Hazmat Identification",
      "body": "Identify hazmat presence from a distance — binoculars, placards, ERG. UN/NA numbers identify specific chemicals. Placards on transport vehicles are required by DOT for hazardous quantities. NFPA 704 diamonds on fixed facilities. Never approach until hazmat team confirms safety.",
      "terms": [
        "Placard",
        "ERG",
        "UN/NA number",
        "NFPA 704",
        "Binoculars"
      ]
    },
    {
      "id": "ch-44.n.02",
      "title": "Hazmat Zones & Decontamination",
      "body": "Hot zone: immediately dangerous, only hazmat-trained personnel in appropriate PPE. Warm zone: decon occurs here. Cold zone: EMS treats and transports decontaminated patients. Patient decon: remove clothing (80% of contamination), flush with water. Never treat before decon.",
      "terms": [
        "Hot zone",
        "Warm zone",
        "Cold zone",
        "Decontamination",
        "Gross decon"
      ]
    },
    {
      "id": "ch-44.n.03",
      "title": "EMT Scope at Hazmat Incidents",
      "body": "EMT role: recognition, notification, isolation, denial of entry, scene support in cold zone only. Do NOT enter hot or warm zones without full hazmat training and appropriate PPE. Support hazmat team. Prepare for mass casualties. Document all contaminated patients.",
      "terms": [
        "Scene support",
        "Cold zone treatment",
        "SCBA",
        "Mass casualty",
        "Incident command"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-44.q.01",
      "q": "At a hazmat scene, EMTs should:",
      "opts": [
        "A. Enter the hot zone with standard gloves",
        "B. Stay in the cold zone and support hazmat team",
        "C. Immediately treat victims in the hot zone",
        "D. Remove all patients without decontamination"
      ],
      "ans": 1,
      "exp": "EMTs without hazmat training must remain in the cold zone. Entering contaminated areas without proper PPE puts the EMT at serious risk."
    },
    {
      "id": "ch-44.q.02",
      "q": "The three hazmat zones in order from most to least dangerous:",
      "opts": [
        "A. Warm, hot, cold",
        "B. Hot, warm, cold",
        "C. Cold, warm, hot",
        "D. Decon, staging, treatment"
      ],
      "ans": 1,
      "exp": "Hot (contaminated/dangerous) → Warm (decon corridor) → Cold (safe staging/treatment area)."
    },
    {
      "id": "ch-44.q.03",
      "q": "The Emergency Response Guidebook (ERG) is used to:",
      "opts": [
        "A. Direct all patient care",
        "B. Identify hazardous materials and initial response actions",
        "C. Dispatch EMS units",
        "D. Train hazmat technicians"
      ],
      "ans": 1,
      "exp": "The ERG uses placard numbers or chemical names to provide initial isolation distances and protective actions for first responders."
    },
    {
      "id": "ch-44.q.04",
      "q": "Primary decontamination of chemical exposure patients involves:",
      "opts": [
        "A. Applying neutralizing agents",
        "B. Removing clothing and flushing with copious water",
        "C. Wrapping in protective blankets",
        "D. Administering activated charcoal"
      ],
      "ans": 1,
      "exp": "Remove all clothing (eliminates ~80% of contamination) then flush with large amounts of water — dilution is the solution to pollution."
    },
    {
      "id": "ch-44.q.05",
      "q": "EMS may treat hazmat patients only:",
      "opts": [
        "A. In the warm zone during decon",
        "B. In the hot zone with proper PPE",
        "C. In the cold zone after decontamination is complete",
        "D. Immediately on arrival regardless of zone"
      ],
      "ans": 2,
      "exp": "Patients must be fully decontaminated before EMS treats them in the cold zone — treating before decon exposes the EMT and ambulance to contamination."
    },
    {
      "id": "ch-44.q.06",
      "q": "The NFPA 704 diamond provides information about:",
      "opts": [
        "A. Traffic routing for emergency vehicles",
        "B. Fire, health, reactivity hazards, and special information on a 0-4 scale",
        "C. Required PPE levels only",
        "D. Chemical antidotes"
      ],
      "ans": 1,
      "exp": "NFPA 704: Red (fire hazard), Blue (health hazard), Yellow (reactivity), White (special hazards) — rated 0 (none) to 4 (extreme)."
    }
  ]
};
