// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch46: Chapter = {
  "id": "ch-46",
  "number": 46,
  "partId": "part-12",
  "title": "EMS Response to Terrorist Incidents",
  "cards": [
    {
      "id": "ch-46.fc.01",
      "q": "What is the primary concern at a terrorism scene?",
      "a": "Scene safety — secondary devices, structural collapse, ongoing threats. EMT safety is always the first priority."
    },
    {
      "id": "ch-46.fc.02",
      "q": "What are the categories of CBRNE agents?",
      "a": "Chemical, Biological, Radiological, Nuclear, Explosive — categories of weapons of mass destruction."
    },
    {
      "id": "ch-46.fc.03",
      "q": "What are signs of a nerve agent exposure?",
      "a": "SLUDGEM: Salivation, Lacrimation, Urination, Defecation, GI distress, Emesis, Miosis — plus bradycardia and bronchospasm."
    },
    {
      "id": "ch-46.fc.04",
      "q": "What is a secondary device?",
      "a": "A bomb or weapon placed to injure first responders after the initial attack — always assume risk until EOD clears the scene."
    },
    {
      "id": "ch-46.fc.05",
      "q": "What are signs suggesting a biological agent attack?",
      "a": "Unusual disease patterns, multiple patients with similar atypical illness, unusual time of year, disease not endemic to area — delayed onset (hours to days)."
    },
    {
      "id": "ch-46.fc.06",
      "q": "What is shelter-in-place?",
      "a": "Directing people to remain inside sealed buildings — used for airborne chemical or biological threats to prevent exposure."
    },
    {
      "id": "ch-46.fc.07",
      "q": "What is the EMT's role in a terrorism response?",
      "a": "Recognize unusual patterns, notify authorities immediately, ensure scene safety, work within ICS, support hazmat, operate in cold zone only."
    },
    {
      "id": "ch-46.fc.08",
      "q": "What are signs of a radiological exposure?",
      "a": "No immediate specific symptoms — nausea/vomiting may occur with large dose. Long-term cancer risk. Detected by dosimeter. Do NOT enter without proper PPE."
    }
  ],
  "notes": [
    {
      "id": "ch-46.n.01",
      "title": "CBRNE Agent Recognition",
      "body": "Chemical: rapid onset, SLUDGEM or anticholinergic signs. Biological: delayed onset (hours to days), unusual disease clusters. Radiological/Nuclear: no immediate symptoms, detected by dosimeter. Explosive: blast injuries, burns, penetrating trauma. Always consider secondary devices.",
      "terms": [
        "CBRNE",
        "SLUDGEM",
        "Secondary device",
        "Dosimeter",
        "Decontamination"
      ]
    },
    {
      "id": "ch-46.n.02",
      "title": "Scene Safety at Terrorism Incidents",
      "body": "Terrorism scenes are crime scenes and active threat areas. Approach with extreme caution — secondary devices are common. Use ICS from the start. Follow law enforcement guidance. Do not enter hot zones. Decontaminate all patients before treatment. Document and preserve evidence.",
      "terms": [
        "Secondary device",
        "Crime scene",
        "ICS",
        "Evidence preservation",
        "Law enforcement"
      ]
    },
    {
      "id": "ch-46.n.03",
      "title": "EMT Response Principles",
      "body": "Recognize the unusual: multiple patients with same presentation, unusual odors/vapors, abandoned devices, mass casualties without clear trauma. Notify immediately. Isolate and deny entry. Establish ICS. Request hazmat, law enforcement, and appropriate resources. Operate in cold zone only.",
      "terms": [
        "Recognition",
        "Notification",
        "Isolation",
        "ICS",
        "Cold zone"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-46.q.01",
      "q": "At a suspected terrorism scene, your FIRST priority is:",
      "opts": [
        "A. Treat the most critical patient",
        "B. Scene safety — including secondary device awareness",
        "C. Establish command",
        "D. Contact hospital"
      ],
      "ans": 1,
      "exp": "Scene safety is always first. Terrorism scenes routinely have secondary devices designed to kill first responders — never rush in.",
      "level1": {
        "q": "What is the primary concern at a terrorism scene?",
        "opts": [
          "A. Scene safety — including secondary device awareness",
          "B. Contact hospital"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-46.q.02",
      "q": "SLUDGEM symptoms indicate exposure to:",
      "opts": [
        "A. Explosive device",
        "B. Radiological agent",
        "C. Nerve agent or organophosphate",
        "D. Biological agent"
      ],
      "ans": 2,
      "exp": "SLUDGEM is the cholinergic toxidrome — characteristic of nerve agents (sarin, VX) and organophosphate pesticides.",
      "level1": {
        "q": "What is SLUDGEM symptoms indicate exposure to?",
        "opts": [
          "A. Nerve agent or organophosphate",
          "B. Explosive device"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-46.q.03",
      "q": "A secondary device is:",
      "opts": [
        "A. A backup communication system",
        "B. A second explosive designed to injure first responders",
        "C. A backup treatment protocol",
        "D. A secondary triage tag"
      ],
      "ans": 1,
      "exp": "Secondary devices are deliberately placed to detonate after first responders arrive — always assume risk until EOD clears the scene.",
      "level1": {
        "q": "What is a secondary device?",
        "opts": [
          "A. A second explosive designed to injure first responders",
          "B. A secondary triage tag"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-46.q.04",
      "q": "Signs suggesting a biological agent attack include:",
      "opts": [
        "A. Immediate mass casualties with burns",
        "B. Unusual disease clusters with delayed onset in multiple patients",
        "C. SLUDGEM symptoms",
        "D. Flash burns and blast injuries"
      ],
      "ans": 1,
      "exp": "Biological agents have delayed onset — recognition comes through unusual disease patterns, multiple patients with similar atypical illness.",
      "level1": {
        "q": "What are signs suggesting a biological agent attack?",
        "opts": [
          "A. Unusual disease clusters with delayed onset in multiple patients",
          "B. SLUDGEM symptoms"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-46.q.05",
      "q": "EMTs at a terrorism incident should operate in the:",
      "opts": [
        "A. Hot zone with hazmat PPE",
        "B. Warm zone for rapid triage",
        "C. Cold zone only",
        "D. Any zone with standard gloves"
      ],
      "ans": 2,
      "exp": "EMTs without specialized training must remain in the cold zone — treating decontaminated patients and supporting hazmat operations.",
      "level1": {
        "q": "What is the EMT's role in a terrorism response?",
        "opts": [
          "A. Cold zone only",
          "B. Hot zone with hazmat PPE"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-46.q.06",
      "q": "Shelter-in-place means:",
      "opts": [
        "A. Moving all patients to a nearby shelter",
        "B. Instructing people to remain inside sealed buildings",
        "C. Setting up a field hospital",
        "D. Establishing a staging area"
      ],
      "ans": 1,
      "exp": "Shelter-in-place directs people to stay inside with windows/doors sealed to prevent exposure to airborne chemical or biological agents.",
      "level1": {
        "q": "What is shelter-in-place?",
        "opts": [
          "A. Instructing people to remain inside sealed buildings",
          "B. Setting up a field hospital"
        ],
        "ans": 0
      }
    }
  ]
};
