// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch42: Chapter = {
  "id": "ch-42",
  "number": 42,
  "partId": "part-12",
  "title": "Ambulance Operations & Air Medical Response",
  "cards": [
    {
      "id": "ch-42.fc.01",
      "q": "What is the most important factor in safe ambulance driving?",
      "a": "Safety — not speed. Lights-and-siren use reduces response time minimally (1-3 min) while significantly increasing crash risk."
    },
    {
      "id": "ch-42.fc.02",
      "q": "What are the phases of an EMS call?",
      "a": "Preparation → Dispatch → Response → Scene → Transfer of care → Post-call (cleaning, restocking, documentation)."
    },
    {
      "id": "ch-42.fc.03",
      "q": "What is the safety zone around a helicopter landing zone (LZ)?",
      "a": "Minimum 100×100 feet on firm, level, debris-free ground — mark with lights at corners, clear of obstacles and power lines."
    },
    {
      "id": "ch-42.fc.04",
      "q": "What is the danger zone around a helicopter?",
      "a": "Never approach from the rear (tail rotor). Always approach from the front at a crouching posture after crew signals — wait for permission."
    },
    {
      "id": "ch-42.fc.05",
      "q": "What are due-regard laws?",
      "a": "Laws holding emergency vehicle operators to a standard of care — even with lights/siren, the driver must act with due regard for all persons."
    },
    {
      "id": "ch-42.fc.06",
      "q": "What are the most common causes of ambulance crashes?",
      "a": "Excessive speed, failure to stop at intersections, distraction, fatigue, not wearing seatbelts, and poor judgment."
    },
    {
      "id": "ch-42.fc.07",
      "q": "What checks should be performed on an ambulance before each shift?",
      "a": "Vehicle inspection (fluids, lights, tires), equipment inventory, medication check, oxygen supply, AED/monitor function, radio check."
    },
    {
      "id": "ch-42.fc.08",
      "q": "When is air medical transport indicated?",
      "a": "Long transport distances, inaccessible terrain, patient acuity requiring specialty care (trauma center, stroke center), or when ground transport is insufficient."
    }
  ],
  "notes": [
    {
      "id": "ch-42.n.01",
      "title": "Ambulance Operations",
      "body": "Ambulance driving requires skill and judgment. Lights/siren reduce response time by only 1-3 minutes on average while increasing crash risk substantially. At every intersection: slow, check traffic from all directions before proceeding. Wear seatbelts — EMT death in crashes is tragically preventable.",
      "terms": [
        "Due regard",
        "Lights and siren",
        "Intersection safety",
        "Seatbelt",
        "Pre-shift check"
      ]
    },
    {
      "id": "ch-42.n.02",
      "title": "Helicopter LZ Safety",
      "body": "Establish LZ: 100×100 ft minimum, firm and level, clear of debris and power lines. Mark corners with lights. Approach helicopter only from the front, crouching, with pilot/crew permission. Never approach tail rotor — invisible when spinning and instantly lethal.",
      "terms": [
        "LZ",
        "100x100",
        "Tail rotor",
        "Approach direction",
        "Debris clearance"
      ]
    },
    {
      "id": "ch-42.n.03",
      "title": "Air Medical Indications & Coordination",
      "body": "Consider air transport: trauma needing rapid access to trauma center, cardiac/stroke requiring specialty center, inaccessible terrain, mass casualties. Weather, darkness, and aircraft availability may limit use. Coordinate with dispatch early. Brief crew on patient status on landing.",
      "terms": [
        "Air medical",
        "Trauma center",
        "Terrain",
        "Weather limitations",
        "Patient briefing"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-42.q.01",
      "q": "Greatest risk factor for ambulance crashes is:",
      "opts": [
        "A. Driving at night",
        "B. Excessive speed and failure to stop at intersections",
        "C. Rain and poor weather",
        "D. Older ambulance models"
      ],
      "ans": 1,
      "exp": "Excessive speed and failure to properly stop at intersections are the top causes of ambulance crashes — use due regard always.",
      "level1": {
        "q": "What are the most common causes of ambulance crashes?",
        "opts": [
          "A. Excessive speed and failure to stop at intersections",
          "B. Driving at night"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-42.q.02",
      "q": "Due regard laws mean:",
      "opts": [
        "A. Lights/siren give unconditional right of way",
        "B. Emergency vehicle drivers must still drive with reasonable care for all persons",
        "C. All other vehicles must yield immediately",
        "D. Speed limits do not apply to ambulances"
      ],
      "ans": 1,
      "exp": "Due regard holds emergency drivers to a reasonable standard of care — running lights/siren does not eliminate liability for preventable crashes.",
      "level1": {
        "q": "What are due-regard laws?",
        "opts": [
          "A. Emergency vehicle drivers must still drive with reasonable care for all persons",
          "B. Speed limits do not apply to ambulances"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-42.q.03",
      "q": "Minimum helicopter landing zone size:",
      "opts": [
        "A. 50×50 feet",
        "B. 100×100 feet",
        "C. 200×200 feet",
        "D. 25×25 feet"
      ],
      "ans": 1,
      "exp": "Standard LZ minimum is 100×100 feet on firm, level, debris-free ground with clear approach and departure paths.",
      "level1": {
        "q": "What is the safety zone around a helicopter landing zone (LZ)?",
        "opts": [
          "A. 100×100 feet",
          "B. 50×50 feet"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-42.q.04",
      "q": "When approaching a helicopter, you should:",
      "opts": [
        "A. Run quickly from any direction",
        "B. Approach from the rear where the tail rotor is visible",
        "C. Approach from the front, crouching, after crew signals",
        "D. Approach at full height from the side"
      ],
      "ans": 2,
      "exp": "Always approach from the front (in pilot's view), crouching. NEVER approach from the rear — tail rotor is invisible when spinning and instantly lethal.",
      "level1": {
        "q": "What is the danger zone around a helicopter?",
        "opts": [
          "A. Approach from the front, crouching, after crew signals",
          "B. Run quickly from any direction"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-42.q.05",
      "q": "Pre-shift ambulance inspection includes:",
      "opts": [
        "A. Only fuel check",
        "B. Vehicle, equipment, medications, oxygen, and AED/monitor verification",
        "C. Only patient care equipment",
        "D. Medical director authorization"
      ],
      "ans": 1,
      "exp": "Full pre-shift checks ensure operational readiness: vehicle condition, all equipment present and functional, medications stocked, oxygen full, AED tested.",
      "level1": {
        "q": "What checks should be performed on an ambulance before each shift?",
        "opts": [
          "A. Vehicle, equipment, medications, oxygen, and AED/monitor verification",
          "B. Only fuel check"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-42.q.06",
      "q": "Lights and siren reduce response time by approximately:",
      "opts": [
        "A. 15-20 minutes",
        "B. 1-3 minutes",
        "C. 10 minutes",
        "D. Varies by distance only"
      ],
      "ans": 1,
      "exp": "Studies show lights/siren reduce response times by only 1-3 minutes on average — not worth the crash risk in non-critical calls.",
      "level1": {
        "q": "What is Lights and siren reduce response time by approximately?",
        "opts": [
          "A. 1-3 minutes",
          "B. 10 minutes"
        ],
        "ans": 0
      }
    }
  ]
};
