// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch40: Chapter = {
  "id": "ch-40",
  "number": 40,
  "partId": "part-11",
  "title": "Patients with Special Challenges",
  "cards": [
    {
      "id": "ch-40.fc.01",
      "q": "What should you do when a home ventilator alarms?",
      "a": "Disconnect from the ventilator and manually ventilate with BVM immediately — do not waste time troubleshooting on scene."
    },
    {
      "id": "ch-40.fc.02",
      "q": "What are communication strategies for hearing-impaired patients?",
      "a": "Face the patient, speak slowly and clearly (do not shout — distorts lip reading), use written communication, use a sign language interpreter if available."
    },
    {
      "id": "ch-40.fc.03",
      "q": "What is a DNR and how should an EMT respond to one?",
      "a": "Do Not Resuscitate — a legal document directing EMS not to resuscitate. Honor if valid, signed, and matches the patient's condition."
    },
    {
      "id": "ch-40.fc.04",
      "q": "What is a gastrostomy tube (G-tube)?",
      "a": "A tube placed through the abdominal wall into the stomach for feeding patients who cannot swallow."
    },
    {
      "id": "ch-40.fc.05",
      "q": "What is autism spectrum disorder (ASD) and how does it affect EMS care?",
      "a": "A developmental disorder affecting communication and social interaction — patients may be hypersensitive to touch, lights, and noise. Use calm, predictable communication."
    },
    {
      "id": "ch-40.fc.06",
      "q": "What is a tracheostomy?",
      "a": "A surgically created opening in the neck into the trachea for breathing — patients may require suctioning and may not be able to speak."
    },
    {
      "id": "ch-40.fc.07",
      "q": "What are special considerations for bariatric patients?",
      "a": "Need for bariatric equipment and additional personnel for lifting. Airway management is more difficult. Difficult vascular access. OSA and hypoventilation risk."
    },
    {
      "id": "ch-40.fc.08",
      "q": "What is a PICC line?",
      "a": "Peripherally Inserted Central Catheter — a long-term IV catheter. EMTs should not access these without specific training and protocol authorization."
    }
  ],
  "notes": [
    {
      "id": "ch-40.n.01",
      "title": "Technology-Dependent Patients",
      "body": "More patients are managed at home with medical technology. EMTs encounter ventilators, feeding tubes, tracheostomies, CPAP/BiPAP, implanted ports, and insulin pumps. For ventilator malfunction: disconnect and ventilate with BVM. For tracheostomy: suction if mucus plug suspected.",
      "terms": [
        "Home ventilator",
        "Tracheostomy",
        "G-tube",
        "PICC",
        "BVM ventilation"
      ]
    },
    {
      "id": "ch-40.n.02",
      "title": "Communication Barriers",
      "body": "Visual impairment: narrate clearly, identify yourself verbally. Hearing impairment: face the patient, use written communication, support lip-reading. Speech impairment: allow extra time, use yes/no questions. ASD: reduce stimuli, be calm and predictable, avoid surprising movements or sounds.",
      "terms": [
        "Hearing impairment",
        "Visual impairment",
        "Cognitive impairment",
        "ASD",
        "Stimuli reduction"
      ]
    },
    {
      "id": "ch-40.n.03",
      "title": "Special Population Considerations",
      "body": "Bariatric patients require specialized equipment, additional personnel, and awareness of airway and access challenges. Homeless patients: exposure, infection, neglect, mental health, substance use. Terminally ill: honor advance directives/DNR. Treat all patients with equal dignity and respect.",
      "terms": [
        "Bariatric",
        "Dignity",
        "Advance directive",
        "Terminally ill",
        "Special needs"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-40.q.01",
      "q": "When a home ventilator patient's ventilator alarms, the EMT should:",
      "opts": [
        "A. Call the manufacturer",
        "B. Disconnect and ventilate with BVM immediately",
        "C. Silence the alarm and reassess",
        "D. Increase the ventilator settings"
      ],
      "ans": 1,
      "exp": "Ventilator malfunction = disconnect and manually ventilate with BVM. Do not waste time troubleshooting — manual ventilation is immediately safe.",
      "level1": {
        "q": "What should you do when a home ventilator alarms?",
        "opts": [
          "A. Disconnect and ventilate with BVM immediately",
          "B. Call the manufacturer"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-40.q.02",
      "q": "For a hearing-impaired patient, effective communication includes:",
      "opts": [
        "A. Shouting louder to be heard",
        "B. Facing the patient and speaking clearly, using written communication",
        "C. Ignoring them and speaking to family only",
        "D. Rapid yes/no questioning only"
      ],
      "ans": 1,
      "exp": "Face the patient, speak clearly (shouting distorts lip reading), use written pads, and allow time for responses.",
      "level1": {
        "q": "What are communication strategies for hearing-impaired patients?",
        "opts": [
          "A. Facing the patient and speaking clearly, using written communication",
          "B. Shouting louder to be heard"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-40.q.03",
      "q": "A valid DNR should be:",
      "opts": [
        "A. Ignored in a cardiac arrest",
        "B. Honored if properly signed and matching the patient's condition",
        "C. Followed only if family agrees",
        "D. Disregarded if the patient is young"
      ],
      "ans": 1,
      "exp": "A valid, properly executed DNR is a legal document and must be honored. If validity is in question, begin resuscitation while contacting medical direction.",
      "level1": {
        "q": "What is a DNR and how should an EMT respond to one?",
        "opts": [
          "A. Honored if properly signed and matching the patient's condition",
          "B. Ignored in a cardiac arrest"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-40.q.04",
      "q": "Patients with autism spectrum disorder may:",
      "opts": [
        "A. Respond normally to all EMS interventions",
        "B. Be hypersensitive to touch, light, and noise requiring modified communication",
        "C. Always have intellectual disability",
        "D. Prefer loud environments"
      ],
      "ans": 1,
      "exp": "ASD patients may have significant sensory sensitivities — reduce lights, noise, and unexpected touch. Use calm, predictable communication.",
      "level1": {
        "q": "What is autism spectrum disorder (ASD) and how does it affect EMS care?",
        "opts": [
          "A. Be hypersensitive to touch, light, and noise requiring modified communication",
          "B. Prefer loud environments"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-40.q.05",
      "q": "A gastrostomy tube (G-tube) is used for:",
      "opts": [
        "A. Urinary drainage",
        "B. Feeding patients who cannot swallow",
        "C. Chest drainage",
        "D. Airway management"
      ],
      "ans": 1,
      "exp": "G-tubes deliver nutrition directly into the stomach through the abdominal wall for patients who cannot swallow due to neurological or structural conditions.",
      "level1": {
        "q": "What is a gastrostomy tube (G-tube)?",
        "opts": [
          "A. Feeding patients who cannot swallow",
          "B. Chest drainage"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-40.q.06",
      "q": "Bariatric patients present special challenges including:",
      "opts": [
        "A. Easier vascular access",
        "B. Airway management difficulties and need for additional personnel",
        "C. Lower fall risk",
        "D. Faster response to medications"
      ],
      "ans": 1,
      "exp": "Obesity creates difficult airway, BVM seal challenges, difficult vascular access, and requires additional personnel and specialized equipment.",
      "level1": {
        "q": "What are special considerations for bariatric patients?",
        "opts": [
          "A. Airway management difficulties and need for additional personnel",
          "B. Lower fall risk"
        ],
        "ans": 0
      }
    }
  ]
};
