// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch45: Chapter = {
  "id": "ch-45",
  "number": 45,
  "partId": "part-12",
  "title": "Multiple-Casualty Incidents & Incident Management",
  "cards": [
    {
      "id": "ch-45.fc.01",
      "q": "What is an MCI?",
      "a": "Mass Casualty Incident — any event producing more patients than available resources can handle with standard protocols."
    },
    {
      "id": "ch-45.fc.02",
      "q": "What does START stand for?",
      "a": "Simple Triage And Rapid Treatment — a rapid assessment system using respirations, perfusion, and mental status to sort patients."
    },
    {
      "id": "ch-45.fc.03",
      "q": "What are the four START triage categories?",
      "a": "Immediate (Red), Delayed (Yellow), Minor (Green/walking wounded), Expectant/Dead (Black)."
    },
    {
      "id": "ch-45.fc.04",
      "q": "START criteria for Immediate (Red) tag?",
      "a": "Respirations >30/min OR absent (restored by repositioning), radial pulse absent, or unable to follow simple commands."
    },
    {
      "id": "ch-45.fc.05",
      "q": "What is the Incident Command System (ICS)?",
      "a": "A standardized management structure for emergency incidents providing clear command, coordination, and communication."
    },
    {
      "id": "ch-45.fc.06",
      "q": "What is NIMS?",
      "a": "National Incident Management System — ensures consistent incident management across all government levels and agencies."
    },
    {
      "id": "ch-45.fc.07",
      "q": "What is the Medical Branch in ICS?",
      "a": "Oversees triage, treatment, and transport of all patients at an MCI — usually led by a senior EMS supervisor."
    },
    {
      "id": "ch-45.fc.08",
      "q": "What does 'Expectant' (black tag) mean?",
      "a": "The injury is unsurvivable given current resources — lowest priority. Does not always mean the patient is currently dead."
    }
  ],
  "notes": [
    {
      "id": "ch-45.n.01",
      "title": "START Triage System",
      "body": "START: assess respirations first. Absent → reposition → if still absent = black or immediate (if respirations return). Respirations >30 = immediate. Then check radial pulse: absent = immediate. Then mental status: can't follow commands = immediate. All other positives: delayed. Walking wounded = minor.",
      "terms": [
        "START",
        "Immediate (Red)",
        "Delayed (Yellow)",
        "Minor (Green)",
        "Expectant (Black)"
      ]
    },
    {
      "id": "ch-45.n.02",
      "title": "Incident Command System",
      "body": "ICS provides: unified command, clear roles, interoperability between agencies. Key positions: Incident Commander, Operations, Planning, Logistics, Finance/Admin. Span of control: 3-7 per supervisor (ideal: 5). EMS functions under Operations as Medical Branch.",
      "terms": [
        "ICS",
        "Incident Commander",
        "Span of control",
        "Unified command",
        "NIMS"
      ]
    },
    {
      "id": "ch-45.n.03",
      "title": "EMT Role at MCIs",
      "body": "Follow ICS — report to your supervisor, accept your assigned role. Do not self-deploy. Do not spend excessive time on any one patient. Document triage tags. Communicate resource needs through chain of command. Triage first, then treat in assigned area.",
      "terms": [
        "Chain of command",
        "Resource management",
        "Triage tags",
        "Self-deployment",
        "Medical Branch"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-45.q.01",
      "q": "An MCI is declared when:",
      "opts": [
        "A. More than 5 patients",
        "B. Available resources are exceeded by patient numbers",
        "C. Hospital is on diversion",
        "D. Two ambulances respond"
      ],
      "ans": 1,
      "exp": "MCI is relative to available resources — even 3 critical patients can be an MCI for a rural agency with one unit.",
      "level1": {
        "q": "What is an MCI?",
        "opts": [
          "A. Available resources are exceeded by patient numbers",
          "B. More than 5 patients"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-45.q.02",
      "q": "A patient with respirations 32/min is tagged:",
      "opts": [
        "A. Green",
        "B. Yellow",
        "C. Red",
        "D. Black"
      ],
      "ans": 2,
      "exp": "Respirations >30/min = Immediate (Red) tag in START triage.",
      "level1": {
        "q": "What is patient with respirations 32/min is tagged?",
        "opts": [
          "A. Red",
          "B. Green"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-45.q.03",
      "q": "Expectant (black tag) in triage means:",
      "opts": [
        "A. Definitely dead",
        "B. Unsurvivable given available resources — lowest priority",
        "C. Needs immediate surgery",
        "D. Ambulatory patient"
      ],
      "ans": 1,
      "exp": "Black/Expectant means the injury is unsurvivable given current resources — limited resources are better used on survivable patients.",
      "level1": {
        "q": "What does 'Expectant' (black tag) mean?",
        "opts": [
          "A. Unsurvivable given available resources — lowest priority",
          "B. Definitely dead"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-45.q.04",
      "q": "The Incident Commander is responsible for:",
      "opts": [
        "A. Treating the most critical patient",
        "B. Overall management, objectives, resources, and safety",
        "C. Driving the command vehicle",
        "D. Hospital notification only"
      ],
      "ans": 1,
      "exp": "The Incident Commander has overall authority for all aspects of the incident — objectives, resources, and responder safety.",
      "level1": {
        "q": "What is the Incident Command System (ICS)?",
        "opts": [
          "A. Overall management, objectives, resources, and safety",
          "B. Hospital notification only"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-45.q.05",
      "q": "Span of control in ICS refers to:",
      "opts": [
        "A. Geographic area of incident",
        "B. Number of personnel one supervisor can effectively manage (3-7)",
        "C. Radio frequency range",
        "D. Number of agencies responding"
      ],
      "ans": 1,
      "exp": "ICS span of control (3-7 per supervisor, ideal = 5) ensures effective supervision without management breakdown.",
      "level1": {
        "q": "What is Span of control in ICS refers to?",
        "opts": [
          "A. Number of personnel one supervisor can effectively manage (3-7)",
          "B. Radio frequency range"
        ],
        "ans": 0
      }
    },
    {
      "id": "ch-45.q.06",
      "q": "At an MCI, EMTs should:",
      "opts": [
        "A. Self-deploy to critical patients",
        "B. Report to assigned supervisor and follow ICS",
        "C. Begin treating before reporting in",
        "D. Wait in ambulance until all patients triaged"
      ],
      "ans": 1,
      "exp": "Follow ICS — report to your supervisor, accept your role, work within the command structure. Self-deployment creates chaos.",
      "level1": {
        "q": "What is At an MCI, EMTs should?",
        "opts": [
          "A. Report to assigned supervisor and follow ICS",
          "B. Self-deploy to critical patients"
        ],
        "ans": 0
      }
    }
  ]
};
