// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ch41: Chapter = {
  "id": "ch-41",
  "number": 41,
  "partId": "part-11",
  "title": "The Combat Veteran",
  "cards": [
    {
      "id": "ch-41.fc.01",
      "q": "What is PTSD and how does it affect EMS care?",
      "a": "Post-Traumatic Stress Disorder — a mental health condition from traumatic events. Combat veterans may have exaggerated startle response, flashbacks, and hypervigilance affecting cooperation with care."
    },
    {
      "id": "ch-41.fc.02",
      "q": "What is traumatic brain injury (TBI) common in combat veterans?",
      "a": "TBI from blast exposure — may cause cognitive impairment, headaches, memory issues, and behavioral changes. May not be apparent on initial assessment."
    },
    {
      "id": "ch-41.fc.03",
      "q": "What special communication approach is used with combat veterans?",
      "a": "Identify yourself clearly, explain what you are doing before doing it, avoid startling, respect personal space, be aware of triggers (uniforms, loud noises, restraints)."
    },
    {
      "id": "ch-41.fc.04",
      "q": "What are common injuries in combat veterans that affect EMS care?",
      "a": "TBI, PTSD, limb amputations, chronic pain, spinal injuries, and burn scars — affects assessment, splinting, airway management, and IV access."
    },
    {
      "id": "ch-41.fc.05",
      "q": "What is military sexual trauma (MST)?",
      "a": "Sexual assault or harassment during military service — common and may affect patient cooperation with examination and personal contact."
    },
    {
      "id": "ch-41.fc.06",
      "q": "What is moral injury in veterans?",
      "a": "Psychological damage from participating in or witnessing events that violate one's moral beliefs — distinct from PTSD, contributes to depression, guilt, and suicide risk."
    },
    {
      "id": "ch-41.fc.07",
      "q": "Why might a combat veteran refuse transport?",
      "a": "Autonomy, mistrust of medical systems, past trauma, PTSD symptoms, or substance use. Use therapeutic communication and explain the importance of evaluation."
    },
    {
      "id": "ch-41.fc.08",
      "q": "How do prosthetic limbs affect EMT assessment?",
      "a": "Standard BP cuffs and pulse oximetry may not work on prosthetic limbs. Assess opposite limb. Be aware of phantom limb pain — a real experience despite absent limb."
    }
  ],
  "notes": [
    {
      "id": "ch-41.n.01",
      "title": "Understanding the Combat Veteran",
      "body": "Combat veterans may have complex physical and psychological injuries from service. PTSD, TBI, chronic pain, and moral injury are common. Approach with respect, identify yourself clearly, explain all actions in advance. Avoid triggers: sudden movements, loud noises, restraints without explanation.",
      "terms": [
        "PTSD",
        "TBI",
        "Moral injury",
        "MST",
        "Hypervigilance"
      ]
    },
    {
      "id": "ch-41.n.02",
      "title": "Physical Assessment Considerations",
      "body": "Amputees: assess on intact limbs. Prosthetics may interfere with monitoring. Burn scars: difficult IV access. Spinal injuries: may affect sensation and response to pain. TBI: cognitive and behavioral changes. Chronic pain may alter the patient's pain reporting and mask new injuries.",
      "terms": [
        "Amputation",
        "Prosthetics",
        "Burn scars",
        "Phantom limb pain",
        "Chronic pain"
      ]
    },
    {
      "id": "ch-41.n.03",
      "title": "Suicide Risk in Veterans",
      "body": "Veterans have a significantly elevated suicide risk compared to civilians. Ask directly about suicidal ideation — asking does not increase risk. Take all statements seriously. Transport for psychiatric evaluation. Be aware of access to weapons. Coordinate with VA resources when possible.",
      "terms": [
        "Suicide risk",
        "Suicidal ideation",
        "VA resources",
        "Direct questioning",
        "Safe transport"
      ]
    }
  ],
  "quiz": [
    {
      "id": "ch-41.q.01",
      "q": "When treating a combat veteran with PTSD, you should:",
      "opts": [
        "A. Approach quickly and apply restraints if agitated",
        "B. Identify yourself, explain all actions in advance, avoid startling the patient",
        "C. Treat identically to any civilian patient",
        "D. Always request law enforcement presence"
      ],
      "ans": 1,
      "exp": "PTSD triggers include sudden movements, restraints, uniforms, and loud noises. Identify yourself, explain each action before doing it, and respect personal space."
    },
    {
      "id": "ch-41.q.02",
      "q": "Blast-related TBI in combat veterans may present as:",
      "opts": [
        "A. Always immediately obvious on assessment",
        "B. Cognitive impairment, memory issues, headaches, and behavioral changes that may be subtle",
        "C. Never affecting behavior",
        "D. Always causing unconsciousness"
      ],
      "ans": 1,
      "exp": "Blast-related TBI may cause subtle cognitive and behavioral changes that aren't immediately apparent — ask about head trauma history and symptoms."
    },
    {
      "id": "ch-41.q.03",
      "q": "When assessing a veteran with a prosthetic limb:",
      "opts": [
        "A. Use the prosthetic limb for BP and SpO2",
        "B. Assess on the intact opposite limb",
        "C. Avoid any assessment",
        "D. Assume all readings from prosthetic site are normal"
      ],
      "ans": 1,
      "exp": "Prosthetics cannot be used for standard monitoring — BP cuffs and pulse oximeters must be placed on intact limbs."
    },
    {
      "id": "ch-41.q.04",
      "q": "Veterans have elevated suicide risk. Asking about suicidal ideation:",
      "opts": [
        "A. Increases the risk of suicide",
        "B. Does not increase risk and is essential for assessment",
        "C. Should only be done by mental health professionals",
        "D. Is illegal for EMTs to ask"
      ],
      "ans": 1,
      "exp": "Research shows that asking directly about suicide does NOT increase risk — it is essential for assessment and getting the patient appropriate help."
    },
    {
      "id": "ch-41.q.05",
      "q": "Military sexual trauma (MST) may affect EMS care because:",
      "opts": [
        "A. It has no effect on EMS interactions",
        "B. It may affect patient cooperation with physical examination and personal contact",
        "C. It only affects female veterans",
        "D. Veterans never disclose it"
      ],
      "ans": 1,
      "exp": "MST survivors may be reluctant to allow physical examination, may have triggers around personal contact, and may need same-gender providers if possible."
    },
    {
      "id": "ch-41.q.06",
      "q": "Phantom limb pain in amputees is:",
      "opts": [
        "A. Not a real phenomenon",
        "B. A real pain experience in an absent limb that should be acknowledged and treated",
        "C. Always psychological only",
        "D. Not relevant to EMS care"
      ],
      "ans": 1,
      "exp": "Phantom limb pain is a real neurological phenomenon — the brain continues to process pain signals from the absent limb. Acknowledge it and treat the patient's pain."
    }
  ]
};
