// scripts/migrate-content.mjs
// One-shot migration: parses legacy/index.html, emits per-chapter TS files.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const html = readFileSync(resolve(root, 'legacy/index.html'), 'utf8');

function sliceBetween(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker);
  if (start === -1) throw new Error(`Marker not found: ${startMarker}`);
  const end = source.indexOf(endMarker, start);
  if (end === -1) throw new Error(`End marker not found: ${endMarker}`);
  return source.slice(start, end);
}

const partsBlock = sliceBetween(html, 'const PARTS =', 'const DATA =');
const dataBlock  = sliceBetween(html, 'const DATA =', '\nlet selKey');

function evalLiteral(src, name) {
  const expr = src.replace(`const ${name} =`, '').trim().replace(/;\s*$/, '');
  return new Function(`return (${expr});`)();
}

const PARTS = evalLiteral(partsBlock, 'PARTS');
const DATA  = evalLiteral(dataBlock,  'DATA');

function chapterId(chKey) {
  const n = parseInt(chKey.replace(/[^\d]/g, ''), 10);
  return { id: `ch-${String(n).padStart(2, '0')}`, number: n };
}

function pad2(i) { return String(i).padStart(2, '0'); }

const partsOut = PARTS.map((p, i) => {
  const number = i + 1;
  const id = `part-${pad2(number)}`;
  const chapterIds = p.topics.map(t => chapterId(t.ch).id);
  return { id, number, label: p.label, chapterIds };
});

const chapterToPart = new Map();
partsOut.forEach(p => p.chapterIds.forEach(cid => chapterToPart.set(cid, p.id)));

const chapterTitles = new Map();
PARTS.forEach(p => p.topics.forEach(t => {
  const { id } = chapterId(t.ch);
  chapterTitles.set(id, t.title);
}));

mkdirSync(resolve(root, 'src/lib/content/chapters'), { recursive: true });

const partsTs =
`// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Part } from './types';

export const PARTS: Part[] = ${JSON.stringify(partsOut, null, 2)};
`;
writeFileSync(resolve(root, 'src/lib/content/parts.ts'), partsTs);

const writtenChapters = [];
for (const chKey of Object.keys(DATA)) {
  const { id, number } = chapterId(chKey);
  const partId = chapterToPart.get(id);
  const title = chapterTitles.get(id);
  if (!partId || !title) throw new Error(`Missing index for ${chKey}`);

  const d = DATA[chKey];
  const cards = (d.cards || []).map((c, i) => ({
    id: `${id}.fc.${pad2(i + 1)}`, q: c.q, a: c.a,
  }));
  const notes = (d.notes || []).map((n, i) => ({
    id: `${id}.n.${pad2(i + 1)}`, title: n.title, body: n.body, terms: n.terms || [],
  }));
  const quiz = (d.quiz || []).map((q, i) => ({
    id: `${id}.q.${pad2(i + 1)}`, q: q.q, opts: q.opts, ans: q.ans, exp: q.exp,
  }));

  const chapter = { id, number, partId, title, cards, notes, quiz };

  const varName = `ch${pad2(number)}`;
  const ts =
`// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from '../types';

export const ${varName}: Chapter = ${JSON.stringify(chapter, null, 2)};
`;
  writeFileSync(resolve(root, `src/lib/content/chapters/ch-${pad2(number)}.ts`), ts);
  writtenChapters.push({ id, number });
}

const imports = writtenChapters
  .sort((a, b) => a.number - b.number)
  .map(c => `import { ch${pad2(c.number)} } from './chapters/ch-${pad2(c.number)}';`)
  .join('\n');

const arrItems = writtenChapters
  .sort((a, b) => a.number - b.number)
  .map(c => `ch${pad2(c.number)}`)
  .join(', ');

const indexTs =
`// AUTO-GENERATED by scripts/migrate-content.mjs. Edit by hand thereafter.
import type { Chapter } from './types';
${imports}

export const CHAPTERS: Chapter[] = [${arrItems}];

const byId = new Map(CHAPTERS.map(c => [c.id, c]));

export function getChapter(id: string): Chapter | undefined {
  return byId.get(id);
}

export function getAllCards() {
  return CHAPTERS.flatMap(ch => ch.cards.map(card => ({ chapterId: ch.id, card })));
}
`;
writeFileSync(resolve(root, 'src/lib/content/index.ts'), indexTs);

console.log(`Wrote parts.ts (${partsOut.length} parts) and ${writtenChapters.length} chapter files.`);
